### PR TITLE
changed Vrtra's hp to reflect retail.

### PR DESCRIPTION
**Pull request by Fiocitrine**
this shit is whack 100k to 40k

### CODE REVIEW

**Comment by Hozu** [comment]
The wiki is wrong about that, heh. Have you tried K club DRK burning Vrtra on retail? If it were only 40k HP, it'd have been much easier than it actually was.

**Comment by Deadwing888** [comment]
Throw this out immediately.

**Comment by Deadwing888** [comment]
https://github.com/DarkstarProject/darkstar/pull/1765

**Comment by Fiocitrine** [comment]
Ok so I  parsed Vrtra's hp via facebook and I got a few different numbers. First one ( https://www.youtube.com/watch?v=MSaJYauy1GA )  I got around 93251 hp without regen. The second one ( https://www.youtube.com/watch?v=pbwivxFeuBE ) I got 79643 hp. I know that those are CLOSE to 100k but they are NOT 100k. I'll look up more videos to further parse the damage.

**Comment by TeoTwawki** [comment]
Your numbers 2 from watching vids are pretty far off from each other. And thats not a parse, what can you possibly be doing, pausing the video every time the damage hits the log to add it?

**Comment by TeoTwawki** [comment]
You know what, nvm, deleting my own comment this is to crazy

**Comment by Fiocitrine** [comment]
Just forget it, I'm obviously wrong in your eyes and I don't want to argue about this.

**Comment by TeoTwawki** [comment]
OR thats obviously not what "parse" means

**Comment by Fiocitrine** [comment]
parse
pärs/Submit
verb
1.
analyze (a sentence) into its parts and describe their syntactic roles.
nounCOMPUTING
1.
an act of or the result obtained by parsing a string or a text.

**Comment by Fiocitrine** [comment]
I'm done

**Comment by TeoTwawki** [comment]
Clearly you are too butthurt to be done

**Comment by TeoTwawki** [comment]
And parsing is not what you did in the ffxi sense, take you dictionary and cram it

**Comment by takhlaq** [comment]
get on retail and kill vrtra a few times while parsing actual numbers sent to the client (so no DOTs)
then you can easily figure out the regen and a fairly accurate figure for total hp
throwing a tantrum doesnt really push arguments for which value is correct but solid data definitely would!

**Pull request closed without merging**
