### PR TITLE
Standardizing format of all BLU spells.

### PR DESCRIPTION
**Pull request by helixhamin**
Please note, this does not change any spells, or fix any spells, it is only to standardize the spell template.

### CODE REVIEW

**Comment by teschnei** [comment]
change your editor to use spaces instead of tabs :p

**Comment by helixhamin** [comment]
Okay, lol, I just added the tabs myself.
How many spaces would you prefer for each nested statement? Or should I just align the spaces to match a single tab in my notepad++?

**Comment by teschnei** [comment]
settings -> preferences -> tab settings -> tab size: 4, check replace by space

**Comment by helixhamin** [comment]
Okay, tabs poofed, all tabs ctrl+hed with 4 spaces in all 110 files.

**Pull request merged**
