### PR TITLE
Fix CN FoV

### PR DESCRIPTION
**Pull request by helixhamin**
Event finish numbers were 1 off

### CODE REVIEW

**Comment by Hozu** [comment]
My bad, I swear I got all of those issues...

**Comment by xdemolish** [comment]
looks good, just need you to rebase/squash :)

**Comment by helixhamin** [comment]
I think I squashed? I did a hard reset...
Sadly, hard to figure out how to do on tortoisegit.

**Comment by xdemolish** [comment]
rebase > force rebase >  ctrl click the commits you wanna squash > right click + squash > change commit message if needed > commit and force push

**Comment by helixhamin** [comment]
Okay, I fail at this. Trying to do this between three different systems, and I have tried every squash, force push, rebase, etc, that I can. Possibly it is because to replicate the pull, I reclone onto a new system to try to rebase and squash? I have done before, but only when the commit is all done on a single PC. I know no one likes close and new pull open, but almost ready to do that since apparently GUI menu through tortoisegit doesn't seem to work...

**Comment by Fiocitrine** [comment]
When you rebase, do you click the force rebase box on the right?

**Comment by helixhamin** [comment]
@Fiocitrine Yes, I have tried. I do not see a change. Perhaps my problem is this:

First release: I edited directly through Github website UI, noticed that the others were not aligned, and fix the second.
Second release: I pulled the tree to my work notebook and tried to force and squash. No change observed in Github.
Third release: I pulled the tree to my home PC, since I have more time to try, force rebase, hard reset, rebase, squash, key getting git did not exit clean errors, or other errors, and every time I got it to force rebase or squash without submission errors, I saw no results on the pull.

I am unsure if it is because of the way I did the releases, but I see no end results using tortoisegit rebase option, tortoisegit merge with squash option, tortoisegit rebase with force rebase option selected. Maybe it is because after I made the web based changes, then pulled, it claims there is nothing to rebase, squash, or otherwise? I think I fail at git.

**Comment by xdemolish** [comment]
rebase onto dsp master not your fork

**Comment by bendangelo** [comment]
It's just two commits. Won't hurt merging this. Any objections?

**Comment by helixhamin** [comment]
@bendangelo No worries Ben, I have been racking my brain, trying every option I can think of to get this commit fixed, and cannot seem to do it. I figured out what @xdemolish said about rebasing from master, but I think it is just beyond me. So, I can always close and redo it. At least when I do it locally, instead of from the webpage, I know how to squash and rebase. I have done that successfully, I guess I just messed up somewhere else. Not your guy's fault.

**Comment by xdemolish** [comment]
> At least when I do it locally, instead of from the webpage, I know how to squash and rebase.

that's exactly how you do it, just force push once you've rebased locally and it'll reflect on the pull request
don't use the webpage ever

**Pull request merged**
