### PR TITLE
Update packet parsing for guild vendor (not honoring quantity)

### LINKED ISSUE #3872: Cannot spend Guild Points at any guild rep
**_I have:_**

- [X] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [X] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **30170427_0**

**_Server Version_** (type `@revision` in game) **Unknown**

**_Source Branch_** (master/stable) **Master**

**_Additional Information_** (Steps to reproduce/Expected behavior) Players on my server cannot spend GP on guild items. All of the trade reps behave the same; the dialogue works but once a selection of and item is made the item is not added, the GP are not removed, and the dialogue loops back to the "Exchange points for..." option window. Things I've noted:
- Performs this way with HQ crystals (all of them), key items, and regular items.
- When selecting a HQ crystal and after entering the number of crystals desired, the dialogue box "Proceed with the transaction?" displays the correct GP amount possessed by the character. Upon going through the purchase process again without deactivating/reactivating the NPC the GP display will change to the itemID of the previous HQ crystal selected, not the character's actual GP amount. This does not happen with key items or regular items.
- If a character does not have the GP to buy an item, no notification is made and the dialogue loop continues.
- I'm working with the 1/16/2017 version of the crafting.lua file, completely unmodified.
- I last updated my client on 5/11/2017 to see if that would fix the issue (it did not).
- The server log produces no errors and does not display inserted print commands if the command is put into the crafting.lua unionRepresentativeTriggerFinish function, but the same command will display when inserted into the NPC script for the corresponding CSID option.
- Link to screenshots and dump of server log: https://drive.google.com/open?id=0B8DHaluZr_0Ed2FobE1MVXpkOVk
- Link to DSP forum post: https://forums.dspt.info/viewtopic.php?f=15&t=21297&p=35953#p35953

### PR DESCRIPTION
**Pull request by ddumont**
Fixes #3872

Is there a function for adding multiple items to a player's inventory?

### CODE REVIEW

**Comment by ddumont** [comment]
Will likely need to bump min client version.

**Comment by teschnei** [comment]
addItem's second parameter is quantity (if it is a number)

**Comment by ddumont** [comment]
cool.   I'll look into that tomorrow.

**Comment by ddumont** [comment]
@teschnei Updated to honor quantity.

**Comment by teschnei** [comment]
We're gonna need to update the min version before I can merge this

**Comment by ddumont** [comment]
Something I should do?  where is that?

**Comment by teschnei** [comment]
ask in IRC when you've time

**Comment by TeoTwawki** [comment]
@teschnei @ddumont I got a minion trying to get it done right now actually

**Comment by teschnei** [comment]
just the person I was going to ask him to talk to!

**Comment by ibm2431** [comment]
I was 90% done with April, but then my father died and I've since been on the other side of the country without my dev machine and very limited internet access. There was a very brief period of time last week which I had access to my box, so I could finish April and push, but didn't do a PR since it'd be a version behind the current one pushed by POL (ie: people couldn't upgrade to match server):

https://github.com/ibm2431/darkstar/tree/version-update

I have the May version update saved on that machine (in case June hits POL servers before I get back), but won't be able to access it again until after June 15th.

**Comment by TeoTwawki** [comment]
@ibm2431 we're almost done getting PR ready for version 30170427_0 your branch there says 30170329_0 so we're a little bit ahead of you now.

**Comment by TeoTwawki** [comment]
versions updated now, so merging

**Comment by TeoTwawki** [comment]
err..there appears to be something else mistakenly mixed in now

**Comment by ddumont** [comment]
Hmm.   Thanks for catching that.  I will fix tonight.

**Comment by TeoTwawki** [comment]
roll back history / rebase, let us know when done (don't simply close the pr to make a new one that isn't needed, just force-push the corrected local copy over the remote, and if you are editing via website..don't do that 😄 )

**Comment by ddumont** [comment]
Yep, I just need to can those last 2 commits.

**Comment by ddumont** [comment]
fixed.

**Pull request merged**
