### PR TITLE
Formatting. Again.

### PR DESCRIPTION
**Pull request by TeoTwawki**
~~Thou shalt not stray from the styling DSP has given thee~~ *AHEM*

so, I corrected a lot of crap in the formatting. no code changes. And I avoided anything I thought might be changed in the bcnmcrap branch.

### CODE REVIEW

**Comment by TeoTwawki** [comment]
so now there are a few code changes. Because params in a few scripts were broken/repeated/missing linebreaks..

**Comment by TeoTwawki** [comment]
-_taps foot impatiently, like most of our new contributors do_-

**Comment by zynjec** [comment]
Don't modify 4500 files in one PR then!

**Comment by TeoTwawki** [comment]
its a mass nukage of pure formatting stuff! until the last 2 commit which only changed 4 files and can be reviewed by looking at just those.

seriously you don't need to look at all 4500 fiels when all them removed the same block comment of:
```lua
-------------------
-- functionnamehere
-------------------
```

its retarded that those ever existed,

**Comment by TeoTwawki** [comment]
rebased

**Comment by TeoTwawki** [comment]
rebased again

**Pull request merged**
