### PR TITLE
update waag-deeg merchant stocks in lower jeuno

### PR DESCRIPTION
**Pull request by tristamgreen**
Update NPCs Hasim and Susu in Waag-Deeg's Magic Shop in Lower Jeuno to current retail values as of 3/17/2018 (both NPCs were streamlined and expanded in 2015).

http://ffxiclopedia.wikia.com/wiki/Hasim

http://ffxiclopedia.wikia.com/wiki/Susu

### CODE REVIEW

**Comment by TeoTwawki** [comment]
like this  
https://github.com/DarkstarProject/darkstar/commit/f3c320c7dc1567f900b9294e3631589a023a2279#diff-dd17e7c50a6d09871ba1ddea4e01960fR27

**Comment by TeoTwawki** [comment]
if not its ok I'll get to them eventually :+1:

**Comment by tristamgreen** [comment]
should i do it in my branch, kill this pr and do a new one? sorry was just keeping the syntax with how it was (i don't mind though just need to know the proper process)

**Comment by TeoTwawki** [comment]
any changes added to the same branch and pushed will auto update the pull request, no need to close :smile:

**Comment by TeoTwawki** [comment]
> sorry was just keeping the syntax with how it was (i don't mind though just need to know the proper process)

nothin to be sorry about, I'm still slowly transitioning the format to match agreed upon conventions that we suck at documenting in this project is all.

**Comment by tristamgreen** [comment]
i am about to head to dinner but can when i return

**Comment by tristamgreen** [comment]
hopefully i changed the right thing, i moved the end bracket and updated the indents on comments as best i could tell.

**Comment by TeoTwawki** [comment]
the tabs kinda threw it off on you, I should noticed it before and told you about it but just took care of it myself instead of pestering you with more revisions. most editor shave settings to let you replace tabs with spaces automatic as you type. We use 4 spaces per indent here (ages ago I demanded we "pick one!" and thats the result)

**Comment by TeoTwawki** [comment]
oh. webeditor sucks. the only thing worse is the github app. I recommended tortoisegit (which requires git for windows) for new people who are on windows, because its really easy to use/learn on. its a shell extension style of using git. if you are a linux person I don't know of anything better than just learning command line, Any help you need hit us up in our discord.

**Pull request merged**
