### PR TITLE
NM Madness! Buncha NMs Added

### PR DESCRIPTION
**Pull request by Fiocitrine**
Added NM and fixed dropID of Lamina

### CODE REVIEW

**Comment by gedads** [comment]
Hi, if it helps:
[07:37:47] 0x0E, 68 Bytes - (Update) Entity
   0  1  2  3  4  5  6  7  8  9  A  B  C  D  E  F
   -----------------------------------------------
   0E 22 4F 0F 05 21 06 01 05 01 0F F2 5E BA AA C1    ."O..!.....ò^ºªÁ
   14 AE 86 C1 B4 D8 83 C3 CC 00 00 00 28 28 64 00    .®†Á´ØƒÃÌ...((d.
   01 99 00 00 00 06 00 20 00 00 00 00 00 00 00 00    .™..... ........
   00 00 C7 08 48 79 61 6B 69 6E 74 68 6F 73 00 00    ..Ç.Hyakinthos..
   00 00 00 00                                        ....
   id: 17178885 targid: 261 xpos: -21.340999603271 ypos: -16.834999084473 zpos: -263.69299316406 
   rotation: 242 sizetype: 15 moving: 204 speed: 40 speedsub: 40 
   animation: 0 status: 39169 unk: 153 nameprefix: 32 unk3: 0 
   animationsub: 0 namevis: 0 size:  

instead of 7,129, in mob pool it should be 1,153

**Comment by Fiocitrine** [comment]
thanks gedad! I'll fix the pos.

**Comment by bendangelo** [comment]
Could you squash this? Do you know how?

**Comment by Fiocitrine** [comment]
No sorry. But I can learn! I'm Bottomfeeder on Rizon.

**Comment by Fiocitrine** [comment]
mistake how do I undo this?

**Comment by Fiocitrine** [comment]
hmmm doesn't look like it did anything?

**Comment by xdemolish** [comment]
rebase then squash

**Comment by bendangelo** [comment]
You have a merge commit. You first have to `git rebase origin/development`, then `git rebase -i origin/development`, then force push it

**Pull request closed without merging**
