### PR TITLE
SCRIPTS: Added BLM Potency Merits Checks

### PR DESCRIPTION
**Pull request by Zenny89**
This is my attempt at implementing BLM Potency Merits. Please let me know if I stuck this code in the wrong function or I made any mistakes.

### CODE REVIEW

**Comment by maxtherabbit** [comment]
you don't need to multiply them by 2 in the script - the value of the potency merits is already 2 in the DB so getMerit will return 2xNumberofUpgrades

**Comment by teschnei** [comment]
It might be a bit easier to read if you use an array like the weather etc do

**Comment by Zenny89** [comment]
Updated merit check.

**Comment by maxtherabbit** [comment]
this pull request became a soup sandwich - please make pull requests to the master branch

**Comment by Zenny89** [comment]
I don't even know what happened. I looked at it a little while ago and it was fine!

**Comment by xdemolish** [comment]
dev branch for devs with main repo push access only :D

**Comment by Zenny89** [comment]
So what's the easiest way to fix this mess?

**Comment by Zenny89** [comment]
Didn't mean to close.

**Comment by xdemolish** [comment]
git checkout master
git cherry-pick 3cf46e9

git push fork patch-9 -f

**Pull request closed without merging**
