### PR TITLE
feat(mob_skills): Add skill chain effects to blood pacts

### PR DESCRIPTION
**Pull request by davismj**
I'm using the pre-2016 behavior where skill chain blood pacts do not consume TP. First, there is no reliable data about how TP affects skill chain blood pacts that I could find. Second, it's a better design decision, as it needlessly interferes with the player's ability to save tp for defensive blood pacts.

I used bg-wiki for all skillchain data: https://www.bg-wiki.com/bg/Blood_Pact:_Rage

### CODE REVIEW

**Comment by Wiggo32** [comment]
any reason as to why you're removing the knockback effect from "moonlit charge" ? just curious if that interferes with chains or something...

**Comment by nfaletra** [comment]
Couldn't find anything about knockback for Moonlit Charge. Don't think it's supposed to be there.

**Comment by davismj** [comment]
Yea just fixin someones typo.

**Comment by Wiggo32** [comment]
fenrir certainly does have a knockback affect with moonlit charge.
https://www.youtube.com/watch?v=WcZCtReetpw&feature=youtu.be

**Comment by Hozu** [comment]
Maybe the Prime version of the mobskill has knockback, but the player version doesn't? I figured the player version should have been the one checked.

Timestamp for the knockback in that video is 43:40, btw.

**Comment by zynjec** [comment]
Wiggo can double check for us to confirm, but Hozu seems to be correct.

The prime version has knock back, the player version does not. This video I found very clearly shows no knockback for the player version:
https://youtu.be/9pPiYth8DwE?t=297

**Comment by Wiggo32** [comment]
Yes, you are correct, there is no knockback effect that happens on mobs. Although, even on dsp this knockback setting does NOT produce a knockback effect on mobs. Leaving it on like it is produces a knockback to players when hit from fenrir prime but no knockback when avatar fenrir hits a mob... just as retail does.

**Comment by Wiggo32** [comment]
oh, thought i pasted the vid "at current time" ... lol my bad =)

**Comment by TeoTwawki** [comment]
player/non player versions of things are usually different ID'd duplicates. Do these share ID, and if they do is there a duplicate readily available?

**Comment by davismj** [comment]
Made the changes as per Wiggo's suggestion.

**Pull request merged**
