### PR TITLE
Corrected Several Recipes 

### PR DESCRIPTION
**Pull request by R3P0FFXI**
Added Kapor Lumber, Corrected Shabti Sabatons, Urunday Lumber, Pieste… Mantle

### CODE REVIEW

**Comment by takhlaq** [comment]
`
Importing synth_recipes.sql into the database...ERROR 1062 (23000) at line 3858: Duplicate entry '3706' for key 'PRIMARY'
`

**Comment by R3P0FFXI** [comment]
K Kj sorry Fixed it, also moved 2 Drop IDs due to them being shared between NM and regular mobs, moved the regular mobs to unused DropID's

**Comment by takhlaq** [comment]
looks like you have some unrelated mob changes on the same branch
try again on a new branch based off dsp master and redo the recipe changes (alternatively you could look into cherry picking specific commits to a new branch if you don't feel like manually copying changes)

**Comment by TeoTwawki** [comment]
I split it for him  #3428 and fixed a mistake.

**Pull request merged**
