### PR TITLE
SCRIPTS/SQL: item and npc fix

### PR DESCRIPTION
**Pull request by lichtl**
This pull request will add and correct the missing signet staffs, stats for a Katana and enable the Sacrarium door used in CoP to be opened with the temple knight key item.

### CODE REVIEW

**Comment by xdemolish** [comment]
commit labels please

**Comment by lichtl** [comment]
uhm sorry. Try to fix this or will create a new pull request.

**Comment by bendangelo** [comment]
You can rewrite the commit messages using interactive rebase.

**Comment by lichtl** [comment]
@bendangelo thanks for that information. :)

**Pull request merged**
