### PR TITLE
Scripts: Animsub reset for respawning imps.

### PR DESCRIPTION
**Pull request by Hozu**
Animsubs don't reset automatically so it needs to be reset on spawn so each mob doesn't have permanently broken horns.

### CODE REVIEW

**Comment by bendangelo** [comment]
Shouldn't the animation sub reset for every mob respawning?

**Comment by Hozu** [comment]
Every mob should respawn with a specific subanim, generally 0, yeah. Some mobs don't ever use 0 though - Aerns start in 1.

I take it you're thinking of a better way to do this?

**Comment by nesstea** [comment]
Good test would be that tinnin i just did. ill go check it.

**Comment by Hozu** [comment]
Good point I don't think Tinnin would spawn in 0 - I'm assuming all three heads is 0, though I didn't look at the specific subanims.

**Comment by nesstea** [comment]
All 3 is 0 yes.

**Comment by nesstea** [comment]
Confirmed. Animation sub does not reset on spawn (for any mob it seems). DB for Tinnin is set at 2 and i spawned it a second time with 3 heads.

**Comment by Hozu** [comment]
Yeah they don't reset by default - I made a recent pull that handled the CoP wyrms so they're fine, but if there's a DB value for default subanim and it's not working/being used, uh...

**Comment by bendangelo** [comment]
I saw a line in ai mob dummy which is supposed to reset the animation sub but it was commented out for some reason. I'll look into it later.

**Comment by teschnei** [comment]
It was commented out because it set the animation to some hardcoded number,
if we're thinking of the same thing (ezekyel code for sea mobs)

**Comment by nesstea** [comment]
Anyway, this commit is legit for the imps. Just have to remember to reset the AnimationSub on spawn.

**Comment by Hozu** [comment]
Fix in core makes this no longer required so closing.

**Pull request closed without merging**
