### PR TITLE
Make ponds in Crimson Orb quest give curse instead of plague

### PR DESCRIPTION
**Pull request by Brierre**
Mother of Pearl, the day I get this right on the first try might be the same day I go back to a stone tablet and chisel. 

http://ffxiclopedia.wikia.com/wiki/Whence_Blows_the_Wind, mini quest for Crimson Orb

### CODE REVIEW

**Comment by TeoTwawki** [comment]
Is it 50% on retail? Dang. I guess I forgot how much that sucked if you forget to bring something to remove it. Also are you able to squash?

**Comment by Brierre** [comment]
Can probably squash, I'll do it tomorrow when I get a minute.  I'm the
worst Git person ever so far.  It did suck pretty bad, like the Afflictor.
That part of quest says 10% max hp and 50% max mp.

**Comment by TeoTwawki** [comment]
Eh, ima try githubs new feature that says can squash for you..Cross your fingers.

**Comment by TeoTwawki** [comment]
That worked out ok.. 7b4b683f8c429c1595f28e3d95566b7bce3b2b0f

**Pull request merged**
