### PR TITLE
Repair Maat fight win conditions.

### PR DESCRIPTION
**Pull request by TeoTwawki**
I did BLM Maat just 2 days ago, he gave up **_around_** 20%. We used to have a 10% check in the core, and the only online source I could find says 25% but isn't all that trust worthy, so I'm going with 20% unless someone has solid evidence to the contrary.

I have not tested this. If you want to wait, it may be a few weeks before I get around to doing so. If someone else gives this a shot in the meantime, please comment.

edit: if this doesn't work, I expect Ouryu to also not work right.

### CODE REVIEW

**Comment by TeoTwawki** [comment]
helps if I remember to define the var for the battlefield we are winning, huh? 😊

**Comment by TeoTwawki** [comment]
Amended

**Comment by nyczducky** [comment]
Confirmed working. WHM gives up after 5 and THF steal works.

**Comment by TeoTwawki** [comment]
Thanks!

**Comment by Fiocitrine** [comment]
So weird, both WHM 5 minutes and THF steal method worked over a year ago.

**Comment by TeoTwawki** [comment]
Special win conditions were removed from core and needed redone in script fio.

**Comment by Fiocitrine** [comment]
ah I see

**Pull request merged**
