### PR TITLE
Added Crafting Recipes to DSP Shareback -- From your favorite <====3 :)

### PR DESCRIPTION
**Pull request by R3P0FFXI**
Added Crafting Recipes to DSP Shareback -- From your favorite <====3 :)

### CODE REVIEW

**Comment by bendangelo** [comment]
Could you give a break down of what kind of recipes these are?

**Comment by teschnei** [comment]
looks like a lot of adoulin/rhapsodies recipes, but it's probably more or
less a bunch of stuff they noticed was missing

**Comment by R3P0FFXI** [comment]
@bendangelo its all commented at the end

**Comment by TeoTwawki** [comment]
@R3P0FFXI I found the values for the KeyItems you need for the recipes you have commented out.

KeyItem                |  ID  
---------------------- | -----
Wood Purification      | 1984 
Wood Ensorcellment     | 1985 
Lumberjack             | 1986 
Boltmaker              | 1987 
Metal Ensorcellment    | 1993 
Chainwork              | 1994 
Sheeting               | 1995 
Gold Purification      | 2000 
Gold Ensorcellment     | 2001 
Clockmaking            | 2002 
Cloth Purification     | 2008 
Cloth Ensorcellment    | 2009 
Spinning               | 2010 
Fletching              | 2011 
Leather Purification   | 2016 
Leather Ensorcellment  | 2017 
Tanning         j      | 2018 
Bone Purification      | 2024 
Bone Ensorcellment     | 2025 
Filing                 | 2026 
Anima Synthesis        | 2032 
Alchemic Purification  | 2033 
Alchemic Ensorcellment | 2034 
Trituration            | 2035 
Concoction             | 2036 
Iatrochemistry         | 2037 
Raw Fish Handling      | 2040 
Noodle Kneading        | 2041 
Patissier              | 2042 
Stewpot Mastery        | 2043

**Comment by R3P0FFXI** [comment]
@TeoTwawki I will go ahead and fix the ones missing the KI with your info thanks man

**Comment by R3P0FFXI** [comment]
KI are in @TeoTwawki

**Comment by bendangelo** [comment]
thanks for contributing

**Pull request merged**
