### PR TITLE
Added logic to define the log file via command line parameter.  Fixed #1...

### PR DESCRIPTION
**Pull request by joncloud**
...296.

### CODE REVIEW

**Comment by maxtherabbit** [comment]
2 issues with this:

1) if you do not #define DEBUGLOGwhatever (it's not defined for search by default) you get a crash on your call to InitializeLog() using an undefined pointer

2) need to move the InitializeLog calls for map and login into main function in kernel.cpp otherwise it does not log the first couple console messages and trips "log_file not defined" warnings

**Comment by teschnei** [comment]
i think it's easier to just name the file based on the passed IP and port rather than specifying one (saves a lot of work, etc)

**Comment by maxtherabbit** [comment]
don't really think that would save much work

you'd still have to set things up the same way, just using different args

**Comment by teschnei** [comment]
i'd make that the default then instead of a warning

**Pull request merged**
