### PR TITLE
Unset day of the week bonus/penalty for crafting.

### PR DESCRIPTION
**Pull request by Hozu**
Confirmation from the FFXI AMA: https://www.reddit.com/r/ffxi/comments/4ulgh1/official_ffxi_developer_ama_with_producer_akihiko/d5qp5k5

tl;dr http://i.imgur.com/0lupEyc.png

### CODE REVIEW

**Comment by TeoTwawki** [comment]
I'm smiling so hard right now my face might break.

**Comment by HeavensSword** [comment]
My life is a lie.

**Comment by TeoTwawki** [comment]
> My life is a lie.

-_shatters into pieces, the pieces themselves landing in a way that you can still see me smiling ear to ear._-

**Comment by Deadwing888** [comment]
Hahahaha, this is fantastic, really?

**Comment by TeoTwawki** [comment]
@Deadwing888 yes at first teh translator tried to say the reply from dev was "no comment" and a bilingual person called them on it and then the translator said it was a "mistranslated" and put the real answer up and so now SE has officially admitted all the myths are BS.

**Comment by Deadwing888** [comment]
Yes I stopped reading when they said no comment and would never have revisited. 

I'm editing one of my crafting issues now with the new info. I said dsp was handling day/moon/direction as much too big factors and that the skills they were affecting was complete bogus but I maintained in the issue that I thought they did ever so slightly affect HQ rate. I really thought they did... by plus or minus ten percent or so for something like day.

**Comment by Deadwing888** [comment]
https://github.com/DarkstarProject/darkstar/issues/2440

Looking okay? Lots of the issues listed here are still live if someone wants to take a swing at them.

**Pull request merged**
