### PR TITLE
Update to Simurgh.lua to allow NM to Spawn

### PR DESCRIPTION
**Pull request by pandorraffxi**
Updated /scripts/zones/Rolanberry_Fields/mobs/Simurgh.lua

Changed line 38 from:
UpdateNMSpawnPoint(mob:getID());
To:
UpdateNMSpawnPoint(Simurgh));

Signed-off-by: pandorraffxi <rahulabon@hotmail.com>

### CODE REVIEW

**Comment by takhlaq** [comment]
this doesnt do anything besides error out preventing setting the 21-24h respawn time

**Comment by Wiggo32** [comment]
You could make him 'rage' too! =)

**Comment by pandorraffxi** [comment]
Ahh I see it now, should be added to MobIDs.lua instead of editing the simurgh.lua...sorry!

**Comment by TeoTwawki** [comment]
no point in being in mobids even - its his own id doesnt need to pass through there

**Comment by TeoTwawki** [comment]
also not seeing any spawn problem tested by setting respawn time very low.

**Comment by wrenffxi** [comment]
Quick explanation on this one: Pandorra's on my server, and we have some custom code that preserves certain NM pop cooldowns through server resets.  It's not retail accurate, so I assume ya'll don't want it.  If you do, let me know.  Anyway, we broke, and later fixed, our code recently.  Pandorra didn't realize it was our issue rather than DSP's.  AFAIK your Simurgh works as expected.

**Comment by TeoTwawki** [comment]
Ah ok. I did something similar for another servers ground kings.

**Pull request closed without merging**
