### PR TITLE
Item Mods Again...

### PR DESCRIPTION
**Pull request by Ninjistix**
@takhlaq

### CODE REVIEW

**Comment by takhlaq** [comment]
```
Importing item_mods.sql into the database...ERROR 1064 (42000) at line 24769: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '+
INSERT INTO `item_mods` VALUES (25758,1,1)' at line 1
```

**Comment by Ninjistix** [comment]
my bad was copying over some stuff from mac to windows.. it added a + to a commented line...

**Comment by Ninjistix** [comment]
@takhlaq

**Comment by takhlaq** [comment]
we get notifications on each push, though it looks like you haven't fixed gelai earrings yet

**Comment by Ninjistix** [comment]
fixed the item_mod_pet

**Comment by takhlaq** [comment]
why did you close? if we dont want it we'll close it ourselves
was still part way through checking the items..

**Comment by Ninjistix** [comment]
I'll let someone else take care of it, info's there.

**Comment by TeoTwawki** [comment]
yeah that won't happen.

**Pull request closed without merging**
