### PR TITLE
Added missing lines for Somnolence damage

### PR DESCRIPTION
**Pull request by Whitechaser**
Fix for #4223

### CODE REVIEW

**Comment by TeoTwawki** [comment]
@takhlaq @Whitechaser 
https://github.com/DarkstarProject/darkstar/blob/157cb9a619ece8dd4c9530c75794183709b5c26b/scripts/globals/magic.lua#L648
```
target:delHP(dmg);
```
That looks like finalMagicAdjustments already removes HP there and updates enmity to lines below it.

**Comment by Whitechaser** [comment]
Oh! You're right! You'll have to revert this, so sorry.

The issue persists then. Somnolence isn't doing damage to mobs.

I found something just now though. You don't suppose it could be https://github.com/DarkstarProject/darkstar/blob/5078b8b1b71c30af4a5fbcb9075787e5a9a3cd3f/scripts/globals/abilities/pets/somnolence.lua#L17 not having a semicolon at then end, do you?

**Comment by TeoTwawki** [comment]
semicolons are fully ignored in lua lamguage. my bet is on something breaking the script before it gets to the the dmg so it never execs that line or the dmg calc itself getting screwed

**Comment by Whitechaser** [comment]
I'll try following the damage calc then. Hopefully I can find where it's going wrong.

**Pull request merged**
