### PR TITLE
Scripts: Correct mods on Expiacion and Tachi: Rana

### PR DESCRIPTION
**Pull request by Hozu**
https://www.bg-wiki.com/index.php?title=Expiacion&oldid=269807
https://www.bg-wiki.com/index.php?title=Tachi:_Rana&oldid=270583

Also fixed two broken Katana WSs.

### CODE REVIEW

**Comment by helixhamin** [comment]
Have you confirmed which is correct, bg or ffxiclopedia?
http://ffxiclopedia.wikia.com/wiki/Tachi%3A_Rana

They both give different STR mod values, so ffxiclopedia values were probably used.

**Comment by teschnei** [comment]
bgi-wiki is the correct choice for pretty much everything nowadays - especially since the big WS changes last year

**Comment by helixhamin** [comment]
Okay, got it. And looking through, I see some of the material referenced in the ffxiclopedia that goes over how they estimated at 35%.
Odd to think that it is outdated now. I used to use it for everything...

**Comment by Hozu** [comment]
Check out the older version of the Tachi: Rana page - http://ffxiclopedia.wikia.com/wiki/Tachi:_Rana?oldid=1388363 35% there too.

**Pull request merged**
