### PR TITLE
Create unique poolid for Seaboard Vulture

### PR DESCRIPTION
**Pull request by ValentineXI**
Addresses issue #5808. Also added Tragopan dropid to Seaboard Vulture group as shares similar pool (bird feather and bird egg).

Bonus content: deleted that annoying blank line in `mob_pools.sql` that's been driving me nuts.

### CODE REVIEW

**Comment by TeoTwawki** [comment]
Hi, it looks like you used git hubs lousy  site or software to make 3 commits, possibly via the file upload. We discourage that but if you do, be sure to edit the commit messages to something actually descriptive in the future. Thanks!


IMG_2766

**Comment by TeoTwawki** [comment]
jus gonna leave these here :wink: 

https://gitforwindows.org/

https://tortoisegit.org/download/

**Comment by ValentineXI** [comment]
Sorry Teo, thanks for the info! Yes I just used the website lol, I thought I'd do this one in the meantine while cloning the repo locally didn't realize it was bad D:

**Comment by TeoTwawki** [comment]
lol. we discourage it because of the tendency to get commit messages that say "update thing". You're ok though I squashed them into one which let me change the commit message to what you had as your description above.

**Pull request merged**
