### PR TITLE
bcnm (amphibian assault)

### PR DESCRIPTION
**Pull request by RoahZoe**
new bcnm amphibian assualt and mob.lua along with mobid.lua for the zone/bcnm

### CODE REVIEW

**Comment by RoahZoe** [comment]
also added commits for treasure chests and their loot for amphibian assault

**Comment by RoahZoe** [comment]
removed some other bcnm info unintended to merge into master

**Comment by xdemolish** [comment]
see comments https://github.com/DarkstarProject/darkstar/pull/3212

**Comment by RoahZoe** [comment]
thanks ill close this and take the advice and do a normal git push

**Pull request closed without merging**
