### PR TITLE
SMN Pet bodyguard fix, Pets respawn in valid zone, pets despawn on chocobo mount and respawn on dismount

### PR DESCRIPTION
**Pull request by thedraked**
Fix for SMN Pet behavior to act as a bodyguard, attacking anything that aggros/has hate on Master or that Master attacks provided pet has no battle target.  

SMN pets will now respawn after zoning.  

Pets will despawn on chocobo mounting.  

I dont know if this is retail behavior but I also made them respawn on chocobo dismount.  

Known issue:  The automatic chocobo dismount on zone (when zoning into an area chcobo's are not allowed) will not respawn pet

### CODE REVIEW

**Comment by R3P0FFXI** [comment]
@thedraked there is a retail free period right now I would check this on retail right now im pretty positive what you just committed is not retail behavior at least via description.

**Comment by teschnei** [comment]
"I dont know if this is retail behavior but I also made them respawn on chocobo dismount."

I can't merge this until you either figure out that it's retail or figure out it's not and remove it

**Comment by teschnei** [comment]
also, you need to be using 4 spaces instead of tabs

**Comment by thedraked** [comment]
what does that mean?  "4 spaces instead of tabs"

**Comment by teschnei** [comment]
what are you editing files with?

**Comment by thedraked** [comment]
Visual Studio

**Comment by teschnei** [comment]
tools ->options -> text editor -> all languages (or c++) -> tabs -> set tab size and indent size to 4, select insert spaces

**Comment by thedraked** [comment]
Ok, gonna close and redo commit just what I know to be retail.  and make that change.

**Pull request closed without merging**
