### PR TITLE
Scripts/SQL: Fix broken GoV pages

### PR DESCRIPTION
**Pull request by Hozu**
General
-Add GoV require to mobs that had it missing
-Move the scripts for mobs that are supposed to be in Maze of Shakhrami there, from Crawler's Nest.

Ranguemont Pass
-Page 3: Add exp amount
-Page 7: Add array for mob amount

Bostaunieux Oubliette
-Page 5: Add exp amount

Toraimorai Canal
-Script mobs for all 8 pages

Dangruf Wadi
-Page 2: Add high level Goblins (Goblin family)

Inner Horutoto Ruins
-Page 7: Correct Skinnymajinx to Skinnymalinks

Ordelles Caves
-Page 4: Made Vorpal Bunnies count properly instead of as Seeker Bats

Outer Horutoto Ruins
-Page 5: Made Eight of Coins count properly instead of as Eight of Swords

The Eldieme Necropolis
-Update Grounds Tome script to have the correct offerings (page 7 was replaced by page 8, and 8 was replaced by Gusgen Mines page 1)
-Page 1/5: Add Hellbound Warrior/Sorcerer

Gusgen Mines
-Page 1/2: Added the high level skeletons to the skeleton family requirement
-Page 3: Made Bandersnatch count properly instead of for page 2

Crawler's Nest/Maze of Shakhrmai
-Update Grounds Tome script to have the correct offerings (page 2 was replaced by the one after it, causing them all to be shifted back one, with page 8 being from Maze of Shakhrami)

Garlaige Citadel
-Page 1: Add reward amount and Fallen Soldier (skeleton family)
-Update Grounds Tome script to have the correct offerings (page 7 was acting as another page 6)

The Boyahda Tree
-Page 2: Made Robber Crab count properly instead of for page 1

Ve'Lugannon Palace
-Page 1: Add Mystic Weapon and Ornamental Weapon

The Shrine of Ru'Avitau
-Page 2: Correct EXP amount

Ifrit's Cauldron
-Page 1/7: Add array for mob amount
-Page 6: Correct EXP amount
-Page 8: Correct script name for Hurricane Wyvern

Gustav Tunnel
-Page 2/3: Add Goblinsavior Heronox and Wyvernpoacher Drachlox (Goblin family)

Lower Delkfutt's Tower
-Page 1: Add array for mob amount, add EXP amount

Middle Delkfutt's Tower
-Page 1: Add array for mob amount, add EXP amount

Upper Delkfutt's Tower
-Page 2/4: Add array for mob amount, add EXP amount

Den of Rancor
-Page 2: Add array for mob amount, correct Mousse script name
-Page 5: Change EXP amount from one guess to a more "accurate" guess
-Page 6: Add Doom Toad amount to the mob array, correct name of Demonic Pugil in mob_spawn_points.sql, correct level of Demonic Pugil in mob_groups.sql

Sea Serpent Grotto
-Page 4: Correct array for mob amount (client has only two things, not 3).

### CODE REVIEW

**Comment by Hozu** [comment]
Note: POLutils confirms there's no "Stygian Pugil" in Den of Rancor.

**Comment by helixhamin** [comment]
@Hozu 
I have actually noted the Fei'Yin missing Northern Shadow here: https://forums.dspt.info/viewtopic.php?f=20&t=2969

**Comment by Hozu** [comment]
I'm removing the NMs I added since apparently they don't count for generic family/class pages.

**Comment by helixhamin** [comment]
Hmm, both ffxicyclopedia and bg-wiki shows there is Stygian Pugil spawns in Den of Rancor.

**Comment by Hozu** [comment]
The client specifically asks for "Demonic Pugil" for page 6, and POLutils has no entries for "Stygian Pugil" in the entire zone of Den of Rancor - only "Demonic Pugil".

**Pull request merged**
