### PR TITLE
Player death message fix

### PR DESCRIPTION
**Pull request by jmcmorris**
This fixes the issue where a player can be sent the wrong death message. It currently uses the target but if the player is not currently targeting the monster that kills them then it will either say that the wrong monster killed them or "falls to the ground".

The fix here is to track which entity was the last one to deal damage to the character and clear it whenever the player takes neutral damage such as from poison.

One thing I'm not crazy about is how the magic case is handled. Magic from monsters deal damage by calling `CLuaBaseEntity::delHP()` but that does not pass in the attacker and is called by hundreds of scripts. It would be somewhat trival to do it for monster scripts but would greatly bloat this PR and have a much higher chance for conflicts. I'm open to whatever.

Tested this by dying to melee attack, magic attack, spikes and poison. All but the last now show "defeated by" message and the last shows "falls to the ground".

Thanks to @Wiggo32 for helping get the correct death spikes message.

### CODE REVIEW

**Comment by TeoTwawki** [comment]
> by calling CLuaBaseEntity::delHP() but that does not pass in the attacker and is called by hundreds of scripts.

At some future point I think we'll have to make a function to put taking damage into so that we aren't directly calling delHP like that

**Comment by jmcmorris** [comment]
I can make that change if you'd like but it is going to touch nearly 700 files - most of which are in mobskills. Not entirely sure it fits within the scope of this PR but I see it going either way.

**Comment by teschnei** [comment]
okay, it looks pretty good, but.. why's `PLastAttacker` in CCharEntity only? don't we want that in all battle entities anyways?

**Comment by jmcmorris** [comment]
I originally had it in CBattleEntity but since I was only using it in CCharEntity I decided to keep it in there. I can always revert that change if you think it will be useful for CBattleEntity.

**Comment by teschnei** [comment]
yeah? mobs do the same thing (falls to the ground vs defeated by x), don't they?

**Comment by jmcmorris** [comment]
You're right that mobs need to be fixed at least a little bit. Right now if a mob dies with no target (player died but mob was poisoned) then it does not display any message. This should definitely say "falls to the ground".

What happens in retail if a mob dies from poison but does have a target? Should it say "falls to the ground" or "defeated by"?

**Comment by jmcmorris** [comment]
@wiggo32 was kind enough to test this on retail. It is "falls to the ground". I will update the code.

**Comment by teschnei** [comment]
It is falls to the ground, yes. It's also falls to the ground for any
script that sets HP to 0, such as chlevnik and chigoes

**Comment by teschnei** [comment]
one last thing - setHP should clear LastAttacker.  The situations I described earlier (chelvnik and chigoes) would (or are, I forget) use setHP to "kill" them

**Comment by jmcmorris** [comment]
Haha yup, I was just reviewing things and remembered that. Testing out my fix now. :)

**Comment by jmcmorris** [comment]
@teschnei Thanks for pushing on this and helping get it to a good state - same for my other PRs

**Pull request merged**
