### PR TITLE
SQL npc_list Update HELM Point Names

### PR DESCRIPTION
**Pull request by Cryptexx**
Fixed a few typos in Mining_Point, Logging_Point, etc names. Standardized format to Proper Case.

### CODE REVIEW

**Comment by TeoTwawki** [comment]
image

???line ends maybe???

**Comment by TeoTwawki** [comment]
why close

**Comment by Cryptexx** [comment]
I thought it was jacked up? Got rolled in with my other commit too. I'll reopen if it's fine..

**Comment by Cryptexx** [comment]
It was jacked up somehow, not sure how to fix at this point.

**Pull request closed without merging**
