### PR TITLE
Version Update Dec2017/NpcID Shifts & Lua Stable Branch

### PR DESCRIPTION
**Pull request by dragonarmor**
Requested by Teo, Here ya go

### CODE REVIEW

**Comment by TeoTwawki** [comment]
ruh oh. that looks like it pulled in other commits.

**Comment by dragonarmor** [comment]
That's odd?? How did that happen?

**Comment by TeoTwawki** [comment]
rebase gone wrong?

**Comment by dragonarmor** [comment]
Closing this to resolve comments

**Pull request closed without merging**
