### PR TITLE
CORE, SCRIPTS, DATABASE/SQL:Sharpshot

### PR DESCRIPTION
**Pull request by Joeyjohjjo**
Created MOD_SHARPSHOT for equipment with "Enhances Sharpshot effect." It increases the Ranged Accuracy that Sharpshot bestows. Added the mod to Hunter's Braccae and its +1. Reorganized the Sharpshot effect page. Added MOD_SHARPSHOT functionality to the ability page. Fixed Sharpshot's base RAcc from 20 to 40 (thanks dazusu for research).

### CODE REVIEW

**Comment by xdemolish** [comment]
use commit labels please (see https://github.com/DarkstarProject/darkstar/blob/master/README.md)

also, rebase and squash your commits into one
squash/rebase > amend last commit > change commit message to include labels > force push

**Comment by Joeyjohjjo** [comment]
Commits be squashed.

It says I changed more lines than I really did. The scripts/globals/status.lua change is line 1015:
https://github.com/Joeyjohjjo/Johjjodarkfork/blob/c40be2fea24e74284b402cbff3647a6d295c2200/scripts/globals/status.lua#L1015

The sql/item_mods.sql are to items 14224 and 15571.

**Comment by teschnei** [comment]
why did you close this?

**Comment by Joeyjohjjo** [comment]
Demo couldn't merge it due to merge conflicts. I'm trying to redo it.

**Comment by teschnei** [comment]
ah, i already copied your stuff and commit it because I thought you rage quit without saying anything (i didn't see anything in irc either)

**Comment by Joeyjohjjo** [comment]
That's fine. Thank you.

Git is hard. ;_;

**Pull request closed without merging**
