### PR TITLE
Chlevnik additions

### PR DESCRIPTION
**Pull request by CTOON50**
Added spell list that contains Meteor, and added BLM as subjob for Chlevnik to give MP to cast.

### CODE REVIEW

**Comment by TeoTwawki** [comment]
You can get away with re-using King Behemoths spell list without creating a new one, sicn ethey are identical. The list ID is 126 and contains only Meteor.

**Comment by CTOON50** [comment]
Completely overlooked that...should have remembered as I just messed around with KB not too long prior.

**Comment by TeoTwawki** [comment]
p.s. I wouldn't mind if you changed that spell lists name field to say something like "Casting_Behemoths" or something else accurately descriptive since its not just KB anymore. Up to you, not required.

(the name field there is unused by anything in the code and is just there for at a glance identification by us fleshy meat puppets)

**Comment by CTOON50** [comment]
There we go, though somehow an extra line was added to the spell list

**Comment by TeoTwawki** [comment]
eh that's ok

**Pull request merged**
