### PR TITLE
mob:getPool() is now a thing

### PR DESCRIPTION
**Pull request by TeoTwawki**
Also converted over the static mobID checks in smobskill scripts to check either the skill list ID or the pool ID...And I ran them through my auto format thing >.>

Source changes in first (and third) commit , script changes in second commit. Everything after that is because you sat on it to long :stuck_out_tongue:

### CODE REVIEW

**Comment by TeoTwawki** [comment]
Sorry, have warnings off since there are so many of them already. Fixing.

**Comment by teschnei** [comment]
visual studio will usually only warn once until that line is changed

**Comment by teschnei** [comment]
however I'd like to go get rid of them all some time :)

**Comment by TeoTwawki** [comment]
I had my return in the wrong line. I didn't go far with testing.

**Comment by TeoTwawki** [comment]
-*nudge*-

**Comment by TeoTwawki** [comment]
Fixed conflicts

**Pull request merged**
