### PR TITLE
Bastok 8 2

### PR DESCRIPTION
**Pull request by Turttle**
Drake Fang  cleanup and Bastok 8-2 mission patch.

### CODE REVIEW

**Comment by Turttle** [comment]
I think something is off, is event "0x00ca" supposed to be for 6-1 and 8-2?

**Comment by gedads** [comment]
check the last file if you want to clean it , ca cb cc are for 8-2 c8 c9 for 6-2

**Comment by Turttle** [comment]
thx!!

**Comment by Turttle** [comment]
#1265

**Pull request closed without merging**
