### PR TITLE
SCRIPTS: Updated Empress Band

### PR DESCRIPTION
**Pull request by Zenny89**
Made changes according to http://ffxiclopedia.wikia.com/wiki/Empress_Band

### CODE REVIEW

**Comment by TeoTwawki** [comment]
Don't go by the nearly dead wiki, go by what yoru client says in game.
http://www.ffxiah.com/item/15762/empress-band
https://www.bg-wiki.com/index.php/Empress_Band
These sources don't agree with ffxiclopedia.

**Comment by TeoTwawki** [comment]
Screenshot from client.
Image of empress band in client

**Comment by TeoTwawki** [comment]
Screenshot from client.
Image of empress band in client

**Comment by TeoTwawki** [comment]
Looks like we can't trust either wiki to have up to date item data for all items.

**Comment by Zenny89** [comment]
Updated based on UI.

**Pull request merged**
