### PR TITLE
Aggro detection changes on some families

### PR DESCRIPTION
**Pull request by Brierre**
Pugils detect by sound, not sight
Imps detect true sight
Treants detect sound
Flan detect sight and job ability
Lizards detect sound

### CODE REVIEW

**Comment by takhlaq** [comment]
recommit with descriptive commit message please

**Comment by Brierre** [comment]
Hopefully that's what you wanted.

**Comment by TeoTwawki** [comment]
Should have force pushed to same branch so the pull request would update, rather than create a 2nd pull request for the same thing.

**Comment by Brierre** [comment]
Sorry, I don't know how to do any of that yet.  I'm lucky I got this far...

**Comment by TeoTwawki** [comment]
well, for next time:

depending on what you use, there's several easy ways to learn stuff.

If you are a command lien person, can just say `git push --help` and it'll direct you to all the wonderful things it can do.

tortoisegit has its help on a right click menu option.

github has help pages describing most actions you could want to know how to do.

and if you ask here, 99.100 times someone will help out fairly quickly. :)

**Comment by Brierre** [comment]
Thanks, I'll ask next time.  I did this all online with the edit button.  I'm not sure how that fits into what you described.

**Comment by TeoTwawki** [comment]
Ah yeah, we avoid letting the website do edits. only slightly better than using githubs desktop app (both are pretty icky compared to other options)

**Comment by takhlaq** [comment]
https://github.com/DarkstarProject/darkstar/issues/3539

**Pull request closed without merging**
