### PR TITLE
sql/item_mods.sql

### PR DESCRIPTION
**Pull request by bn7**
Added some missing Mods

### CODE REVIEW

**Comment by TeoTwawki** [comment]
2 things: 
* This is more than some, its enough changed in a single commit that github can't display the changes. So you'd have to  look at the diff locally like I just did. Huge pita.
* Since there is no commenting, anyone reviewing the changes would have to look up when item the item ID each one is and then what modifiers those mod IDs are being applied.

Could you possibly make this a little easier on us?

**Comment by bn7** [comment]
Sorry the system just took the whole list. Is their a command/way to make it as several? instead of one?

**Comment by TeoTwawki** [comment]
You'd have to make commits as you make changes, instead of after all changes are finished. 

It is possible to roll back the history, but backup the file first if you are going to. I'd hate to see you lose any of your work!

**Comment by xdemolish** [comment]
pull to a new branch, change 100 lines of code at most, commit and push to your fork
then pull request and wait til we review before making a new one

**Pull request closed without merging**
