### PR TITLE
removed non player spells from the list

### PR DESCRIPTION
**Pull request by Ninjistix**
- http://pastebin.com/raw/BsfQxhzY (master spell list for all jobs)
- separated spells currently disabled in spell_list.sql
- http://pastebin.com/raw/fkZwEwkW (current spells missing from spell_list.sql)

### CODE REVIEW

**Comment by takhlaq** [comment]
mmm if the spells removed were just the ones with blank names then yeah, but i don't really see the need to remove mob spells if they can be used for testing

**Comment by Ninjistix** [comment]
would it be better to split the cmds? into something like @addplayerspells or something

**Comment by TeoTwawki** [comment]
I have a compromise suggestion: leave it split like you have it, but default uncommented. servers that don't want addallspells to mean ALL spells can just comment those lines

**Comment by TeoTwawki** [comment]
easier than picking out the spell IDs in the table

**Comment by Ninjistix** [comment]
actually the ones that i have commented out are actually commented out from the current spell_list, but there's a set of spells that are missing form the list too, in that second pastbin, has the names/jobs

**Comment by Ninjistix** [comment]
if anything i can split the lines between players and mobs, to make it easier for servers to disable mob spells...

**Comment by TeoTwawki** [comment]
> if anything i can split the lines between players and mobs, to make it easier for servers to disable mob spells...

sounds fine to me.

As for missing, those do no harm and work once someone actually implements them. Command was rework awhile back with something about that along with making it not spam packets, iirc.

**Comment by ibm2431** [comment]
What about a flag when calling the command? Like `@addallspells player_only` or `@addallspells include_mob_spells`.

**Pull request closed without merging**
