### PR TITLE
Be able to fish more items

### PR DESCRIPTION
**Pull request by nuno-pires-cruz**
When FishingChance <= 20, you could only get quested items. With this change, you're now able to get the other possible items.

### CODE REVIEW

**Comment by TeoTwawki** [comment]
ignore me, browser error

**Comment by TeoTwawki** [comment]
but below were still comparing zero to another number and expecting it to be equal or less?
```cpp
 			int32 FisherLuck = 0;
             int32 FishingChance = dsprand::GetRandomNumber(1000);
 
 			while(Sql_NextRow(SqlHandle) == SQL_SUCCESS) 
 			{
 				FisherLuck += Sql_GetIntData(SqlHandle,7);
 
				if (FishingChance <= FisherLuck)
```

**Comment by nuno-pires-cruz** [comment]
Hi,

In that part of the code, `FisherLuck` is always different from zero. Because he ads 0 + the value from table record ( witch is always > 0 , because of the sql statement "`AND lure.luck != 0`").

That part of the code, is still the original. If you remove that random and the verification, it would mean that the player would always catch something.

**Comment by TeoTwawki** [comment]
ooooh I didn't see the += adding the sql row's value to it, my bad

**Pull request merged**
