### PR TITLE
Create job_points

### PR DESCRIPTION
**Pull request by some1here**
add

### CODE REVIEW

**Comment by TeoTwawki** [comment]
is no sense is like revolve door? or is like water wheel in hurricane. my sanity break. if is shoot and am 20dmg not 2000 dmg then am suicide fail. 

**Neuga Zeina Zieber Zom...**

**Comment by nesstea** [comment]
Are you trolling or something? You keep opening and closing PRs...

**Comment by some1here** [comment]
No this program does not let me submit.....

**Comment by nesstea** [comment]
use git and tortise git...

**Pull request closed without merging**
