### PR TITLE
Initial Homeserver

### PR DESCRIPTION
**Pull request by ENKIDUtheWILD**

### CODE REVIEW

**Comment by ENKIDUtheWILD** [comment]
Mistake. Sorry. ><

**Comment by TeoTwawki** [comment]
Generally one forks from darkstar master, not fork a fork. If you are going to copy someone else s entire server (I see code I customized for the LegionDS server) I hope you are talking to them and being friendly, and not intending to split their server population or anything that starts drama. I certainly don't mind see things I do get used (sharing is caring, I try to share even my custom stuff from Annwn server) but others might be upset at using a full 1:1 copy for anything other than solo'ing at home.

And if anyone is flipping out, I hope it occurs to them sooner rather than later that open source is about being open, not controlling who has access to what.

**Comment by teschnei** [comment]
if you put legion on a public github account, anyone is allowed to fork it
without you knowing

**Comment by TeoTwawki** [comment]
Told them that

**Pull request closed without merging**
