### PR TITLE
Fix jump/highjump landing for zero dmg

### PR DESCRIPTION
**Pull request by TeoTwawki**

### CODE REVIEW

**Comment by teschnei** [comment]
Do the other fake weapon skills need fixing too? Shield bash, weapon bash,
blade bash, etc

**Comment by TeoTwawki** [comment]
hadn't even thought of it. I'll go check. brb

**Comment by TeoTwawki** [comment]
nope the "bash" moves are ok as is. They don't go through that function.

**Comment by ibm2431** [comment]
Did a [search for atkmulti](https://github.com/DarkstarProject/darkstar/search?p=2&q=params.atkmulti&unscoped_q=params.atkmulti).

How's [Eagle Eye Shot](https://github.com/DarkstarProject/darkstar/blob/08f7115f028376eb4db577c465fc9cfc89abdeb7/scripts/globals/abilities/eagle_eye_shot.lua#L42) and [Violent Flourish](https://github.com/DarkstarProject/darkstar/blob/58539ad5a2c612b0041135b2349d99824a51e1b6/scripts/globals/abilities/violent_flourish.lua#L51)? From what I can tell, Flourish doesn't look like a fake WS itself, but it is [going through cMeleeRatio](https://github.com/DarkstarProject/darkstar/blob/58539ad5a2c612b0041135b2349d99824a51e1b6/scripts/globals/abilities/violent_flourish.lua#L64), which had [similar atkmulti changes](https://github.com/davismj/darkstar/blob/0ec5a8beb546bdff7b590bd045fac9cb985f5f6d/scripts/globals/weaponskills.lua#L499).

**Comment by TeoTwawki** [comment]
@ibm2431 I'll check'em after work tonight

**Comment by TeoTwawki** [comment]
pet abilities might need it as well

**Pull request merged**
