### PR TITLE
Scripts/SQL: Jailer of Hope

### PR DESCRIPTION
**Pull request by Hozu**
Enabled the ability to spawn it via trade.
Gave it the ability to cast Burst II and Thundaga III instantly for up to a minute after using Plasma Charge.
Bumped up Phuabo movespeed to 70 as they are supposed to have enhanced movement speed.

### CODE REVIEW

**Comment by Hozu** [comment]
Fixed this conflict.

**Comment by Scavenge** [comment]
Does it allow instant cast only from the time it first uses it, or does it refresh the timer while spikes are active? Seems this method could cause it to lose instant cast even if it still has spikes or reuses the move.

**Comment by Hozu** [comment]
Every time Plasma Charge is used, it sets the one var to current server time + 60. The effect is supposed to remain even if spikes gets removed, which is why I wrote it the way I did. If it uses Plasma Charge while it's already able to cast spells, it just resets it to 60 seconds again.

Whenever the 60 seconds has passed, the spelllist gets set to an empty one and the var is set to 0 so it doesn't keep setting the list repeatedly (I think onMobFight happens every second or something).

**Comment by Turttle** [comment]
onMobFight is called every 3 seconds

**Comment by teschnei** [comment]
onMobFight has been every second for a long time... probably over a year

**Pull request merged**
