### PR TITLE
@commands

### PR DESCRIPTION
**Pull request by helixhamin**
Added some of Tagban's @ commands for more @ options and to test gitpull

### CODE REVIEW

**Comment by TeoTwawki** [comment]
If the preceding comments I made look out of context go to the individual commits pages. 
I can't speak for the devs but nearly all of this of this looks like the sort of custom stuff they don't want in trunk. I could see the [at]ah making it in if cmdprops are cleaned up. Actually intended to include my own ver of that in my next batch.

**Comment by tagban** [comment]
Lol I actually replaced my @chocobo command with that as well. The truth is, most custom commands aren't retail based so they likely won't be added to the main repo. (Mainly why I never submitted them). I am planning on adding my custom colors and stuff shortly, just cleaning up a few more things and haven't had time for a few days to work on it.

**Comment by tagban** [comment]
As for shops, I agree with Teo, and thats why I've been slowly working on modding mine as well, will post all results in scripts section on forums once done though. As promised, since I cannot contribute much to C++, I can at least share everything I CAN contribute. :)

**Comment by helixhamin** [comment]
Pull request closed. Bad coding, but at least I was able to figure out how to properly submit changes to github to help on the project.

**Pull request closed without merging**
