### PR TITLE
assuming this fixes #4032

### LINKED ISSUE #4032: Lamie No.9 Not coded as a NM
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30170728_2

**_Server Version_** (type `!revision` in game) **:** Unknown

**_Source Branch_** (master/stable) **:** Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** Lamie No.9 @ (J-6) on Map Three in Arrapago Reef is coded as a Very Tough normal mob with no loot pool other than standard Lamie pool. Should be a Notorious Monster.

Sauce: http://ffxiclopedia.wikia.com/wiki/Lamie_No.9

### PR DESCRIPTION
**Pull request by Ninjistix**
let me know if i missed anything or did anything wrong, assuming this fixes #4032

### CODE REVIEW

**Comment by TeoTwawki** [comment]
Need to set the mob type to notorious which is in mob_pools.sql none of this other stuff relates to the `/check` being wrong. So one more line needed.

**Comment by Ninjistix** [comment]
Will modify it when I get home

**Comment by Ninjistix** [comment]
I also am assuming that is the right position for that value, assuming that I didn't count wrong lol...

**Comment by TeoTwawki** [comment]
btw nm_spawn_points only gets used if the NM's script calls the function to grab a new spawn point. Any NM that can pop at many diff pos would need that script command and the diff pos's added to the table. This one doesn't even have a script yet so that table entry you added for it won't be used until she does.

**Comment by Ninjistix** [comment]
thanks for the heads up

**Pull request merged**
