### PR TITLE
SCRIPTS: Tateeya fix

### PR DESCRIPTION
**Pull request by Zenny89**

### CODE REVIEW

**Comment by teschnei** [comment]
i highly doubt that fixes it - i'm 99% sure if i named it subid I wanted the subid

**Comment by Zenny89** [comment]
I traded her a few attachments and she converted them all, and I was able to equip them all to the automaton.

**Comment by teschnei** [comment]
Yes, but where did you get the attachments? If you used additem, you
probably added the wrong one (there are two itemids for every attachment,
only one is auction housable). The auction house one uses subid to point to
the real one

**Comment by Zenny89** [comment]
Yes, I used additem: For Attuner, I used the ID found here: http://www.ffxiah.com/item/8453/attuner so 8543. Where can I find the correct one?

**Comment by teschnei** [comment]
Search it on ffxiah. One of them will be stackable, I think it's that one

**Comment by Zenny89** [comment]
Got it - closing this pull request and will check to see if this NPC works with the existing code later.

**Pull request closed without merging**
