### PR TITLE
ENM Brothers added

### PR DESCRIPTION
**Pull request by Fiocitrine**
Added:

Mobs
Droplist
Spell list
Condition to win 
Functionailty to the NPCs to obtain items for the ENM

### CODE REVIEW

**Comment by Hozu** [comment]
You really need to do a rebase, there's a lot of stuff that would be undone if this were merged.

**Comment by Fiocitrine** [comment]
I know. When I try to rebase I can't find the commits I made in tortoisegit

**Comment by Fiocitrine** [comment]
I go to Rebase > then check Force Rebase then just rebase?

**Comment by Hozu** [comment]
You need to do a pull to your master branch prior to doing a rebase, so it will be applied to the latest commit.

**Comment by Fiocitrine** [comment]
I did that and now I'm rebasing but I get a Cherry-picked failed! error

**Comment by Hozu** [comment]
Huh, I haven't had that particular error before. Unfortunately I no longer have anything installed so I can't help you figure things out. :/

**Comment by Fiocitrine** [comment]
hmmm I'll redo this

**Comment by takhlaq** [comment]
yes you'll get a cherry pick failed on a merge, so you'll need to resolve conflicts again

**Pull request closed without merging**
