### PR TITLE
CORE: Mobs no longer path through walls...

### PR DESCRIPTION
**Pull request by m241dan**
Because Bad Friggin Dyslexic Algorythm

### CODE REVIEW

**Comment by bendangelo** [comment]
I don't think this changes anything?

**Comment by m241dan** [comment]
Sure fixed it on my server.

**Comment by Fr0zt** [comment]
Mobs sure as hell path through walls on my server, as well as walk on water/air. I know they are supposed to wallhack when they don't have a path to you, but mobs wallhack all the time for me.

**Comment by bendangelo** [comment]
I see what this fixes. The mob won't look at the point if it is already on the target point. I think the `LookAt` method should be slightly refactored but this is a good fix.

**Pull request merged**
