### PR TITLE
Update settings.lua to add ENABLE_ROV

### PR DESCRIPTION
**Pull request by some1here**
added expansion

### CODE REVIEW

**Comment by some1here** [comment]
git push some master -f

everything up-to-date

**Comment by some1here** [comment]
Ran git commit --amend, then git push -f 
said: 1 file changed, 1 insertion
but they just refreshed this post

**Comment by bendangelo** [comment]
thanks

**Comment by some1here** [comment]
No, Thank you........ sorry if I am dumb

**Pull request merged**
