### PR TITLE
Small tweak for nation mission 5-1.

### PR DESCRIPTION
**Pull request by TeoTwawki**
(Despawn the other mobs, because BCNM cleanup is so slow that the adds will kill you while cs loads. And sorcerer kill is not a win requirement, only archlich is.)

### CODE REVIEW

**Comment by TeoTwawki** [comment]
Note: I keep seeing ppl say in irc that this mission is broken. I just ran through entire mission before making this pull, works fine for me not seeing any missing mob issues etc...

**Comment by teschnei** [comment]
sounds like a problem elsewhere... Asked demo or max to look at them not
despawning instantly?

**Comment by teschnei** [comment]
They should, unless im missing some specific case they shouldn't

**Comment by TeoTwawki** [comment]
They depop, its just slow. Massive lag as cs loads.

**Comment by TeoTwawki** [comment]
Running the depop command in onMobDeath happens instantly, so I put it back in (it was removed last time I touched this).

**Comment by TeoTwawki** [comment]
@xdemolish  @maxtherabbit either of you wanna volunteer to make this pull request uneeded?

**Comment by teschnei** [comment]
Yeah, they should depop as soon as the conditions are met. (Also players in
a full cs are supposed to lose aggro but that's something else)

**Comment by xdemolish** [comment]
can't depop if the warriors are spawned outside the battlefield handler!

**Comment by teschnei** [comment]
yeesh, this is gonna be fun. No way to tell if a mobs part of a bcnm either
I don't think... I'd like to do this in a way that doesn't involve changing
the scripts. Maybe check the mobs zone in SpawnMob, see if its a bcnm zone?
I suppose that doesn't really work for bahamut bcnm, or any other stuff
that might use that system (voidwatch maybe?).

**Comment by gedads** [comment]
INSERT INTO `bcnm_battlefield` VALUES ('512', '1', '17620993', '3');
INSERT INTO `bcnm_battlefield` VALUES ('512', '1', '17620994', '3');
INSERT INTO `bcnm_battlefield` VALUES ('512', '1', '17620995', '3');

Maybe it's because other adds if left alive (17620996 ,97,98,99) aren't in the bcnm_battlefield so aren't cleared on win?

**Comment by TeoTwawki** [comment]
I gather whatever is being done to bcnm system is going to take awhile. How about we allow the 4 line fix that works without probs just for now? Can always be removed (again) later.

**Comment by teschnei** [comment]
Figuring out if the bcnm system even needs changes yet or if you just need
to add them to the bcnm table

**Comment by TeoTwawki** [comment]
Can't add the warriors to bcnm table, that would be non retail behavior - they are NOT supposed to be up at start, they are spawned repeatedly by Archlich during fight..

**Comment by teschnei** [comment]
that's why I added that extra column like 2 years ago. you don't see both
phases of shadow lord spawned at the beginning of 5-2 ya?

**Comment by TeoTwawki** [comment]
.........Didn't even know he was 2 IDs, or about this extra column. >.>

I'll test and amend later today.

**Comment by teschnei** [comment]
Its a bit packed number (only 2 bits ATM..), one is for spawned at the
start, the other is for required to be killed for victory. I don't remember
the name, but I assume if you put the skeletons in there as 0 they should
despawn when the bcnm cleans up.

**Comment by TeoTwawki** [comment]
Amended and tested. The whole end of bcnm is still quite slow, but they stop attacking and depop properly so its good. I never knew what that last field in the table did or where it was enum'd till now, just kept what was already there.

**Pull request merged**
