### PR TITLE
Synth/Desynth | Swap 1 to 0 and Vice Versa

### PR DESCRIPTION
**Pull request by Cryptexx**
Changes made:

1. In synth_recipes, renamed column 'Type' to 'Desynth'.
2. Swapped 1's and 0's so normal synths are now 0 and Desynth is a 1 under 'Desynth'.
3. Added column 'ResultName' that lists the NQ result for human readability.
4. Changed core files to reflect 0 being normal synth and 1 being desynth.
5. Updated query in synthutils to reflect new 'Desynth' column name.

### CODE REVIEW

**Comment by helixhamin** [comment]
Not sure about this

> Added column 'ResultName' that lists the NQ result for human readability.

I understand. One reason I created my excels, to let me see these things, but this just causes more unneeded bloat to the tables. I guess the people with actual authority to merge will need to weigh in though.

**Comment by TeoTwawki** [comment]
That "unneeded bloat" was to spare us from future loss of data via lost comments when redumping. It has no functional difference its just adding human readability so we don't have to go running to item_basic or ffxiah to see what the result item was or really on maintaining a comment next to the row. Just moving that comment into the row itself basically. A bunch of us on discord chimed in that we preferred to at least preserve the item name.

If I have to right scroll a mile, then I consider it bloaty. code wise mysql does extremely well with massive amounts of rows and columns. Pretty much exists _because_ a machine can do well with such things while a human cannot.

**Comment by helixhamin** [comment]
Sure, I asked before about something like that, that would basically make it more of a permanent comments type of thing, but I was told it would not be accepted. Why I thought this would not really be approved. If it is, well, no concern to me.

**Comment by TeoTwawki** [comment]
Told by who? Most thinsg kinda depends who you ask, which is why this isn't insta merged - give everyone a chance to object.

**Comment by ibm2431** [comment]
Regarding Name as a _column_: How often are redumps done/used? Would it be useful?

Not weighing in either way; asking because I honestly don't know since I've never worked on something that'd benefit from a DB redump.

**Comment by ibm2431** [comment]
And this has been linked to a few times recently on Discord, but for those that only follow DSP through GitHub, this PR is addressing #3544. Previous discussion/some ideas can be found there.

**Comment by Cryptexx** [comment]
I've seen some discussion before as to whether desynth was actually being used in any calculations (looks like it's referenced in that PR too). I just want to clarify that Type (now called Desynth) **is** being read while verifying the recipe and whether it's a normal synth/desynth does have an effect on the mods being used during synthesis calculation.

**Comment by TeoTwawki** [comment]
@ibm2431 this happened specifically because the person PR'ing this had a situation that would be made a ton easier by redumping, but would lose comments. But with 1 join on the query we could get the item name back so that happened. Looking at the file, it looks like the comments were manually re-added _anyways._ As a rule redumps have been avoided and should not happen often, but the reason for that (in most tables) has always been comment loss or people that don't keep it sorted making the diffs hellish to review.

@Cryptexx the part that would make desynths have a drastically lower success rate compared to synths isn't in there yet.

**Comment by Cryptexx** [comment]
@TeoTwawki Yes, I agree. Desynths aren't fully coded yet, but it is accounted for and the stage is set for further development.

**Pull request merged**
