### PR TITLE
DB/SQL: Item and Weapon update

### PR DESCRIPTION
**Pull request by theRonLewis**
all credit goes to legionffxi from Darkstar project forums, found here:

https://forums.dspt.info/viewtopic.php?f=20&t=2342

Stumbled across this on the forums, figured just needed to be uploaded
for people to utilize. Got w/Wadski to test things out on his test
server, and everything looks good as far as we can tell.

files updated:
/sql/item_armor.sql
/sql/item_basic.sql
/sql/item_latents.sql
/sql/item_mods.sql
/sql/item_weapon.sql

### CODE REVIEW

**Comment by R3P0FFXI** [comment]
This is an old Legion update from 6 months ago, all these weapons are already in game in our last weapon and item update. This PR should be cancelled.

**Comment by theRonLewis** [comment]
Ah, alright. I was under the impression that even though the files were old, they still hadn't been integrated to core. Was helping a friend from our private server get these added.

Thanks for checking out the PR quickly.

**Comment by TeoTwawki** [comment]
Its probably just the mods table entries missing then.

**Comment by TeoTwawki** [comment]
"22,295 additions, 21,202 deletions not shown"
Gee, thanks for being useless github.. Its beyond their view limitations, presumably because the format changed so much that it thinks every line has changed, like a re-dump or line ends changed.

**Comment by theRonLewis** [comment]
Does this PR need to be re-opened, or re-requested to have it checked out and added in then?

**Comment by TeoTwawki** [comment]
I'd make a new one, starting with a clean copy of darkstar and manually adding only lines definitely not already in file (that way the changes can actually be seen in the diff report on github).

**Comment by theRonLewis** [comment]
Alright, I'll work on getting that done here in the next few days - at work now.

Thanks Teo.

**Comment by theRonLewis** [comment]
Question on that I guess - would it be better to revert back my branch merge, or to delete my fork and re-fork and start completely anew?

This is my first time contributing to a large project, sorry for the probably simple questions. Thanks.

**Comment by TeoTwawki** [comment]
Tip: avoid making your changes on the master branch, make a new branch. When creating a branch via github it always begins life as a 1:1 duplicate of master.

As for your quest both of those should have the same resulting files if the fork was fully up to date with darkstar before you made changes.

**Comment by theRonLewis** [comment]
Yep, I had created a separate branch, but then merged it with my master and did the pull request from that new master.

I went ahead and reverted back that merge. In the future when I do pull requests, I won't merge into my master and instead just do the pull request directly from the new branch on my fork, I'm assuming thats what you're saying I should be doing.

If I use this reverted back fork and have issues, I'll just start all over again incase I dun goof'd somewhere.

Thanks again!

**Comment by teschnei** [comment]
Yes, don't use master for anything other than pulling from our repository

**Pull request closed without merging**
