### PR TITLE
SQL: Added item latents that required ID 56

### PR DESCRIPTION
**Pull request by BRFord88**
Added rune equips and 1 other that required the latent ID 56
implementation.

### CODE REVIEW

**Comment by bendangelo** [comment]
CI failing, otherwise looks good

**Comment by BRFord88** [comment]
What could be the possible cause of this?

**Comment by Hozu** [comment]
Wonder if it's because the latent doesn't exist in this particular branch, since it's in the other pull.

**Comment by teschnei** [comment]
Importing item_latents.sql into the database...ERROR 1136 (21S01) at line 2749: Column count doesn't match value count at row 1

**Comment by teschnei** [comment]
the takeaway here is that you do actually need to compile/run/test your changes - I certainly don't have the time to do them for you

**Comment by BRFord88** [comment]
I understand. I'll wait until the latent Id is merged and then try to upload this again.

**Pull request closed without merging**
