### PR TITLE
Psoxja lift patch

### PR DESCRIPTION
**Pull request by Turttle**
Updated and tested the scripts. All of the lifts are working as intended.

### CODE REVIEW

**Comment by TeoTwawki** [comment]
Grats on successfully working with the current ridiculous elevator code.

**Comment by Turttle** [comment]
I'm not 100% sure how it works, but it does ^.^

**Comment by nesstea** [comment]
tytytytyty

**Comment by xdemolish** [comment]
once you fix fort ghelsba we can close https://github.com/DarkstarProject/darkstar/issues/752 :p

**Comment by ashdam** [comment]
Hahaha ;)  {yes, please}

**Comment by Turttle** [comment]
does the Fort Ghelsba lift has a special id, like the one id Port Bastok?

**Comment by TeoTwawki** [comment]
Fort Ghelsba one has a lever at top and bottom. Can actually be done much simpler than the others. To use existing elevator framework, copy what palborough miens one does and change the IDs.

**Comment by Turttle** [comment]
Palborough mines one does have a unique id = ELEVATOR_PALBOROUGH_MINES_LIFT.
If I change the id = ELEVATOR_FORT_GHELSBA_LIFT then server crashes and i get error DSP_DEBUG_BREAK_IF(lua_isnil(L,1) || !lua_isnumber(L, 1)); <~ breakpoint

**Comment by TeoTwawki** [comment]
What you likely ran into is one the reason I hate the current implementation: its done on spawn, and in some cases the elevator code can't be in the actual elevator NPC or its lever. It has to be the NPC that gets loaded first (lowest ID value of all involved NPCs).

Also from your crash I can tell you aren't ion teh most recent version of DarkStar because Kj made a change the other day that has it abort instead of crashing when that happens.

**Comment by TeoTwawki** [comment]
We need to switch IRC or forum thread (or forum PMs) because ppl get emails every time we post here.

**Comment by TeoTwawki** [comment]
@xdemolish I summon thee! @Turttle has the scripts for elevator and lever looking correct, and I just made sure eh defined the elevator ID in status.lua with the others. His crash is fixed but elevator didn't go.

**Pull request merged**
