### PR TITLE
bcnm

### PR DESCRIPTION
**Pull request by RoahZoe**
added bcnm and some synth recipes

### CODE REVIEW

**Comment by xdemolish** [comment]
https://github.com/DarkstarProject/darkstar#pull-requests

> Commits should contain a descriptive name for what you are modifying

**Comment by xdemolish** [comment]
also you have way too many sql changes for us to review, recommit 100 line changes per commit

**Comment by helixhamin** [comment]
@RoahZoe 
Recommend submitting the BCNM and synth issues separately. For the LUA changes, the line limit isn't the issue, since the LUAs need to be fully created. But as demolish stated, for SQL changes, you need to break your changes into multiple submissions. Also recommended: Do not upload files like this. I have personal experience on how much worse it can make it. It is recommended to make your changes locally and submit via normal git pushes, not to drop files in via upload. It created a major headache for me in the past...

**Comment by RoahZoe** [comment]
cool thanks for the advice

**Pull request closed without merging**
