### PR TITLE
SQL/SCRIPTS: Added Nether Blast

### PR DESCRIPTION
**Pull request by Zenny89**

### CODE REVIEW

**Comment by teschnei** [comment]
The ability and the mob skill don't look in the same directory for their
scripts. The mob skill will not look in abilities/pets

**Comment by Zenny89** [comment]
I followed the instructions located here: https://wiki.dspt.info/index.php/Core#Special_Case:_Avatar_BPs
It works on my test server.

**Comment by teschnei** [comment]
Yes, it works fine for pets. But you changed the script name in mob
abilities too

**Comment by Zenny89** [comment]
I changed the script name in mob abilities only for "-- Pet - Diabolos". I didn't touched "Diabolos (Darkness Named)  or (Waking Dreams) because I do not know the correct equations for enemy Diabolos. Which part should of this should I change?

**Comment by teschnei** [comment]
okay, I see now: the mob_skill.sql rows under "Pet - Diabolos" were just a copy/paste of the real Diabolos abilities and weren't correct - I'll review the script itself later

**Comment by Zenny89** [comment]
Okay, thanks!

**Pull request merged**
