### PR TITLE
fix hq synth rates

### PR DESCRIPTION
**Pull request by wrenffxi**
divide int literals (1/2), get an int output (0)

### CODE REVIEW

**Comment by TeoTwawki** [comment]
can we possibly recast it to enable using actual division?

**Comment by wrenffxi** [comment]
I mean if you're averse to float representation and really want fractional representation you could divide float literals (1./2.) and get the same number.  Just can't divide int literals, or you'll get an int result.

**Comment by TeoTwawki** [comment]
@isotor so about that testing our changes my dude :)

**Comment by TeoTwawki** [comment]
@wrenffxi I'm fine with however this turns out but there was some discussion about clarity, /shrug I'll let someone either merge as is or tell you what they want here.

**Pull request merged**
