### PR TITLE
[Sea] Missing Mob IDs, removed uneeded variables.

### PR DESCRIPTION
**Pull request by ProjectTako**
scripts/zones/The_Garden_of_RuHmet/MobIDs.lua
-Added the mob IDs that other files (such as Zone.lua) access. 

scripts/zones/The_Garden_of_RuHmet/Zone.lua
-Removed old unneeded variables.

### CODE REVIEW

**Comment by Turttle** [comment]
ID for JoF qm is off.

**Comment by ProjectTako** [comment]
Are you sure? When I go look up the NPCs in the sql file:
https://raw.githubusercontent.com/DarkstarProject/darkstar/master/sql/npc_list.sql

The entry for 16921028 is this: INSERT INTO `npc_list` VALUES (16921028,'qm2','???',224,-560.000,5.000,239.000,7,40,40,0,0,0,0,3,0x0000340000000000000000000000000000000000,0,'COP');

If I jump to that position (-560, 5, 239) it puts me in an IxDRK room with Aerns. If I jump to the positions for qm1 and qm3, they line up with what I currently have. I will be glad to fix it, just wanting to make sure.

**Comment by Turttle** [comment]
it might have been wrong on the lua before the change then.

**Comment by nesstea** [comment]
@ProjectTako I already pushed the MobIDs.lua

**Pull request closed without merging**
