### PR TITLE
Scripts/Quest: Claws of the Griffons.

### PR DESCRIPTION
**Pull request by Vivitarut**
- Cut scene for onZoneIn in Jugner[s] was missing.
- Updated FingerFilcher Dradzad's name in db for Fingerfilcher_Dradzad.lua.
- Added Allied ribbon of glory key item and fixed a typo in itemid reward.

### CODE REVIEW

**Comment by Vivitarut** [comment]
qm6.lua contents was showing on a single line in git along with the changes i made, i had to convert it to crlf and back to lf with notepad++ to fix it.

**Comment by gedads** [comment]
Hi, you seems to be interested in wotg! i hope this will help you
http://pastebin.com/XbRyynFm all cs from mission 9->53 and with ki zoning etc
i have to do the same for quests as this are just the missions but i'll try to do it quickly if you're willing to do all wotg

**Comment by Vivitarut** [comment]
@gedads

I have up to mission 15 scripted from last year for all nations except for the battlefields, that list will be very helpful for the remaining ones, thanks!

**Comment by Vivitarut** [comment]
Quick walkthrough for testing:

  Rholont                    @pos -166 -2 54 80
                             @zone 81
  cs                         @zone 82
  ???                        @pos 70 0 326

**Comment by gedads** [comment]
yes some just can't be done atm like fire in the hole with adelhaide having a specific behaviour and other quests with similar instances leading to upper missions.

**Comment by xdemolish** [comment]
rebase
oh and squash the quests.lua and other changes into one commit

**Comment by Vivitarut** [comment]
@xdemolish

What happened exactly? Should i close this and submit a new one?

**Comment by xdemolish** [comment]
pull > resolve conflicts > rebase > squash >force push

should be good then

**Comment by Vivitarut** [comment]
@xdemolish

Done.

**Comment by xdemolish** [comment]
still cant merge
try again, need to pull from dsp master, not your fork's

**Comment by Vivitarut** [comment]
I don't know what i'm doing wrong, in git git, i remote >> fetch from >> origin then switched to my branch and pushed it, maybe i'm missing a step?

**Comment by teschnei** [comment]
Merge master to your branch

**Comment by Vivitarut** [comment]
@teschnei

Merge done and pushed.

**Comment by xdemolish** [comment]
what kj said, and fetching doesn't integrate remote changes (on tortoisegit anyways)

anyways, if you also have tortoisegit you can just pull from origin/master straight onto your branch, or
switch to master, pull from origin/master, switch back to branch and merge changes from master into branch

there's probably an easier way to do it from commandline (i personally use tortoisegit cause i prefer gui)

**Comment by Vivitarut** [comment]
@xdemolish

I use both the tortoise and command line, git rebase origin/master gave me errors but doing the merge from the gui worked, hopefully i did it right this time.

**Comment by Vivitarut** [comment]
Looks like i messed up again somehow, i see 22 commits where there should be 2, sorry :[

**Comment by xdemolish** [comment]
hop on irc and someone'll talk you through it (i say someone since i personally won't be at my pc for another 8 hours or so)

don't wanna spam everyone with emails as github sends one out for each comment

**Comment by teschnei** [comment]
will close this until it can be put to a new branch and can be merged

**Pull request closed without merging**
