### PR TITLE
Add Stables Teleport Items

### PR DESCRIPTION
**Pull request by Wiggo32**

### CODE REVIEW

**Comment by TeoTwawki** [comment]
truly shocked we didn't have these already. I never even thought to check, multiple servers have had them.

**Comment by TeoTwawki** [comment]
Correct pos for stables scarf should be `123,-6,-134,0,241`

lets use the teleport global

**Comment by TeoTwawki** [comment]
oh its already in there even..
https://github.com/DarkstarProject/darkstar/blob/5078b8b1b71c30af4a5fbcb9075787e5a9a3cd3f/scripts/globals/teleports.lua#L752
```lua
function federationStablesScarf(player)
    player:setPos(123,-6,-134,0,241);
end;
```

**Comment by takhlaq** [comment]
dont forget to use the teleport effect

**Comment by TeoTwawki** [comment]
can check any of the existing items that use the teleport global to see what they do

**Comment by Wiggo32** [comment]
should I round all of those pos's I got from retail?

**Comment by Wiggo32** [comment]
wait... nevermind... i think i see what to do

**Comment by TeoTwawki** [comment]
I was going by what I thought was a captured pos, if whats in the global is rounded, feel free to un-round them :)

**Comment by Wiggo32** [comment]
yea, I just saw that... was on it

**Comment by Wiggo32** [comment]
hmmm.... this teleport system is kind of leaving me slightly confused...

**Comment by TeoTwawki** [comment]
Example:
```lua
-----------------------------------------
-- ID: 13181
-- Item: Federation Stables Scarf
-- Enchantment: "Teleport" (Windurst Chocobo Stables)
-----------------------------------------
require("scripts/globals/teleports")
require("scripts/globals/status")
-----------------------------------------

function onItemCheck(target)
    local result = 0
    if not target:isZoneVisited(241) then
        result = 56
    end
    return result
end

function onItemUse(target)
    federationStablesScarf(target)
end
```

**Comment by Wiggo32** [comment]
yes, that's what I was thinking exactly, but then Demo was like "don't forget the teleport effect" and I got confused... ok, I'll do them all up like this.

**Comment by TeoTwawki** [comment]
I think he was composing that before my multi message

**Comment by Wiggo32** [comment]
no worries... fixed them all up... tested them all... working!

**Pull request merged**
