### PR TITLE
sql/item_mods

### PR DESCRIPTION
**Pull request by bn7**
3 sets

### CODE REVIEW

**Comment by xdemolish** [comment]
looks good, need you to rebase/squash if it passes the checks then force push

**Comment by xdemolish** [comment]
assuming you've tested in-game, of course

**Comment by bn7** [comment]
yup

**Comment by xdemolish** [comment]
you clearly didn't test
https://travis-ci.org/DarkstarProject/darkstar/builds/128407801

**Comment by TeoTwawki** [comment]
psssst commenting what item and modifier it is helps

**Comment by TeoTwawki** [comment]
jus sayin

**Pull request closed without merging**
