### PR TITLE
Version-Update/December-2017

### PR DESCRIPTION
**Pull request by dragonarmor**
Npc shifts updated
Lua scripts updated
TextIDs update
TextID aesthetic's have been updated. This will make the updates a little more easy to work with.

### CODE REVIEW

**Comment by dragonarmor** [comment]
Closing this I'll need to recheck NPCid shifts. my bad.

**Comment by TeoTwawki** [comment]
if you can in the future, split the swl and lua into separate prs.

sucks having to scroll pasthundreds of files to check the npc list. I'd say seperate commits was enough but then I hafta look at any extra commits adusting or else just pull it all in local to look

**Comment by dragonarmor** [comment]
Yes I can do that. Do you prefer TextIds and Npc Shifts on separate prs?

**Comment by TeoTwawki** [comment]
yeah 1 for just text id and one for the rest works

**Pull request closed without merging**
