### PR TITLE
SW Apollyon 3rd floor mimics

### PR DESCRIPTION
**Pull request by kitala1**
SCRIPTS: Apollyon 3rd floor now spawns armoury crates and mimics again. Also fixed some wonky references I found

### CODE REVIEW

**Comment by kitala1** [comment]
If someone has any insight as to why this broke in the first place, I'd gladly welcome it. I couldn't find any files  or evidence that broke the 3rd floor, it simply stopped popping armoury crates after the last server update we had. 

The issue I found was that onEventFinish was not being called when you select "Yes" when prompted to move to the next floor of Apollyon, but it was being called when you selected "No". All I did was move the call to spawn3fcoffers to onEventUpdate, which was being called every time I moved floors...

**Comment by xdemolish** [comment]
commit labels please (see https://github.com/DarkstarProject/darkstar/blob/master/README.md)

**Comment by kitala1** [comment]
Fixed, sorry about that

**Comment by Hozu** [comment]
Oh hey this also fixes the chest drop from the elementals on 4f in SW. They weren't dropping either.

**Comment by xdemolish** [comment]
squash > force push
(so it sticks all the changes in one commit since the old one without the label is still hanging around)

**Comment by kitala1** [comment]
Done! :)

**Pull request merged**
