### PR TITLE
Do not allow shield blocking while terrorized

### PR DESCRIPTION
**Pull request by ymkc**
Stumbled across this and was marked as easy fix :)

and btw what about parrying while being terrorized, is it possible on retail?

#2731

### CODE REVIEW

**Comment by Deadwing888** [comment]
I think yes parry while asleep, no while terrorized.

Not 100% sure.

**Comment by teschnei** [comment]
what about sleep? stun?

**Comment by Deadwing888** [comment]
I believe shield block cannot proc during petrify stun or sleep

**Comment by takhlaq** [comment]
hmm is it only terror or other effects such as stun?
if other effects prevent then https://github.com/DarkstarProject/darkstar/blob/master/src/map/status_effect_container.cpp#L1444

**Comment by bendangelo** [comment]
If there are more status effects, might as well add a flag `no_shield_proc` and add it to those status effects. Then in that condition you can just check if any status effects have the flag.

**Comment by teschnei** [comment]
an entire flag for one spot...?

**Comment by Deadwing888** [comment]
Is it still the case that shield block does not work VS mob's physical ws on dsp?
I have not tested recently, but this was the case for quite some time

**Comment by TeoTwawki** [comment]
Lets start by verifying what retail does for each situation *exactly* since I'm not the only one who's commenting with uncertainty here.

I'm fairly sure I've gotten retail shield procs while slept, but not only was that a long time ago and my memory hazy, but entirely possible things could have changed (though I see nothing about any changes on either wiki, nor any mention of being able to proc or not).

Lets just make sure before we fix more of it, is all mean to say.

**Comment by teschnei** [comment]
yes, Deadwing

**Comment by Deadwing888** [comment]
30/100 shield blocks while awake
0/100 shield blocks while asleep

I wasn't 100% sure myself, but now we know. I am much more confident about petrify and stun, but am still happy to check if there are doubts.

**Comment by TeoTwawki** [comment]
Thank you Deadwing.

**Comment by Deadwing888** [comment]
In regards to the mob's physical weaponskills, shield block on retail has a chance to proc vs those. Would someone here like to look at it or should I write it up as a separate issue?

**Comment by teschnei** [comment]
Separate issue if there isn't one already (and please include that additional effects can't proc on blocked mob weaponskills, in case the implementer does not know about that)

**Comment by teschnei** [comment]
As for this PR, that should be good enough reason to use the function @takhlaq linked instead of a specific effect check

**Comment by ymkc** [comment]
Updated PR

Is it safe to assume that neihter guarding nor parrying is possible while being terrorized?
Open a seperate PR for those two and see if some can verify?

**Pull request merged**
