### PR TITLE
SQL/CORE/SCRIPTS: Apogee

### PR DESCRIPTION
**Pull request by Zenny89**

### CODE REVIEW

**Comment by Zenny89** [comment]
Do not send this through yet.

**Comment by Zenny89** [comment]
@teschnei Does it look like I'm using the wrong ID here or is there something else causing this issue?

**Comment by teschnei** [comment]
I looked at it and the code seems to be correct, but I haven't had time to check out your branch and figure out what's wrong yet

**Comment by Zenny89** [comment]
Updated and working. I had the wrong recast ID.

**Pull request merged**
