### PR TITLE
Splice job

### PR DESCRIPTION
**Pull request by TeoTwawki**
@teschnei I dunno what the actual F is going on here, he kept having this happen to his rebase, and now I did a clean clone of stable and cherry picked one single commit and I got this BS myself. It makes no sense at all.

### CODE REVIEW

**Comment by teschnei** [comment]
I can't investigate it until the 1st. Not sure what it could be without
looking at it myself

**Comment by TeoTwawki** [comment]
it's like it thinks the remote was missing these commits, but they already exist. And its different commits than he got.

**Comment by TeoTwawki** [comment]
stable gonna have to wait for its ID fixes for now, I'll be away a lot too. See you on discord if you happen to be around.

**Comment by teschnei** [comment]
Yeah, if I can run git through you later we can look at it, if someone else
doesn't by then

On Dec 23, 2017 3:20 PM, "TeoTwawki" <notifications@github.com> wrote:

stable gonna have to wait for its ID fixes for now, I'll be away a lot too.
See you on discord if you happen to be around.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/DarkstarProject/darkstar/pull/4419#issuecomment-353751434>,
or mute the thread

**Pull request closed without merging**
