### PR TITLE
These are my first .lua files also my first commit, be gentle with me.

### PR DESCRIPTION
**Pull request by Yuchemey**
Signed-off-by: Yuchemey <Yuchemey@hotmail.com>

### CODE REVIEW

**Comment by teschnei** [comment]
title your pull request with what you actually changed, you can mention the rest in the description

**Comment by Yuchemey** [comment]
OH sorry, i've added T2  Etude bard song.

**Comment by teschnei** [comment]
don't forget to make their effect decrease by 1 every 10 seconds (if you don't know how, just ask)

**Comment by Yuchemey** [comment]
I don't know how ^^;, i'll look into it.

**Comment by teschnei** [comment]
the third param to addBardEffect is tick time (how often onEffectTick is called) and the last param is tier (which you should probably change to 2, since it's the second tier)

then you just have to modify effects/etude.lua to lower the stat if it's a) a tier 2 etude, b) is still giving more than 0 of the stat, and c) set the power to the new value of the mod

**Comment by Yuchemey** [comment]
Should the effect be in script/globals/effect/etude.lua or should it be in script/global/spells/<insertspellname>.lua?

**Comment by teschnei** [comment]
find the one that exists already (it's the same one that tier 1 etudes use)

**Comment by Yuchemey** [comment]
ok i made Bewitching Etude i used teotwacki's/temp effect. I forgot i could browse threw the site to help me. is that pretty much it?

**Comment by Yuchemey** [comment]
"if not (target:addBardSong(caster,EFFECT_ETUDE,power,10,duration,caster:getID(), 7, 2)) then"
what is the seven? i know that 10 is the power and 2 is the tier. but the 7?

**Comment by Yuchemey** [comment]
Ok so i modified the effect of the spells as requested. 
-Sub power
-T2 instead of T1
-Tick at 10 instead of 0 
from my previous Push. Let me know what you think.

**Comment by teschnei** [comment]
ok, a couple things here: the second to last param (subpower) is the mod that the etude adds.  so herculean etude should be MOD_STR, etc.

second thing, you still have to modify scripts/globals/effects/etude.lua to tick the effect downwards if it's a tier 2 etude

**Comment by teschnei** [comment]
now just waiting for you to test it so you can fix the typos :)

**Comment by Yuchemey** [comment]
hehe awesome.

**Pull request merged**
