### PR TITLE
[WIP] Murder settings that have a known retail default

### PR DESCRIPTION
**Pull request by isotor**
I have one last attempt in me today >.>

### CODE REVIEW

**Comment by TeoTwawki** [comment]
yer gonna make zynjec happy while annoying me

**Comment by isotor** [comment]
This must be how interns at the United Nations feel 😄

**Comment by TeoTwawki** [comment]
well ya know we could try..discussing things all the way before the work gets done instead of..After.

I merge 30 pr's close ONE and have to see some bullshit about how you've made to many and its time to chase you away by some assclown on discord, doesn't make me very happy here.

**Comment by isotor** [comment]
I'm just trying to do what people want <.< the goalposts keep changing depending on who is awake, and the PRs are raised as "hey would you like this" and "okay how about this" not "yo merge my stuff".

**Comment by tagban** [comment]
TBH we need more configuration options not less. It allows for more unique servers without having to modify the main source code, thus easing the ability to keep up with updates to the core code.

**Comment by helixhamin** [comment]
@tagban The main issue is about who will manage it. We discussed this on the discord. It would be better to find a way to easily allow others to modify the code without dealing with tons of bloated settings toggles that make it more difficult for development. Ideas on how to do that are open.

**Comment by tagban** [comment]
The easiest way to do that is literally push everything to Lua if you wanted to do that. :-\ But that's just as complex. If not more?

**Comment by tagban** [comment]
Plus would contribute to slower loading I'd imagine.

**Comment by TeoTwawki** [comment]
@isotor the goalpost did not change, there is no agreement on what is to be done overall, and going forward before that is not a good idea. if you leave it to zynjec you can kiss all settings goodbye.

@tagban I have a pipe dream of moving "old school" settings to a table in another file, and just load that into settings.lua. Have default behavior for the things those settings would do if they aren't present - old school ppl just insert their setting into script.

**Comment by tagban** [comment]
> @isotor the goalpost did not change, there is no agreement on what is to be done overall, and going forward before that is not a good idea. if you leave it to zynjec you can kiss all settings goodbye.
> 
> @tagban I have a pipe dream of moving "old school" settings to a table in another file, and just load that into settings.lua. Have default behavior for the things those settings would do if they aren't present - old school ppl just insert their setting into script.

I mean, I'd be fine if they moved to SQL since it would NEVER get overwritten and could easily be backed up. But I'm lazy?

**Comment by ibm2431** [comment]
Apologies for my limited understanding of status effects, but might it be possible to handle custom Dia/Bio behavior with just the SQL negative IDs?

**Comment by isotor** [comment]
Yes it would, set them to overwrite 3 (always) instead of 1 (higher only) under a common `negative_id` and boom. I need to submit a PR to harmonize the negid anyway.

**Comment by TeoTwawki** [comment]
previously the settings were removed and a contributor put them back. and correct me if I misunderstand but overwrite always would mean overwriting the lower tier as well. EFFECTOVERWRITE_EQUAL_HIGHER is a thing though.

**Comment by isotor** [comment]
That is the ticket yes, sorry I have too many windows open...

**Pull request closed without merging**
