### PR TITLE
Fix off by 1 IDs in merrypietard mountains [s]

### PR DESCRIPTION
**Pull request by TeoTwawki**

### CODE REVIEW

**Comment by xdemolish** [comment]
Importing npc_list.sql into the database...ERROR 1062 (23000) at line 9140: Duplicate entry '17175338' for key 'PRIMARY'

**Comment by helixhamin** [comment]
Lines 9139/9140:
` INSERT INTO `npc_list` VALUES (17175338,'Indescript_Markings','Indescript Markings',1,-392,-9,88,32775,40,40,0,0,0,2,3,0x0000340000000000000000000000000000000000,0,'WOTG');
 +INSERT INTO `npc_list` VALUES (17175338,'16','     ',0,0.000,0.000,0.000,0,40,40,0,0,0,2,2051,0x0000340000000000000000000000000000000000,0,'WOTG');`

**Comment by TeoTwawki** [comment]
I know - entire damn zone is off by 1

**Comment by TeoTwawki** [comment]
I hate how I always, ALWAYS spot a typo right after I push. It should be fixed now.

**Comment by TeoTwawki** [comment]
Travis passed that last one but appveyor caught the typo.

**Pull request merged**
