### PR TITLE
PROJECT: May 2016 Update version.info

### PR DESCRIPTION
**Pull request by Ninjistix**
client update

### CODE REVIEW

**Comment by teschnei** [comment]
Not until NPC/textids/packets are looked at

**Comment by Ninjistix** [comment]
okay

**Comment by starlightknight** [comment]
I'll look at them sometime before the end of the weekend if no one beats me to it

**Comment by Ninjistix** [comment]
@starlightknight thanks, looking forward to it.

**Comment by Tom-Neverwinter** [comment]
yeah there is a packet or two that is not updated for logout (118 and 11B)

**Comment by teschnei** [comment]
already handled in another commit

**Pull request closed without merging**
