### PR TITLE
Basic fodder mob_droplist updates with mob_groups updated along with an item_basic addition for Sacred Kindred's Crest

### PR DESCRIPTION
**Pull request by Strafeous**
Let me know if you need anything changed. Thanks.

### CODE REVIEW

**Comment by xdemolish** [comment]
in future, split unrelated changes into a separate pull request

**Comment by Strafeous** [comment]
Sure, thanks.

**Comment by Strafeous** [comment]
Oh, the item_basic was a 2% drop off of all of them, it was added along with the Ygrette rocks until @TeoTwawki explained to me that they were all done in the core. :P

**Comment by TeoTwawki** [comment]
@xdemolish @Strafeous specifically, I said "anything global, like crystals, seals, geodes, etc, would wind up in core instead of in individual mob table entry".

**Comment by Strafeous** [comment]
Yeah, gotta make Teo elaborate :)

**Comment by xdemolish** [comment]
uwot i just checked the syntax and merged

**Comment by TeoTwawki** [comment]
@xdemolish thats ok I made sure he didn't put anything in there that didn't belong before he even PR'd while I was teachin him to git gud.

**Pull request merged**
