### PR TITLE
Create Masan

### PR DESCRIPTION
**Pull request by AikoSachi**
Adding new page with era gil amounts.

### CODE REVIEW

**Comment by helixhamin** [comment]
Isn't there already gil drop values in the mob drops table? Why would we need to add a specific lua for him?

**Comment by KnowOne134** [comment]
You could add it to pool_mods

**Comment by megberry** [comment]
BTW, we'll need a Masan.lua eventually to add its melee attack additional effects, so NBD if one's created for it.

**Comment by wrenffxi** [comment]
We'll need a Masan.lua eventually, to add its melee attack additional effects, so NBD if one's created for it.

**Pull request merged**
