### PR TITLE
Huge pile of format adjustments

### PR DESCRIPTION
**Pull request by TeoTwawki**
No more:

```lua
-----------------------------------
-- onTrigger Action
-----------------------------------

 function onTrigger(player,npc)
 end;
```

The department of redundancy department's has lodged a formal protest.

### CODE REVIEW

**Comment by TeoTwawki** [comment]
I forgot to hit the other subdirectories, so I'll need make a followup to this

**Comment by takhlaq** [comment]
i wanna leave this until bcnms are done, though i feel we should have at least a single line comment with either the function name or short (like up to 5 words) description

**Comment by TeoTwawki** [comment]
```lua
-- name
function name
```
gets a big no from me. and there's no reason to describe onTrigger at every single instance of onTrigger either. Such a thing belongs in some actual dedicated documentation one time instead of in every script ever.

conflicts on this shouldn't be real bad with BCNM branch, I didn't even think there would be any honestly. Maybe in the individual BCNM lua's if you touched those from the onEventFinish comments.

**Comment by TeoTwawki** [comment]
if we need a separator:
```lua
function name(args)
    stuff
end;

------------------

function name(args)
    stuff
end;
```

would be more agreeable to me. As would any actual explanatory comments for the actual code:
```lua
-- important note about why we are using this
function name(args)
    -- wtf we are actually doing
    stuff we are doing
end;
```

**Comment by TeoTwawki** [comment]
rebased

**Comment by TeoTwawki** [comment]
> takhlaq changed the base branch from master to bcnmcrap 43 minutes ago

That just puts all of master's commits into it as well. I can't even use rebase to put just my pr's commits there because my PR was up to date with master. So you are seeing conflicts you get comparing master to bcnmcrap not just my changes.

**Comment by TeoTwawki** [comment]
rebased again.

**Comment by TeoTwawki** [comment]
Resolved all issues: there will be no conflicts form this in either master or the bcnm branch

**Pull request merged**
