### PR TITLE
spawn mechanics for lottery NMs in Dynamis Bubu, Beauc, Xarc

### PR DESCRIPTION
**Pull request by wrenffxi**
These are all the non-Jeuno lottery NMs.  Jeuno is weird: some of the NMs have multiple mobids.  Will figure that one out in a future PR.

### CODE REVIEW

**Comment by megberry** [comment]
Forgot to escape my parens.  Fixed!

**Comment by wrenffxi** [comment]
Forgot to escape my parentheses.  Fixed.

**Comment by zynjec** [comment]
Conflicts from your other PR now, RIP.

**Comment by wrenffxi** [comment]
Rebased

**Pull request merged**
