### PR TITLE
[!! NOTICE ME !!] Change player:getVar to player:getCharVar

### PR DESCRIPTION
**Pull request by ibm2431**
(Tag to try and maximize the number of people watching this repository seeing what will be a major change to contributions.)

As discussed on Discord, this PR changes all calls of `player:getVar` to `player:getCharVar`, `player:setVar` to `player:setCharVar`, and `player:addVar` to `player:addCharVar`.

If you have a PR open that uses char vars, working on one not yet submitted, or if you're running a server with a lot of custom code...
"I'm sorry! Blame head honko Lotus! He told me to do it!"

(On the plus side, there weren't any references to "getVar", "setVar", or "addVar" that _weren't_ in the context of char vars. So a blind mass-replace on your code would probably be fine.)

**Forewarning that changing the name of what is currently "getLocalVar" is also planned for after this.**

### CODE REVIEW

**Comment by ibm2431** [comment]
@TeoTwawki Technically you can just pass in a `-1` to `addCharVar` to make it decrement...!

But I don't have a horse in `addCharVar`, I'm just the person who is (overly) eager to mass-replace stuff!

**Comment by TeoTwawki** [comment]
You can “technically” use negatives with addMod and addHP too instead of delMod and DelHP. _if you make a delCharCar I’ll hurt you_

**Comment by TeoTwawki** [comment]
rebase and I'll merge

**Comment by ibm2431** [comment]
Rebased. The Magicite conflict was a good thing, because I forgot about the Lycopodium Sparkles that @kaincenteno added. (They were new, so they didn't flag a conflict)

**Pull request merged**
