### PR TITLE
Updated wyvern types for Geomancer and Runefencer.

### PR DESCRIPTION
**Pull request by joncloud**

### CODE REVIEW

**Comment by whasf** [comment]
GEO and RUN can summon wyverns?

**Comment by joncloud** [comment]
No, but they can be the support job for a Dragoon.

**Comment by teschnei** [comment]
tabs -> spaces

**Comment by joncloud** [comment]
Fixed - Is there a preference, or should it just be consistent with the code around the scope?

**Comment by teschnei** [comment]
If you put spaces in a tabbed file I'd be okay with it (since spaces are
the preference). So I suppose that makes spaces preferred in all situations

**Comment by teschnei** [comment]
all files will be spaces eventually, I swear it! (just not right now because I don't want to convert it all)

**Pull request merged**
