### PR TITLE
SQL: Added modifiers for Asn. Armlets +2, Raid. Poulaines +2, Toro Cape, Atheling Mantle, Friomisi Earring, Ifrit Ring +1, Shiva Ring +1, Mes. Haubergeon, Mes'yohi Slacks, and Cetl Belt

### PR DESCRIPTION
**Pull request by some1here**
SQL: Added modifiers for Asn. Armlets +2, Raid. Poulaines +2, Toro Cape, Atheling Mantle, Friomisi Earring, Ifrit Ring +1, Shiva Ring +1, Mes. Haubergeon, Mes'yohi Slacks, and Cetl Belt

### CODE REVIEW

**Comment by TeoTwawki** [comment]
> SQL: Added modifiers for Asn. Armlets +2, Raid. Poulaines +2, Toro Cape, Atheling Mantle, Friomisi Earring, Ifrit Ring +1, Shiva Ring +1, Mes. Haubergeon, Mes'yohi Slacks, and Cetl Belt

Thats what the commit message should have looked like.

**Comment by TeoTwawki** [comment]
@some1here thats the pull request title, not the commit message

**Comment by TeoTwawki** [comment]
There is no need to close these, anytime branch is updated pull request is automatically changed as well. Amend will let you modify your last commit, and a force push will make the remote branch match your local copy. You may want to google these features of git.

**Comment by xdemolish** [comment]
oh and you shouldn't commit to dev branch
pull from origin/master > commit changes to a new branch > push to fork > open a new pull request on dsp master

**Pull request closed without merging**
