### PR TITLE
Scripts/SQL: Corrected valid targets for Auspice/Esuna/Sacrifice

### PR DESCRIPTION
**Pull request by Hozu**
Disabled the ability to cast Auspice on others via command - it's a self only spell that's AoE like Esuna.

### CODE REVIEW

**Comment by teschnei** [comment]
why would you do that in the script?

**Comment by Hozu** [comment]
It's already done in the database but that only affects what you can target via menu cast or <stpc> or <stal> or whatever. Doing /ma Auspice name would still work on others.

**Comment by teschnei** [comment]
i think you are mixing "the client" with "the database"

**Comment by Hozu** [comment]
...You are correct, it was wrong in the DB. Changed it there instead.

**Pull request merged**
