### PR TITLE
Database/SQL: item_mods

### PR DESCRIPTION
**Pull request by Desufire2**
Here's our item_mods. There isn't 1 specific thing he added, like Empy items. He just said that he's been adding things that he has found not there. So a lot of stuff.

### CODE REVIEW

**Comment by teschnei** [comment]
you'll have to resolve the conflicts before I can merge it

**Comment by Desufire** [comment]
Yeah sorry. Got busy with work. Will look at it and fix today.

**Comment by Desufire2** [comment]
Man, what a pain this is lol

**Comment by Desufire2** [comment]
I wouldn't merge this yet. I'm going over it compared with the latest item_mods pull and there's a lot of stuff that has been added that I'm finding are different from what he put in. Somebody has errors whether it be this one or whomever submitted the recent changes that were made. I'm going to say it's ours though.

Gonna keep this open for after I update it and correct it ... which I trusted my GM to do....

**Comment by xdemolish** [comment]
reopen this pull req when updated so i don't keep looking at it thinking it's new lol

**Pull request closed without merging**
