### PR TITLE
Fixing Quick Draw for Corsair.

### PR DESCRIPTION
**Pull request by Heepster03**
-- It was 1 second, fixed it to 1 minute as it should be.

### CODE REVIEW

**Comment by teschnei** [comment]
What's the problem? It's one charge - the old SQL is right

**Comment by Heepster03** [comment]
The problem is that it's spammable

**Comment by Heepster03** [comment]
Each of the shots are set to 1 second, therefore if quickdraw recharges a "charge" in 1 second, then it's spammable. Setting the QuickDraw to 1min then it isn't spammable and according to bgwiki/ffxiclopedia, it's 1min recast.

**Comment by teschnei** [comment]
I need to verify this before anyone merges.

**Comment by Heepster03** [comment]
https://www.bg-wiki.com/bg/Quick_Draw

http://ffxiclopedia.wikia.com/wiki/Quick_Draw

Take your pick, each clearly state 1min timers.

**Comment by TeoTwawki** [comment]
@heepster03 not what he meant just calm and wait bruh

**Comment by Heepster03** [comment]
Oh, one more thing to add to maybe make things easier.

"Initially you have 2 Quick Draw charges. These recharge at 1 per minute. Each Quick Draw Recast merit will reduce this by 2 seconds to a maximum of -10 seconds with the full 5 merits."

**Comment by teschnei** [comment]
Can't reproduce.  It's working as intended, seems like your server is
missing the abilities_charges table.

**Comment by teschnei** [comment]
Sorry, yes, I know how Quick Draw works (I wrote the entire thing), I just
meant I needed to verify the behaviour you were seeing.

**Comment by TeoTwawki** [comment]
that should leave a log error shouldn't it?

**Comment by teschnei** [comment]
Maybe the table is there but it's empty - but the behaviour he is seeing would be explained by Quick Draw not being joined to abilities_charges properly

**Comment by TeoTwawki** [comment]
investigation results: Old bad data in char_recast table

**Pull request closed without merging**
