### PR TITLE
Fix SQL syntax errors that came in with #1840

### PR DESCRIPTION
**Pull request by TeoTwawki**
@xdemolish @whasf  laugh away boys. Travis didn't see it either.

### CODE REVIEW

**Comment by TeoTwawki** [comment]
> Importing item_mods.sql into the database...ERROR 1062 (23000) at line 31183: Duplicate entry '27874-1' for key 'PRIMARY'
>
> The command "sh travis_sql.sh" exited with 0.

**Comment by TeoTwawki** [comment]
@some1here I fixed the mistakes

**Comment by some1here** [comment]
I am sorry for any mistakes. I had to cut and paste and change a lot of
locations

**Comment by TeoTwawki** [comment]
@some1here Its my fault for not looking for the same ones that were pointed out in  #1822 
When TravisCI gave it a pass I assumed it was all set.

**Pull request merged**
