### PR TITLE
Add trust cast animation

### PR DESCRIPTION
**Pull request by giroroxi**
- Add a single trust: Shantotto to the spell list.
- Add cast/finish animations for spellcasting.
- Fix typo which causes mining.lua to error out.
- Make !addspell save the added spell for that character.

Test this via:
```
!addspell 896
```
Then cast `Shantotto`. Currently nothing happens afterwards in order to keep this PR small.

### CODE REVIEW

**Comment by TeoTwawki** [comment]
Do you mind if I just merge the part I didn't already have into my branch where I was already working on this? I'm farther ahead.

**Comment by giroroxi** [comment]
No problem, go for it. Progress is progress regardless of who does it.

**Comment by giroroxi** [comment]
If you can link to your branch that'd be great, to see what is missing.

**Comment by TeoTwawki** [comment]
going to move from my own branch to a branch in the project, so we can all work and pr to that branch instead of master. right now merging our 2 branches together to form the base of that and I'll send up my un-pushed work later. Your actual commit will be there so credit is preserved.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/tree/trust

my remaining work in the branch actually deals with the fellow NPC more than trust NPCs..But I did start a table for data about trusts as most stuff in the spell list table doesn't apply to them. I had been using Shantotto II as my test subject so now there are scripts for both in there. I'll sort out my remaining mess and push it soon™

**Pull request closed without merging**
