### PR TITLE
[WIP] Consolidate first batch of settings into OLDSCHOOL_ENABLED

### PR DESCRIPTION
**Pull request by isotor**
First trial batch of consolidating global settings into a single switch. Will add more but wanted to get (#engagecorporate) gauge the temperature of the room before spending more time on it.

Please Don't merge yet, there is plenty more >.>

@zynjec

### CODE REVIEW

**Comment by ibm2431** [comment]
Death to `STONESKIN_CAP`!  :fire: :mountain:
And `AQUAVEIL_COUNTER`! :fire: :droplet:

(These have never been changed. And current players on retail are getting hit _harder_ these days, so 350 should be ample!)

**Comment by isotor** [comment]
Can I also kill the DIA/BIO_OVERWRITE now they work properly pleeeeeease @TeoTwawki

**Comment by zynjec** [comment]
This still doesn't resolve having to maintain multiple "bases" for some code, lots of if trees, and now more in-fighting of what is considered "old school" and if it should/could be included in it.

**Comment by TeoTwawki** [comment]
@DarkstarProject/contributors  @DarkstarProject/core what say you to a "oldschool.lua" that the rest of us can simply ignore

**Comment by maxtherabbit** [comment]
"oldschool" is too ambiguous, if we were going to consolidate settings I would suggest having specific expansions as the dividing line only

**Comment by TeoTwawki** [comment]
>  specific expansions as the dividing line only

I suggested that earlier today, when my lunch break hits today I'm trying something in a branch to see how it looks (splitting into separate tables)

**Pull request closed without merging**
