### PR TITLE
More Retail item Mods

### PR DESCRIPTION
**Pull request by R3P0FFXI**
Blah Blah more mods...

### CODE REVIEW

**Comment by TeoTwawki** [comment]
@R3P0FFXI it seems my history surgery to fix the mess followed by the rebasing had unwanted effects on attribution.

**Comment by TeoTwawki** [comment]
@takhlaq not it this time! if I have to review legions items my head'll explode

**Comment by R3P0FFXI** [comment]
I am going to assume noone has issues with this PR as noone has commented

**Comment by takhlaq** [comment]
was trying to coax someone into writing tool to auto check item pull reqs but failed
though i guess if i ever finish export tool that won't be needed

im not gonna bother checking so can wait a few days before i check/blind merge

**Comment by TeoTwawki** [comment]
if its gonna get blind merged I may as well do it now

**Pull request merged**
