### PR TITLE
Nuno pires cruz patch 1

### PR DESCRIPTION
**Pull request by nuno-pires-cruz**

### CODE REVIEW

**Comment by nuno-pires-cruz** [comment]
I hate Git

**Comment by TeoTwawki** [comment]
sure sure, blame the git. :stuck_out_tongue: 

the poor git can't help being dumb, Linus coded him to be that way!

**Comment by nuno-pires-cruz** [comment]
lol Teo. i  only use Git from time to time, i'm not used to it. my main source control tool, is TFS

**Comment by TeoTwawki** [comment]
I'm a tortoisegit user most days. Sometimes command line for the "fun stuff".

If such a thing existed, Gits like the opposite of deep learning - its a robotic idiot that tried anything it thinks we told it, even if that was kinda impossible. "Ok boss!" *watches world burn*

**Pull request closed without merging**
