### PR TITLE
ZM8 bcnm blackscreen fix

### PR DESCRIPTION
**Pull request by Sacshop**
Input the proper event ID for winning the bcnm.

### CODE REVIEW

**Comment by teschnei** [comment]
hm, I doubt that this is the only bcnm in the game that doesn't use a cs in the 32000 range, is this from retail?

**Comment by Sacshop** [comment]
Yes - this would make it 100% retail accurate and no longer just leave you at a black screen upon winning.

**Comment by teschnei** [comment]
so just to confirm - you went on retail, capped the packet, and that is what the csid was

**Comment by Sacshop** [comment]
No - let me do that now then ~

**Pull request closed without merging**
