### PR TITLE
dont calculate distance where there is none to be calculated

### PR DESCRIPTION
**Pull request by xdemolish**

### CODE REVIEW

**Comment by teschnei** [comment]
why?

**Comment by xdemolish** [comment]
cause checking distance on self triggered me

**Comment by teschnei** [comment]
is it actually a problem?  have you profiled it?

**Comment by xdemolish** [comment]
lolno that's what we have @Scavenge for

**Comment by teschnei** [comment]
closing until it's proven to fix an issue

**Pull request closed without merging**
