### PR TITLE
Changed Wildfire to calculate as magic damage

### PR DESCRIPTION
**Pull request by Fr0zt**

### CODE REVIEW

**Comment by teschnei** [comment]
need to do a revision on the doMagicWeaponskill function since Wildfire's dSTAT is AGI - INT (not INT - INT) and I guess the club ones are probably MND as well

**Comment by TeoTwawki** [comment]
@teschnei  Shining Blade and Seraph Blade would be MND too

**Comment by maxtherabbit** [comment]
do you want to just add a dSTAT parameter to doMagicWS() like we have with applyResistance() ?

**Comment by teschnei** [comment]
That or use params to send the stats (that way we can do int-int default
and not have to change them all. Then again, there's not that many..
Anyways, I prefer params over another arg though. That's what its for, not
bloating args

**Pull request merged**
