### PR TITLE
Su fix

### PR DESCRIPTION
**Pull request by Skanless**
Wanted to go into the src\maps\packets\char_stats.cpp to ad in 
WBUFB(data,(0x52)) = 2;

### CODE REVIEW

**Comment by TeoTwawki** [comment]
Hilarious as the commit log here is, you need to rebase onto darkstar master, and next time start with a clean branch that is 1:1 with darkstar master.

**Comment by TeoTwawki** [comment]
I'm not gonna be around much this week, so I summon @takhlaq to show you the ropes.

**Comment by maxtherabbit** [comment]
also we intentionally didn't hardcode the superiority value into the packet because it's not retail accurate

so this doesn't need to be in trunk anyway

**Comment by TeoTwawki** [comment]
Oh.. I didn't even catch that. just saw the many many many commits and knew somethin went terribly wrong

**Pull request closed without merging**
