### PR TITLE
SQL: Add in some sublinking groups

### PR DESCRIPTION
**Pull request by Hozu**
-Added sublinking groups for: Lamia/Merrow and two Imp families. Added NMs in a different family to their intended families (Gurfurlur, Medusa/Experimental Lamia, Mahjlaef the Paintorn, Brass Borer and Achamoth, Cheese Hoarder Gigiroon, and Verdelet).
-Corrected the nameflag for Gurfurlur.

Edit: Ignore anything about mdt stuff in the comments, I removed it from the pull and made an issue about it.

### CODE REVIEW

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/search?l=cpp&q=MOD_DMGMAGIC&utf8=%E2%9C%93

?

**Comment by Hozu** [comment]
Looks like someone didn't update that comment when they redid all xdt stuff.

**Comment by TeoTwawki** [comment]
http://ffxiclopedia.wikia.com/wiki/Calculating_Magic_Damage#Target_Magic_Damage_Adjustment according wiki it never should have been changed, whoever was before you done goofed. Also betting all the shell spells are messed up on amounts and/or applying incorrect modifier.

**Comment by Hozu** [comment]
I'm removing the mdt% changes until we figure out how they should be handled.

**Comment by TeoTwawki** [comment]
I suggest toss them into a 2nd PR and if project doesn't care about the precision someone else removed then your change should be merged so that things don't have higher damage reduction than they should at least. I remember IRC discussions about the precision before but didn't recall what became of it. Looks like it was only partly changed.

**Comment by TeoTwawki** [comment]
If anyone was confused by our exchange here, there isn't a problem with merging this. He split the other thing we were discussing from this anyway.

**Pull request merged**
