### PR TITLE
SCRIPTS: Added Summon Skill P.Acc. Bonus

### PR DESCRIPTION
**Pull request by Zenny89**
Summoning magic should add 1 Accuracy per level over the cap: http://ffxiclopedia.wikia.com/wiki/Category:Summoning_Magic

### CODE REVIEW

**Comment by teschnei** [comment]
that's a weird place to put it - why don't you add it to the avatars base acc when they are summoned (ie. where the merit acc is)?  you can't realistically expect the summoning magic skill level to change dramatically while an avatar is out, right?

**Comment by Zenny89** [comment]
Sorry, it only applies to BPs - left that part out.

**Comment by Hozu** [comment]
Various equips give skill, so it can change whenever the player feels like it.

**Comment by teschnei** [comment]
oh duh, never mind me

**Pull request merged**
