### PR TITLE
SQL:item_basic adjusted flags to match polutils value

### PR DESCRIPTION
**Pull request by Ninjistix**
As title said adjusting flags to match polutils value, added some missing items

### CODE REVIEW

**Comment by Ninjistix** [comment]
I only made it to item 500 so far.. should i keep going or wait? @TeoTwawki  @xdemolish @bendangelo

**Comment by bendangelo** [comment]
Just wait, or put your other changes into an other pull request.

**Comment by Ninjistix** [comment]
I'm going over the whole, item_basic file adjusting the flags and adding missing items... will eventually have to do diff pull requests for this.. not sure how long it will take me

**Comment by bendangelo** [comment]
Thanks for contributing :heart:

**Pull request merged**
