### PR TITLE
Ability changes

### PR DESCRIPTION
**Pull request by nesstea**
Allows steps to consider the mythic Terpsichore.

### CODE REVIEW

**Comment by maxtherabbit** [comment]
why not just do 

player:addStatusEffect(EFFECT_FINISHING_MOVE_1+daze + player:getMod(MOD_STEP_FINISH),1,0,7200);

and do away with the modifier variable?

**Comment by nesstea** [comment]
If I was going to change it, I'd rewrite the whole thing. I was going to just add one to the daze variable, but the daze variable is being set again in the nested sluggish daze if-thens.

**Comment by teschnei** [comment]
you're better off getting rid of the variable and tacking on the getMod to the "daze" variable in the first half of the script (except when the target has max daze already), and then capping daze in the second half of the script - the way its currently written isn't really extensible and will break if there are more than one source of the mod

**Comment by nesstea** [comment]
ok but there is only one source of this mod. are you talking about future content?

**Comment by teschnei** [comment]
yes, i am always keeping future content in mind (as the proper developer should)

**Comment by nesstea** [comment]
Ok I'll do that today.

**Pull request closed without merging**
