### PR TITLE
Item Weapon changes v1

### PR DESCRIPTION
**Pull request by Ninjistix**
fixed multi-hit, added missing weapons

### CODE REVIEW

**Comment by Ninjistix** [comment]
messed-up something will repost

**Comment by R3P0FFXI** [comment]
@Ninjistix You don't need to open and close the request, if you made a mistake just amend a previous commit and it will go through the process of recertifying again automatically.

**Comment by Ninjistix** [comment]
@R3P0FFXI was trying to squash them as @bendangelo suggested, so there wouldn't be so many commits.. but messed-up somewhere

**Comment by xdemolish** [comment]
doesn't matter, force push rewrites the history
@teotwawki does it all the time :)

**Pull request closed without merging**
