### PR TITLE
Scripts: Tenzen's Path KI bug fix + Sea requirement check

### PR DESCRIPTION
**Pull request by Hozu**
-Made the ??? in Batallia Downs check for the progress before and after the defeat of the Disaster Idol. This is because you don't have to defeat it again if you forgot to get the KI. Currently, if you defeat the NM, you are stuck unable to get the KI.
-Changed the requirements to use various Sea stuff from KI Light of Al Taieu to CoP current mission is past The Warrior's Path. The KI is not Sea access, as you are supposed to lose it at some point, and only one race is to get it back. However, I'm not sure when the loss is supposed to happen, so I left that out.

### CODE REVIEW

**Comment by Hozu** [comment]
This fixes #2034.

**Comment by xdemolish** [comment]
is it supposed to give the keyitem to anyone who's completed warrior's path? cause the way you've got it now it does

**Comment by Hozu** [comment]
Hm? The only thing I changed about being given the KI for the one Tenzen's path thing is allowing for the progress var being 6 or 7 instead of just 6. It's set to 6 from the first CS at the ???, and set to 7 when the NM is killed if it's at 6.

The other changes merely replaced checking for the Light of Al'Taieu to checking for CoP mission past The Warrior's Path.

**Comment by xdemolish** [comment]
whatever

**Pull request merged**
