### PR TITLE
Dancer Steps - Mythic changes

### PR DESCRIPTION
**Pull request by nesstea**
Allow Terpsichore to augment steps as the wiki states.

### CODE REVIEW

**Comment by teschnei** [comment]
don't open a pull request before testing :\

**Comment by nesstea** [comment]
I did on my server. forgot to save the changes. missed a )

**Comment by teschnei** [comment]
also, a dnc main with terpsichore with this code and 3 finishing moves will get lethargic daze instead of finishing move 5

**Comment by nesstea** [comment]
1 second. My git is having a hayday.

**Comment by nesstea** [comment]
You are correct. My logic was fubar. Changing now.

**Comment by teschnei** [comment]
just do local daze = 1 + getMod(whatever);

then on the specific cases you can cap it if it needs to be capped

(cap of 2 at 3 step, cap of 3 at 2 step, cap of 4 at 1 step)

**Comment by nesstea** [comment]
I will have to do that later tonight. Want me to close the pull until it's done and tested?

**Comment by teschnei** [comment]
ya

**Pull request closed without merging**
