### PR TITLE
Made GoV prowess buff behave more retail (only lost on zoning out, not from dc or even logoff).

### PR DESCRIPTION
**Pull request by TeoTwawki**

### CODE REVIEW

**Comment by TeoTwawki** [comment]
(Apologies for repeat, I engrished the hell out of initial comment).
I think we still need the behavior of needToZone() changed to not trigger on re-logging or getting dc'd, and then I think issue #297 can be closed (although the flag for zone still also trips on logging out or dc, really should be 2 diff flags).

The places needToZone() is already used at will be or are perfectly retail if this is done. Unless that was already changed and I didn't notice, we're already all set. Last I knew it was still triggering on entering game.

**Comment by teschnei** [comment]
Now that the server can differentiate logging in and zoning again, it
shouldn't be any work at all (just have to figure out how needtozone works
in the first place)

**Comment by TeoTwawki** [comment]
@teschnei related: I was just helping gedads test something, and found out that if trip cs during login that retail only has happen on zone in, you crash out the client. So I guess we need to preven cs in onZoneIn from happening when its a login as well.

**Comment by TeoTwawki** [comment]
ok..Shits broken that I did not touch in this pull request, but make sthsi pull request 100% useless. Not one word about testing. There is no way this should have failed and a simple flag change shouldn't need to be tested rigorously: I set the effect flags so that it would NOT be removed form zoning, since that trips on login, and then manually removed the effects in player.lua ONLY when an actual zone occurs, since that is the only way to tell them apart right now. That should have worked fine. Except the #$%^&ing server is STILL removing effects that are not flagged to be removed.

**Pull request closed without merging**
