### PR TITLE
CORE: issue #367

### PR DESCRIPTION
**Pull request by maxtherabbit**

### CODE REVIEW

**Comment by teschnei** [comment]
i dont think thats right, pretty sure resisted spells still generate enmity (like bind etc)

should double check what tookEffect does

**Comment by teschnei** [comment]
also a cure probably still aggroes the mob (it must generate at least 0 enmity)

**Comment by maxtherabbit** [comment]
with this change, resisted spells will still generate enmity unless they are cures

the condition is if !isHeal() *or* tookEffect()

**Comment by maxtherabbit** [comment]
and in the comments of #367 you said the cure doesn't aggro the mob so I'm lost now

**Comment by teschnei** [comment]
yes, that's why i wanted to check what tookEffect actually does (because tookEffect was not in this conditional before)

if i said that after testing it, then that's probably right

**Comment by maxtherabbit** [comment]
all tookEffect does is test the spell action message

**Comment by maxtherabbit** [comment]
wait I think I get what you're saying now... if you cast cure on an undead and it resists it should still generate enmity? I can change that, you were just confusing me talking about resists b/c when you cure a non-undead the message is "no effect"

**Comment by maxtherabbit** [comment]
better?

**Comment by teschnei** [comment]
yeah, but other things do "no effect" and should claim and generate enmity as well

**Comment by maxtherabbit** [comment]
uh they do already don't they? the conditional I added tests true for all spells that aren't cures so it wouldn't affect other spells that have no effect

**Pull request merged**
