### PR TITLE
DATABASE/SQL: Mamool Ja's Raptor Respawn Time

### PR DESCRIPTION
**Pull request by Zenny89**
Changed the respawn time for Mamool Ja's Raptor to 0 from 300 like the other pet mobs. Currently, this mob takes 5 minutes to respawn despite the Stabler summoning

### CODE REVIEW

**Comment by xdemolish** [comment]
gotta change the actual commit's message (not the same as the pull request title)

amend last commit > change message > force push to remote branch > dun

**Comment by Zenny89** [comment]
Did that accomplish what you requested?

**Comment by teschnei** [comment]
looks like you made a second commit to undo your first commit

**Comment by teschnei** [comment]
on the command line, use "git rebase -i"
then, use that to delete your second commit and change the commit message of the first one

**Comment by Hozu** [comment]
FYI after you submit another commit you have to comment so the devs can see, apparently.

**Comment by Zenny89** [comment]
Okay, thanks Hozu. Updated with suggested changes.

**Pull request merged**
