### PR TITLE
add jobs table to dsp object

### PR DESCRIPTION
**Pull request by wrenffxi**

### CODE REVIEW

**Comment by TeoTwawki** [comment]
I don't suppose you'd like to volunteer to do the keyitems later too? 😅

**Comment by takhlaq** [comment]
no dont bother, i can write something up later to table the rest of the globals (probably just dsp.FILENAME.var)

**Comment by TeoTwawki** [comment]
k

**Comment by takhlaq** [comment]
actually, lets just do it manually (i failed)

**Pull request merged**
