### PR TITLE
Bastok mission

### PR DESCRIPTION
**Pull request by Turttle**
Bastok Mission Patch 1, related NPC Naji, Halvier, Baraka, Helaku,
Kupipi, Melek, Gold Skull, Uu Zhoumo, Makarim. Related Missions Bastok
1-1, 2-1, 2-3, 5-1, 6-2.

### CODE REVIEW

**Comment by xdemolish** [comment]
tabs > 4 spaces

**Comment by Turttle** [comment]
Missing extra dialog from ambassy NPCs.

**Comment by xdemolish** [comment]
add it then

**Comment by TeoTwawki** [comment]
> tabs > 4 spaces

Well you are doing that, if you could change `if(` to `if (` I would appreciate that

**Comment by Turttle** [comment]
i will reopen once i sort out the windy NPCs CS

**Pull request closed without merging**
