### PR TITLE
[SCRIPT] Imp defense and horn-breaking AI

### PR DESCRIPTION
**Pull request by nesstea**
You can now break horns! This isn't all the imps in the game, but should be plenty enough until the others need coding/AI.

### CODE REVIEW

**Comment by nesstea** [comment]
I missed the non-versioned files.

**Comment by bendangelo** [comment]
There are two imp families but you are only checking for one. Should you check for both families?

**Comment by Hozu** [comment]
Aren't Imps able to pull out another horn after some period of time?

**Comment by nesstea** [comment]
not that I recall.

**Comment by bendangelo** [comment]
Thanks

**Pull request merged**
