### PR TITLE
Gathweeda guildshop entry

### PR DESCRIPTION
**Pull request by Scavenge**
Added minium and a few other items on gathweega and gave him a lua, also added the same new items to wahraga as well, since i took his stock in the first place

### CODE REVIEW

**Comment by mspyerzuka** [comment]
Warp is using magic so it doesn't count!

**Comment by teschnei** [comment]
Importing guild_shops.sql into the database...ERROR 1062 (23000) at line 1748: Duplicate entry '60425-4443' for key 'PRIMARY'

**Comment by Scavenge** [comment]
yea i just changed that before submitting, i must not have reloaded the page or something

**Comment by Scavenge** [comment]
oh it's the one on wahraga woops

**Comment by Scavenge** [comment]
should be good now..

**Comment by xdemolish** [comment]
rebase/squash

**Pull request closed without merging**
