### PR TITLE
Fix loops on Panzerfaust and Stormwind

### PR DESCRIPTION
**Pull request by ymkc**
unfortunately not 100% matching retail, as they do not continue the chain when they have to catch up to PC. but still way better than an infinite loop

### CODE REVIEW

**Comment by teschnei** [comment]
what was wrong with the old way?

**Comment by ymkc** [comment]
i never saw it work, mobs always got stuck in a loop when using them
and just moved despots panzerfaust part into the mob's lua to make it better visible

**Comment by teschnei** [comment]
Yeah, moving it to the mobs lua is good.  Is mob:actionQueueAbility() always returning false?  That should be fixed if it is rather than working around it.

**Comment by ymkc** [comment]
i think it is

**Comment by teschnei** [comment]
I think I'll just get rid of it, actually.

Can you fix horrid roar too? horrid_roar_3.lua (it's the only thing other than panzerfaust/stormwind using actionQueueAbility)

**Comment by ymkc** [comment]
sure, will do

and is there a way to check whether an mobskill was successfully executed?
maybe add a listener on WEAPONSKILL_STATE_EXIT?

**Comment by teschnei** [comment]
this is for repeating the move if it wasn't executed successfully?

**Comment by TeoTwawki** [comment]
whether it lands or not, according to issue #3196

**Comment by TeoTwawki** [comment]
err, sorry, think I misunderstood

**Comment by ymkc** [comment]
yes, to mimic retail

**Pull request merged**
