### PR TITLE
Corrected #3795 Ashu Talif Captain to be killable after he jumps down.

### PR DESCRIPTION
**Pull request by nyczducky**
Also allows for Gessho to start casting on captain.

### CODE REVIEW

**Comment by nyczducky** [comment]
Seems that when Gessho engages the crew first, the captain proceeds to attack Gessho and then becomes untargetable.

**Comment by teschnei** [comment]
Isn't he supposed to give up? Not be killed?

On Mar 14, 2017 2:16 PM, "nyczducky" <notifications@github.com> wrote:

Seems that when Gessho engages the crew first, the captain proceeds to
attack Gessho and then becomes untargetable.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/DarkstarProject/darkstar/pull/3803#issuecomment-286546022>,
or mute the thread

**Comment by nyczducky** [comment]
Yes. That check is there. Maybe I misinterpreted unkillable.

**Comment by teschnei** [comment]
if that check is there, then what is this doing?

if he gives up at 20%, what difference does making him killable do?

**Pull request closed without merging**
