### PR TITLE
implement eagle eye shot

### PR DESCRIPTION
**Pull request by xdemolish**
tested and werks but fkifiknow if its retail

### CODE REVIEW

**Comment by xdemolish** [comment]
also the ability damages before bow is even drawn in animation

**Comment by teschnei** [comment]
i already did the EES script though!

**Comment by xdemolish** [comment]
gdi kayjay as if i ever check commits

**Comment by teschnei** [comment]
my script didn't do anything with OnAbilityCheck though, so I think that might be needed

**Pull request closed without merging**
