### PR TITLE
Added binding onWeaponskillHit to trigger mob script things when a player or pet uses TP on a mob, per discussion with Kjlotus…

### PR DESCRIPTION
**Pull request by TeoTwawki**
…. Tested with bst jug pets and smn avatars.

Modeled function on the existing onMagicHit, including some quirks that has. Which I intend to iron out later. This works though.

### CODE REVIEW

**Comment by TeoTwawki** [comment]
May wanna leave this till Kj sees it, in case he wants me to change something. I know he's away for awhile and I can wait/rebase if needed.

**Comment by teschnei** [comment]
can leave out the kukulkan script? i know it's commented out but there's like 3 things wrong with it and it's pretty much guaranteed to change once abyssea is actually looked at properly

**Comment by TeoTwawki** [comment]
Sure but can you tell me what was wrong in IRC later? I just wanted to leave an example for when ppl actually try to use this.

**Comment by TeoTwawki** [comment]
@teschnei Script removed as requested.

**Pull request merged**
