### PR TITLE
more zone list stuff

### PR DESCRIPTION
**Pull request by TeoTwawki**
Updated the documentation file, sql table, and gave the new area a default position and accurate basic text IDs.

### CODE REVIEW

**Comment by starlightknight** [comment]
@TeoTwawki can you also update the batch properties for the new zone?

**Comment by TeoTwawki** [comment]
@starlightknight it doesn't have any mob or npc entries yet, but I added
```
277=scripts/zones/RaKaznar_Turris/
```
to the zone mappings and got distracted before pull requesting (getting it done now).

**Comment by gedads** [comment]
@TeoTwawki
for npcs  -> look @ z 277
for mobs, all actual mobs are already added, it's the last soa mission bcnm area
-- --------------------------------------------------------------
-- Z 277 Kaznar Turris
-- --------------------------------------------------------------

INSERT INTO `mob_spawn_points` VALUES (17911809,'Hadesv1','Hades',0,720,-406,480,0);
INSERT INTO `mob_spawn_points` VALUES (17911810,'Arciela','Arciela',0,748,-406.5,478,128);
INSERT INTO `mob_spawn_points` VALUES (17911819,'Hadesv2','Hades',0,720,-406,480,0);
INSERT INTO `mob_spawn_points` VALUES (17911820,'Arciela','Arciela',0,748,-406.5,478,128);
INSERT INTO `mob_spawn_points` VALUES (17911821,'Theodor','Teodor',0,748,-406.5,482,128);

**Comment by TeoTwawki** [comment]
The other pull req for utils hasn't been merged yet, I'll update it.

**Pull request merged**
