### PR TITLE
Stable fix back into master

### PR DESCRIPTION
**Pull request by TeoTwawki**
......

### CODE REVIEW

**Comment by TeoTwawki** [comment]
hey @lyptt ? pr to master in the future, not stable, I didn't even see it till it was too late.

**Comment by lyptt** [comment]
@TeoTwawki sure, no worries! I wasn't sure what the branching strategy was for this project so I just branched off what I'm using on my own machine.

**Comment by TeoTwawki** [comment]
I would rather we sent bug fixes to both branches, but we haven't got the manpower to deal with it like that, so we just throw everything to master and periodically merge to stable before rebuilding the installer.

**Comment by lyptt** [comment]
Okay cool, I'll do the latter in future 🙂

**Pull request merged**
