### PR TITLE
Chocobo Digging rewrite

### PR DESCRIPTION
**Pull request by wrenffxi**
Added DIGGING_RATE setting.
Moved all digging rewards into the global script.
Added weighted reward selection (weight do not need to sum to 1000).

### CODE REVIEW

**Comment by TeoTwawki** [comment]
in muh zone files, pwning muh customz with minor edit conflicts...

**Comment by wrenffxi** [comment]
I didn't remove chance to skillup on failed dig.  The skillup check is outside of the pass/fail conditional.

**Comment by Xaver-Entropia** [comment]
rechecked, >< my bad wren.

**Comment by TeoTwawki** [comment]
Ok good. I'm on mobile at work so I couldn't even see the code today

**Pull request merged**
