### PR TITLE
Lieutenants Sash Effects

### PR DESCRIPTION
**Pull request by dwn134**

### CODE REVIEW

**Comment by TeoTwawki** [comment]
whats retail do if used when there is no effect to remove?

**Comment by dwn134** [comment]
Hmm. I havent had retail experience in over 10 years

**Comment by Wiggo32** [comment]
Nothing:
sash1
We use the sash, but remove no food:
sash2

**Comment by TeoTwawki** [comment]
So it *does* waste the charge then, so we won't need any `onItemCheck()` extras for a fail message. Thanks.

**Comment by TeoTwawki** [comment]
err.. no, your before and after both show 99 charges. So we need..to silently exit?

**Comment by dwn134** [comment]
Was it 100 when 1st used and the screen shot shows 99 now so it did use a
charge?

**Comment by Wiggo32** [comment]
It *did* use a charge... rather immediately upon use before casting was finished. You can see the text right above the "Damisha uses..." message where I had *just* obtained it. Hope they didn't give me one with a charge missing already, I'd be miffed.

**Comment by TeoTwawki** [comment]
ok, thanks. got confused because both screencaps has 99/100

**Comment by KnowOne134** [comment]
So looks to be all in order then. Uses charge regardless of having food
effect of not

**Pull request merged**
