### PR TITLE
merge exodus with dsp

### PR DESCRIPTION
**Pull request by Alice5150**
for some fuckin reason

### CODE REVIEW

**Comment by nesstea** [comment]
Best merge ever :P

**Comment by Alice5150** [comment]
I'm still learning! lol

**Comment by teschnei** [comment]
I'll think about writing an update guide later if it'll help

**Comment by Alice5150** [comment]
This one was actual very helpful, I'm pretty on top of it now: https://forums.dspt.info/viewtopic.php?f=11&t=2568

**Comment by Alice5150** [comment]
Is there a way to delete this? It's closed, but...

**Pull request closed without merging**
