### PR TITLE
SMN Pet Bodyguard behavior fix

### PR DESCRIPTION
**Pull request by thedraked**
Fixes original implementation of SMN Pet Bodyguard behavior.

### CODE REVIEW

**Comment by takhlaq** [comment]
need you to squash and rebase
as for the actual code/behaviour i guess @teschnei can take a look once you've rebased

**Comment by thedraked** [comment]
I do not know what "need you to squash and rebase" means.

**Comment by takhlaq** [comment]
http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html
and then force push

**Comment by TeoTwawki** [comment]
If your a tortoisegit user they made it easy. Right clock show log ctrl+click commit you want to squash together, right click and select "combine".

If you add darkstar/master as a remote, rebasing becomes easy too. you show darkstars log instead of your local copy log, then right click the commit you want rebased onto. "rebase onto this". Bam done.

**Comment by thedraked** [comment]
lol, well I just made things worse.  I cant figure this stuff out at all.  I got enough on my plate atm and give up, thanks anyway!  Closing

**Comment by RunAwayDSP** [comment]
https://github.com/DarkstarProject/darkstar/pull/3538

**Pull request closed without merging**
