### PR TITLE
Fixed Dark and Light arts not correctly increasing skill levels for…

### PR DESCRIPTION
**Pull request by UnknownX7**
…jobs with less than E skill

### CODE REVIEW

**Comment by Hozu** [comment]
What does this commit change the skill levels to? https://github.com/DarkstarProject/darkstar/issues/2764 has data of what the value should be at minimum, gathered from retail.

**Comment by teschnei** [comment]
I think it's just fixing a bug of using MJob instead of MLevel

**Comment by Hozu** [comment]
Ah. I checked the various formula against the data, and it mostly lines up. Largest error is +/-1, and none of the levels divisible by 10 (except 70), 75, and 76-99 are wrong, so it's more or less correct. Accurate for level-capped content, unless there's a 70 cap thing I'm forgetting about.

**Comment by UnknownX7** [comment]
> I think it's just fixing a bug of using MJob instead of MLevel
This is correct.

**Pull request merged**
