### PR TITLE
Update some issues with DNC Horos gear

### PR DESCRIPTION
**Pull request by helixhamin**

### CODE REVIEW

**Comment by helixhamin** [comment]
I used the 
`    AMNESIARES                = 253, // Enhances "Resist Amnesia" effect`
from modifier.h file, but it mentions at the top of that section:

>     // Resistances to enfeebles - Traits/Job Ability

So not sure if this is correct. If not, then there is no gear resist amnesia enabled, since the 253 mod is the only amnesia mod.

**Comment by TeoTwawki** [comment]
Gear use the same mod as traits there.

**Comment by helixhamin** [comment]
Sooo, all good then?

**Comment by TeoTwawki** [comment]
Good cept for dupe and the potentially confusing to the next person commenting.  Just put what the mod is, like all the pre-existing comments do. And if you click "details" travis says what it broke on https://travis-ci.org/DarkstarProject/darkstar/builds/201417009#L2384

**Comment by helixhamin** [comment]
@TeoTwawki Yep, checked travis, figured it out. Was supposed to integrate the item id by 1...

I also removed the extra comment and left it as just the mod effect note.

**Comment by TeoTwawki** [comment]
"Should also get mp+19" Should? are you not sure or what lol

**Comment by helixhamin** [comment]
o.O
Should as in "The sources confirm they should get it, but it was not originally in the script, so I included and noted".
I will change to just the value and drop the other part.

**Pull request merged**
