### PR TITLE
Added enable caskets and droprate multiplier to settings.lua

### PR DESCRIPTION
**Pull request by Omnione**
This is a prerequisit of the future addition of caskets, it will do nothing right now.
Added the ability to enable caskets through settings and also the abilty to adjust base droprate of caskets through a multiplier if so desired.

### CODE REVIEW

**Comment by Omnione** [comment]
I don't think travis likes me lol, 2 lines changed and he died

**Comment by ibm2431** [comment]
Don't need `ENABLE_CASKETS` if `DROP_RATE` is 0~!

**Comment by TeoTwawki** [comment]
as IBM is pointing out, we can default to what we think the retail rate is and check for 0 to disable it rather than making the setting itself a multiplier,

**Comment by TeoTwawki** [comment]
I also don't see why you are preemptively pr'ing the setting before it really exists

**Comment by Omnione** [comment]
tbh I don’t know why I pr’ed this first, close it if you want, I’ll include it when I actually feel brave enough to pr the global script, in regards to the enable caskets setting, I was using that to mainly disable the mixins from being added to mobs if it’s turned off, unless it’s not a problem letting the mixins being added to every mob in 59 zones if you don’t want caskets.

**Comment by Omnione** [comment]
Gonna close this, no point in it being PR'ed yet, sorry for doing that, and i have taken the advice onboard and going to remove the enable caskets setting and go with the setting rate to 0 to disable.

thanks everyone for commenting

**Pull request closed without merging**
