### PR TITLE
Bastok 2-3 patch

### PR DESCRIPTION
**Pull request by Turttle**
Baraka gives a missionStatus of 7.5 if you talk to her to start second
part of the mission. If starting the mission, part 1, then is ok.

### CODE REVIEW

**Comment by xdemolish** [comment]
honestly, it'd be a lot easier to just rewrite all the missions
especially considering the amount of times these mission vars need 'fixing'

**Comment by Turttle** [comment]
I agree. Could do something like i did with with Halvier.

**Comment by teschnei** [comment]
Missionstatus is an integer, 7.5 will just get truncated to 7

**Comment by Turttle** [comment]
had a player on that mission and the 7.5 went to a 8, idk why had to set manually his variable to 7.

**Comment by xdemolish** [comment]
it's not worth trying to figure it out, there are too many npcs involved in this mission and a lot of missionstatus derpage

i vote: close this pull request and rewrite the mission from scratch

**Comment by Turttle** [comment]
Ok.

**Comment by xdemolish** [comment]
you only need to rewrite the missions you feel like fixing, someone else can fix the others when they decide to submit a variable fix :p

**Pull request closed without merging**
