### PR TITLE
Added NM Ankou and fixed Lamina familyID and skill_list to reflect retail

### PR DESCRIPTION
**Pull request by Fiocitrine**
Added dis' fo' and his drop Astaroth cane.

### CODE REVIEW

**Comment by teschnei** [comment]
you didn't flag the mobtype as a NM, and it doesn't look like you're using the right spell list

**Comment by Fiocitrine** [comment]
didn't pass again?

**Comment by xdemolish** [comment]
click the build that failed > view log > scroll to the bottom
```
Importing mob_groups.sql into the database...ERROR 1062 (23000) at line 12111: Duplicate entry '14336' for key 'PRIMARY'
```

**Comment by Fiocitrine** [comment]
unsure if this is what the check is looking for?

**Comment by xdemolish** [comment]
synthax is now correct, i'll let kayjay or lauty look over this cause retail

**Comment by bendangelo** [comment]
:+1: it looks good

**Comment by Fiocitrine** [comment]
I did notice and issue with my test server. He's not spawning properly. I gave him a 1 hr repop. So far he no showy.

**Comment by teschnei** [comment]
you have the spawntype set to scripted (128), which means it won't spawn unless a script spawns it

**Pull request closed without merging**
