### PR TITLE
Version update dec2017/NpcId Shifts & Lua Stable branch

### PR DESCRIPTION
**Pull request by dragonarmor**
Rebased for Stable branch

### CODE REVIEW

**Comment by TeoTwawki** [comment]
okaaaay. Tomorrow I can just rip the commit(s) and manually fix this if you'd like. you seem to he having a bad time with it. Suggest sacrificing a few taru's to the ffxi gods.

**Comment by dragonarmor** [comment]
I guess so because I am doing nothing different than I normally do. why all those merge commits is beyond me.

**Comment by TeoTwawki** [comment]
well I'd hazard a guess that your forks stable branch isn't lining up with your local copy and either would get that little error on tortoise that prompts most users to mistakenly pull when you really needed a force push, or local copy just didn't get rebased correctly before pushing to it.

but I can't really say.

**Comment by TeoTwawki** [comment]
@dragonarmor just to give you an update I tried to handle it over xmas and this happened: #4419

The git gawds have forsaken us dude.

**Comment by TeoTwawki** [comment]
we fixed by merging master to stable the other night

**Pull request closed without merging**
