### PR TITLE
[ZNM]Sarameya - Lower MEVA slightly

### PR DESCRIPTION
**Pull request by nesstea**
It's way too high.

### CODE REVIEW

**Comment by bendangelo** [comment]
Does this mob have high resistance to magic? With that much magic resistance it'll be very hard to nuke.

**Comment by nesstea** [comment]
Yes. It's supposed to be very resistant to magic.

**Comment by nesstea** [comment]
RIP Travis

**Comment by bendangelo** [comment]
I'll just merge this in.

**Pull request merged**
