### PR TITLE
Version update 2017/04/04 (client: 30170329_0)

### PR DESCRIPTION
**Pull request by ibm2431**
Requesting that this update from March->April gets PR'ed into master, prior to the update up to May @TeoTwawki mentioned in #3882 (which would be March->May), so that commit log has a history of what changed March->April, and then April->May.

Sorry if this would cause you to have to do a rebase, Teo. D:

### CODE REVIEW

**Comment by TeoTwawki** [comment]
That actually isn't necessary, and is gonna confuse my minions and when confused ppl tend make mistakes get frustrated and give up on things.

**Comment by TeoTwawki** [comment]
I'd rather we didn't bother up obsoleted updated just to have extra client revisions in history (unless your server needs that revision)

**Comment by TeoTwawki** [comment]
Just a heads up I am prolly gonna merge this afterall things seem to have already gone sideways with the work in progress so I''l re-sync it to the next client myself,

**Comment by TeoTwawki** [comment]
@ibm2431 so get this, not a single text ID changed since your revision to the current client. NONE. The only text ID's I found changed that weren't in your PR were caused by the default paths in the tool missing their ending slash. Maybe I'll be lucky and the same is true for npc IDs (I can dream right?)

**Comment by ibm2431** [comment]
Oh, just got the chance to check the internet (access is very sporadic), glad it was of help.

You shouldn't have any changes to NPCs other than in Legion~! Those have changed every month. Usually just shifts every NPC in the zone up or down a few IDs as SE adds/removes Ambuscade mobs from month to month.

I haven't seen any other zones (truly) shift in a long time, despite what the tool might like you to believe for a few of them. Feel free to ignore it on things like Apollyon chests, Shadow Lords in Throne Room, etc.

**Comment by TeoTwawki** [comment]
thanks, @Heepster03 is double checking for me before I bump the version check again

**Pull request merged**
