### PR TITLE
SQL: Added modifiers for Asn. Armlets +2, Raid. Poulaines +2, Toro Cape, Atheling Mantle, Friomisi Earring, Ifrit Ring +1, Shiva Ring +1, Mes. Haubergeon, Mes'yohi Slacks, and Cetl Belt

### PR DESCRIPTION
**Pull request by some1here**
SQL: Added modifiers for Asn. Armlets +2, Raid. Poulaines +2, Toro Cape, Atheling Mantle, Friomisi Earring, Ifrit Ring +1, Shiva Ring +1, Mes. Haubergeon, Mes'yohi Slacks, and Cetl Belt

### CODE REVIEW

**Comment by TeoTwawki** [comment]
> some1here wants to merge 1 commit into DarkstarProject:dev from some1here:dev

You appear to not either comprehend or just not listen to anybody.

**Comment by TeoTwawki** [comment]
You need something like:
> some1here wants to merge 1 commit into DarkstarProject:master from some1here:items

**Comment by some1here** [comment]
1. https://github.com/some1here/darkstar
2. https://github.com/some1here/darkstar/pulls
3. https://github.com/DarkstarProject/darkstar/compare/dev...some1here:dev

**Comment by TeoTwawki** [comment]
Please stop being a tard.

**Comment by TeoTwawki** [comment]
https://translate.google.com/?hl=en
would be better than your non communication, and thats saying something.

**Comment by TeoTwawki** [comment]
In any case, if you don't understand something that has been said, you need to say so.

**Comment by some1here** [comment]
my steps and I am sorry if I am wrong were 1, 2, 3

**Comment by TeoTwawki** [comment]
`DarkstarProject:dev` is wrong needs to be `DarkstarProject:master`

**Comment by TeoTwawki** [comment]
I do not mean to discourage, just got frustrated.

**Comment by some1here** [comment]
Its ok you can call me a stupid bastard from Legion I was Omg :P

**Pull request closed without merging**
