### PR TITLE
 SQL Job Points Player menu

### PR DESCRIPTION
**Pull request by some1here**
Right below merits is job points
some info is on https://www.bg-wiki.com/bg/Job_Points#Acquiring_Capacity_and_Job_Points
as well as
https://github.com/Windower/Resources/blob/master/lua/job_points.lua

### CODE REVIEW

**Comment by xdemolish** [comment]
Why do you consistently close and reopen pull requests as well as close and open a new one for the exact same change?
It's unnecessary since they update automatically and it just causes irc and email spam; it also means we have to review and comment on the newer pull request and repeat any feedback, which you seem to either flat out ignore or not be able to comprehend anyways.

**Comment by some1here** [comment]
pull-51 was on the darkstar master and would not close under commands.   This format some1here:master errors apron close.

**Comment by some1here** [comment]
I get:  All checks have failed
continuous-integration/appveyor — AppVeyor was unable to build non-mergeab

**Comment by nesstea** [comment]
what the hell...

just join the rest of us and use git.

**Pull request closed without merging**
