### PR TITLE
Modified steps to consider Terpsichore (mythic) augments.

### PR DESCRIPTION
**Pull request by nesstea**
Terpsichore adds a finishing move whenever you step.

### CODE REVIEW

**Comment by teschnei** [comment]
chances are if you write "getEquip" in your code anywhere you probably should have made a modifier


this is one of those cases

**Comment by nesstea** [comment]
Other gear enhances accuracy. There is a modifier for that. This is the only piece of gear that modifies steps in this way.

**Comment by maxtherabbit** [comment]
every time someone says that and hardcodes an item id check, retail releases more items with the mod and we end up having to redo it

**Comment by teschnei** [comment]
there are like 7 terpsichores in the game

you really want to have that check for 7 items?

**Comment by nesstea** [comment]
want me to close this pull and resubmit one with the mod?

**Comment by nesstea** [comment]
The mod is already coded and I'm derpy. I'll modify the abilities for the mod.

**Pull request closed without merging**
