### PR TITLE
Lu shang quest fixes

### PR DESCRIPTION
**Pull request by metalfiiish**
Fixed the issues with initial quest cutscene no passing carp item ID's as per issue:
https://github.com/DarkstarProject/darkstar/issues/4066

Updated both quest givers to give standard dialog after quest starts.

Updated both to utilize Demolish's new npc_utils:fishingAnimation.

NPC's have a minor issue where sometimes they don't fix their rotation (should turn back around after talking with a player). Talking with them again will fix it.

### CODE REVIEW

**Comment by metalfiiish** [comment]
The only lingering thing is now they turn around (face away from player) while talking to players during the initial cutscene to start quest. Other than that they are perfect.

**Comment by teschnei** [comment]
are they actually supposed to stop fishing on trigger?

for the event yes, since the event bugs out otherwise, but do you know for sure that the showText should have them putting their rod away?

**Comment by metalfiiish** [comment]
well showtext forces them to look at you with their fishing rod in your face, unless I am missing a param that tells them not to turn.

Trading them, they should not turn at all for sure.

**Comment by takhlaq** [comment]
looks like retail uses an event, and they're not supposed to turn around https://www.youtube.com/watch?v=Xz0yOPfjSQc

**Comment by metalfiiish** [comment]
Yep, then this PR so far looks to match retail, since the changes kj advised resolved thhat.

**Pull request merged**
