### PR TITLE
remove drawin from King Behemoth

### PR DESCRIPTION
**Pull request by KnowOne134**
can not find any info saying KB has a drawin effect

### CODE REVIEW

**Comment by godmode** [comment]
It is regional. Not a standard draw in but he will draw in if you have hate and are outside of the region.

**Comment by Delkathus** [comment]
He does have a draw in, i remember it vividly and it's why pld's had to kite with w.legs on retail.

**Comment by TeoTwawki** [comment]
We're aware his draw in Is currently not the right type but we're leaving it until are draw in is in.

**Comment by TeoTwawki** [comment]
Ahem let me amend what i just said

**Comment by TeoTwawki** [comment]
We are aware _multiple_ NM ate using the wrong type of draw in, but we've been allowing it until the correct type is implemented.

**Comment by KnowOne134** [comment]
Gotta. I couldnt find any info on it so thought was a mistake. Closing

**Pull request closed without merging**
