### PR TITLE
SQL: Dynamis currency drop/rate adjustment

### PR DESCRIPTION
**Pull request by Hozu**
-Dynamis Beastmen - 100s at 1% -> singles at 15%
-Dynamis Qufim Nightmare mobs have currency rates to match other Dreamlands zones (4 singles at 20%, 1 100 at 1%).
-Glacier Orc statue - 100 Byne Bill -> Montiont Silverpiece
-Added Jadeshell drop to Dynamis - Windurst NMs at same rate as the 100 from NMs in other cities

### CODE REVIEW

**Comment by Hozu** [comment]
Something interesting I noticed - ALL of the beastmen had a 100 in their drop pool, but only the Quadavs, Goblins, and Kindred actually dropped them. I have no idea why that is.

**Comment by TeoTwawki** [comment]
Ty Hozu <3

**Comment by Deadwing888** [comment]
<3

**Comment by R3P0FFXI** [comment]
<3 @Hozu Gogo piss off all the ppl doing dynamis

**Comment by Teromaximus** [comment]
The one and only reason Dynamis was made to take so long to upgrade a relic on retail was for the purpose of subscription fee +24. That's IT. To make it like that on small private servers like that is completely pointless. 

The game play should be as close to capturing the retail experience as possible, yes. But, some aspects of the retail experience was solely for monetary gain, and nothing else. Those aspects aren't necessary to capture the essence of the game. Even with the currency drop rate as it was before lowering it, it still takes a lot of work and effort to complete, and still has the feeling of accomplishment with it.

**Comment by Hozu** [comment]
If you disagree with the changes, have your custom server adjust the drops/drop rates. DSP's goal is to match retail, though it should be using Neo Dynamis, I suppose... Hopefully the old style of Dynamis will remain as an option.

**Comment by Arximiro** [comment]
Didn't want to post a new issue, however none of the beastmen and/or other mobs have been dropping 100's in City Dynamis. Only the NMs and stats drop them at all. In Beauc only the NMs and Eyes drop 100's. It could be a custom Nasomi fix but there is no way to know really.

Just thought I'd report it in case it's an issue with DSP. Either way it's pretty ridiculous on a low pop server to full clear a Dynamis and get 5 100's.

**Comment by Hozu** [comment]
That's intentional. Feel free to customize the drop rates for your own private server.

**Comment by Arximiro** [comment]
Ooops, my bad. I had read the top post as saying you changed beastmen to have a 1% chance to drop 100's and a 15% chance to drop singles. Now I see that you were saying you changed it from one to the other, apologies. Nasomi is probably using straight DSP if that's the case then.

Sad faces all around.

**Pull request merged**
