### PR TITLE
DATABASE: According to the wiki even though the aegis is a class 5 shield, it procs like a class 3 shield which should be about 50%.  This currently only handles the lvl 75 item.

### PR DESCRIPTION
**Pull request by dacrybabysuck**
DATABASE: According to the wiki even though the aegis is a class 5 shield, it procs like a class 3 shield which should be about 50%.  This currently only handles the lvl 75 item.

### CODE REVIEW

**Comment by teschnei** [comment]
pretty sure aegis already has 50% block rate and this is adding 50% more

**Comment by dacrybabysuck** [comment]
You're right. After looking through battleutils.cpp I see there's a special switch for it.  So we can ignore this pull request. Does it make sense to handle it from the db since there's a block rate mod, rather than having special cases in code?

**Comment by dacrybabysuck** [comment]
Does the mod just adjust the current is or is it setting the base. I guess that would make the difference.

**Comment by teschnei** [comment]
the block rate mod is for adjusting, for example reprisal

**Pull request closed without merging**
