### PR TITLE
Reversed some BCNM changes Tested on 5-1, Double Draconian

### PR DESCRIPTION
**Pull request by cowrevenge**
delPlayerFromBcnm -- Was missing, basically.

### CODE REVIEW

**Comment by cowrevenge** [comment]
Should be noted that I believe 5-1 still has an issue, along with some others. This has to do with the lua code and oneventfinish for specific CS id. I have a fix for that too, but its really a separate issue. It was not included here. If anyone has a list of bcnms/missions with that issue, I would be glad to create a simple fix for all of them.

**Comment by TeoTwawki** [comment]
Elaborate: 5-1 used to work as scripted, I want to know what exactly broke it.

**Comment by Hozu** [comment]
When the AI rewrite happened, 5-1 would occasionally not give the KI for the win. 2-3 is/was? the bigger problem, it would rarely play the winning CS.

**Comment by cowrevenge** [comment]
5-1   if (csid == 0x7d01) then

This line is not working. However, if you skip the dialog with this line
"player:startEvent(0x7d01,1,1,1,instance:getTimeInside(),1,0,1);" The 1 is the change.

then "if (csid == 0x7d01) then" works. 

oneventfinish does not work for 0x7d01. I wrote a code to created a new win variable that properly gives ki items, regardless of the cs reported. I think the cs id is changing when the cs is viewed instead of skipping it. 

I have not had an issue with 2-3.

**Comment by TeoTwawki** [comment]
[This? ](https://github.com/DarkstarProject/darkstar/blob/master/scripts/zones/QuBia_Arena/bcnms/rank_5_mission.lua#L37)

```lua
function onBcnmLeave(player,instance,leavecode) 
-- print("leave code "..leavecode); 
    if (leavecode == 2) then -- play end CS. Need time and battle id for record keeping + storage 
        if (player:hasKeyItem(NEW_FEIYIN_SEAL)) then 
            player:startEvent(0x7d01,1,1,1,instance:getTimeInside(),1,0,0); 
        else -- Gives skip dialogue if previously completed 
            player:startEvent(0x7d01,1,1,1,instance:getTimeInside(),1,0,1); 
        end 
    elseif (leavecode == 4) then 
        player:startEvent(0x7d02); 
    end 
 end; 
```

**Comment by cowrevenge** [comment]
the code you posted works, check below it for oneventfinish.

**Comment by cowrevenge** [comment]
I checked mission 2-3, and it is using similar code. 
function onEventFinish(player,csid,option)
-- print("bc finish csid "..csid.." and option "..option);
    
    if (csid == 0x7d01) then

**Comment by TeoTwawki** [comment]
> This line is not working. However, if you skip the dialog with this line
"player:startEvent(0x7d01,1,1,1,instance:getTimeInside(),1,0,1);" The 1 is the change.

> the code you posted works, 

I wasn'ty asking about the onEventFinish

**Comment by cowrevenge** [comment]
onbcnmleave works fine.

**Comment by TeoTwawki** [comment]
this is godamn frustrating. re read your own gd posts before replying to me again.

**Comment by cowrevenge** [comment]
if (csid == 0x7d01) then
Does not work
if (csid == 0x7d01) then
Does not work
if (csid == 0x7d01) then
Does not work
if (csid == 0x7d01) then

**Comment by TeoTwawki** [comment]
idiot

**Comment by TeoTwawki** [comment]
"The 1 is the change."

**Comment by cowrevenge** [comment]
player:startEvent(0x7d01,1,1,1,instance:getTimeInside(),1,0,0); -- not skippable

player:startEvent(0x7d01,1,1,1,instance:getTimeInside(),1,0,1); -- skippable 

if (csid == 0x7d01) then -- works when skipped, but does not work when forced to watch

**Comment by TeoTwawki** [comment]
Thank you.

Its acting the opposite to whats expected.

**Comment by cowrevenge** [comment]
I wasn't asking for help. I already fixed the issue on my server. I was trying to provide you with information and there was an error in communication. 5-1 works on my server because I created a playervar "bcnmwin" with a value of 1, when people click or trade to the burn circle. This is set at 2 when bncm leave 2. onEventFinish then checks this value and gives ki, then sets it back to 1.
You could warp out after win, but clicking or trading resets it anyway.

 I removed "if (csid == 0x7d01) then" and replaced it.

Just in case someone else is reading this. All of this chat has nothing to do with this pull request. :(

**Comment by teschnei** [comment]
If I understand this correctly - this change fixes the player not being removed, but does not address what was discussed with 5-1?

**Comment by cowrevenge** [comment]
Yes.

**Comment by TeoTwawki** [comment]
I didn't say you were asking for help. I said if you were going to act like that I wouldn't be helping in the future.

I had to ask for clarification on where your quoted line of code came from because there was no context. It was a yes or no question. The lack of reading comprehension has been astounding. Goodbye now.

**Comment by teschnei** [comment]
I fixed this in e3ffb1ed5a9e79d105e47b897614ba229aa682cb.

**Pull request closed without merging**
