### PR TITLE
Bark Tarantula - unnecessary mobmod

### PR DESCRIPTION
**Pull request by nesstea**
Dropped too much gil.

### CODE REVIEW

**Comment by bendangelo** [comment]
References?

**Comment by bendangelo** [comment]
Wait, what mob did this belong to before? I think the mob id should just be changed to the correct mob.

**Comment by teschnei** [comment]
BARK TARANTULA, DONT PLAY WITH MY STYLE I MIGHT STING YA

**Comment by Deadwing888** [comment]
Ahhh someone finally reported Goldfinger the bark tarantula lol.

**Comment by bendangelo** [comment]
Thanks for contributing but the mod belonged to Vivian. I just went ahead and did it for you.

**Pull request closed without merging**
