### PR TITLE
Add Entries to item_mods and item_mods_pet Tables

### PR DESCRIPTION
**Pull request by CoolJoeWee**
Created insert statements to item_id in both item_weapon and item_equipment that didn't have any mods in item_mods or item_mods_pet table.

### CODE REVIEW

**Comment by TeoTwawki** [comment]
image
 even when I looked at the commits separately, too big to happen all at once.  If I have to do a local pull just to see the changes, I am far less likely to review it in the same _week_ you opened it. And 1000x more likely to wait and let it be somebody else who reviews it.

**Comment by CoolJoeWee** [comment]
@KnowOne134 

Completely forgot about it as I was merely working on the additions. I will have both sql files sorted in the next commit.

**Comment by TeoTwawki** [comment]
### Ok..I tried to rebase this for you..And I found it to be unreviewable for me. You code is still all there. But I cannot handle this. There were 2 major problems that are not truly your fault - I lost 2 and a half hours to my OCD\* and because the diff shows excessive line beyond your changes even when I hide whitespace changes. Both of these things are because the PR is ***to damn big*** and because you moved so many unrelated things for the sake of alignment to an arbitrary text column. I forget who started that but its ending today. I'm going to start transitioning us to something else after this. I'm not sure what yet.

##### \*This is a legit medical condition in which the brain forces things on a person, I can't "just ignore it" If we were in a professional environment some accommodations would exist for me, but alas this is an open source project anybody can contribute to: style guide is my only safety net here.

You can wait till someone else reviews who doesn't have my problems and hope it doesn't get an edit conflict again before then or you can redo it in smaller bite size pieces (no more than 500 lines per commit, all formatting/whitespace commits LAST, NO TABS and don't add spaces between values - I need the constancy).

Sorry, I just can't do this. My brains quest to make everything in the universe consistent put me into hyperfocus on things that don't matter instead of the stuff you are trying to add.

**Comment by CoolJoeWee** [comment]
@TeoTwawki 

First of all, appreciate your time for making an attempt at reviewing my PR and sorry for OCD that caused you. To be honest, I had checked less than 10 items throughout this exercise. Most my efforts were spent on parsing and the dictionary creation for DB inserts.  Creating insert statements with comments, sorting, and formatting was something extra I did just for PR.  DBMS should simply take care of them.....

While adding a varchar column to house the comments may help standardize formatting, it doesn't solve the fundamental data integrity problem, which is missing mod_id table.  I believe people added comments because of that. Instead, I'd like to propose adding mod_id table to the repo for maintainability. Mod details of items can be built with a few table joins. it'll definitely help with the reviews. Besides, a few other tables(item_latents, item_ mods_pet) may also benefit from it. There might be some work to come up with latent_id and pet_id tables as well to be thorough. The idea is, let data speak for itself. I don't mind picking up the initial load since it's my proposal if agreed.

Lastly, about the cap of 500 lines per commit. With nearly 15K entries on table, it'll take roughly 30 commits, let alone reviewing the changes. I doubt people would review them line by line because I already don't. They're merely data entries. If there are errors, the community can easily fix them without break the core. Risk of mass inserts to DB is low in my opinion.

**Comment by TeoTwawki** [comment]
I may have hasty saying 500, but 15k entries is to many for a single pull request. And a db table or the mods isn't going to fly - we have to many places to update mods at as it is. The comment was there to aid reviewing, and its now becoming a hindrance. And people keep changing each others formatting - I previously asked the main contributors of that to get together and settle on one and codify it as THE style, and that never happened so new contributors just try to go by which one they think is dominant or is more aesthetically pleasing. Can't blame new contributors for that, it whats I would have done too. So  I'm just trying to reduce future frustrations while explaining why I can get'r'done here. 

The pr I opened last night is in draft state for several reasons, one of which is letting your merge 1st - it'll be easy for me to fix mine but you fixing yours if mine went first would be a hassle for you. Other reasons include seeing if the rest of the team veto's it before it goes farther.

(Note that many items have no comments - they'd been stripped by past redumps of the table.  Comments often contain info that is not simply the modifier info.)

**Comment by CoolJoeWee** [comment]
@TeoTwawki 

Okay. I'll close the pull request and let you take over with another PR?

**Comment by TeoTwawki** [comment]
I was saying if your stays up and anotehr dev can review+merge it, I can easily fix the resulting conflict in my own pending draft or.

If I were to merge mine first yours would get hit with conflicts again (like the ones I fixed last night, this is why github shows I committed to your branch)

**Comment by teschnei** [comment]
How many lines were actually added in this PR? If there really are 13k mods added, that's going to need to be split up, because it's too much to review at once.  If there's only 13k lines changed because of formatting changes, please don't mass change the format of files like that (especially in the same commit with actual changes), because it makes both reviewing and merging much harder.  So we need to either split it up, or undo formatting changes so that the PR only contains actual changes.  (then we can think about reformatting later, separately, if we care about it)

**Comment by CoolJoeWee** [comment]
13928 new entries to item_mods.sql and 330 to item_mods_pet.sql. f0eb43c, unsorted, should be the cleanest as new entries were simply appended.

**Comment by zynjec** [comment]
Has a conflict, and quite frankly just way too big to review in a single PR.

Please submit your additions in a separate commit.

**Pull request closed without merging**
