### PR TITLE
 Basic additions for aptant NM Nargun in Ro'Maeve. Drops not added yet. 

### PR DESCRIPTION
**Pull request by TeoTwawki**
Most info I could locate was at https://translate.google.com/translate?sl=auto&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=wiki.ffo.jp%2Fhtml%2F18539.html&edit-text=&act=url

### CODE REVIEW

**Comment by TeoTwawki** [comment]
@zynjec meeerrrrgggee mmmeeeee

without loot he can't be loot piñata, will add loot when more of him is working

**Comment by KnowOne134** [comment]
Teo starting to sound like me

**Comment by TeoTwawki** [comment]
Then I must be doinitright

**Comment by KnowOne134** [comment]
Thank you for the verification. Im finally doing it right

**Comment by TeoTwawki** [comment]
see it works guys, we just nag zynjec specifically formn now on!
j/k don't hurt me
_-hides-_

**Pull request merged**
