### PR TITLE
Various bug fixes from previous commit

### PR DESCRIPTION
**Pull request by neosatus**
The Trick Attack fix got put live on Era recently and mass testing caught a few more things.

Jump and High Jump got missed when doPhysicalWeaponskill params were changed.
Spirits Within used a different variable syntax that was broken by a mass edit.

### CODE REVIEW

**Comment by teschnei** [comment]
jump/high jump should check for TA

**Comment by neosatus** [comment]
Alright, I'll add that in.

**Comment by teschnei** [comment]
not that it matters anymore (since you're replacing it), but nullptr isn't a thing in lua.. you probably meant nil

**Comment by neosatus** [comment]
Yea, I had just noticed that. It's actually running on Era now as nullptr (cause I copied the fix we put in when we found it) and it works. Presumably an uninitialized defaults to nil. Obviously not good practice though.

Quick question, the getTrickAttackChar checks for TrickAttack status as it's first step. The previous code from weaponskills.lua (that I replaced recently) checked for it as well before calling it. Is there a performance savings to do the check twice in order to not have to go back to core or should I remove the check as it's redundant?

**Comment by takhlaq** [comment]
performance hit is prolly negligible but ya, redundant code be redundant so check isnt necessary :)

**Comment by TeoTwawki** [comment]
There is this wonderful feature call "amend" you should look into :smiley: 
It lets you change the very last commit you made, and then you can do whats called a force push to replace it, rather than stacking up additional commits.

**Comment by teschnei** [comment]
also check: scripts/mobskills/freezebite.lua

**Pull request merged**
