### PR TITLE
Adding quest Bastok Too many chefs

### PR DESCRIPTION
**Pull request by dwn134**
2 problems im having with this is the check for fame, and both options for the start of this quest are option 0 , so the quest will start no matter what you pick. Other than that everything works.

### CODE REVIEW

**Comment by ibm2431** [comment]
> is the check for fame

What's the problem with the fame check? Is the quest available event playing when the person has insufficient fame? Not playing when they supposedly do have the correct fame?

> both options for the start of this quest are option 0 , so the quest will start no matter what you pick

Is this how retail behaves? Do the contents of the event for both options indicate the quest is being accepted?

**Comment by dwn134** [comment]
The fame check problem im have on my test server is i can recieve the quest
no matter what my fame is. I have only tested on my GM account and not a
reg account if that makes a difference.

**Comment by dwn134** [comment]
It could be very possible either option starts the quest. I cant see to find any evience that it wouldnt. In that case disregard that part

**Comment by TeoTwawki** [comment]
> The fame check problem im have on my test server is i can recieve the quest no matter what my fame is. 

show us what your fame check looked like.

> both options for the start of this quest are option 0 

```lua
function onEventFinish(player,csid,option)
    -- printf("CSID: %u",csid);
    -- printf("RESULT: %u",option);
```
Wen you uncomment the prints, both menu selections have RESULT of zero on that csid?

**Comment by dwn134** [comment]
Yes both option show as 0 when un commented

**Comment by TeoTwawki** [comment]
Cloned your branch local and took a look. Fame check worked fine for me so guessing you had the fame boost setting used or something..

I also verified retail does start the quest no matter which option you choose, and then cleaned up your [whitespace](https://github.com/DarkstarProject/darkstar/pull/3887/commits/0b8a65148b4a92bce87ecc301461c73c585ff8f4#diff-d11d9c73b0e9aa8160f756b64893bc5dL24). Project uses 4 spaces, not tabs. It looks like you used githubs crappy web editor.

**Comment by dwn134** [comment]
I was using notepad ++  I seem to get some error when i use spaces but tabing to the right location seems to work. Then copy and pasted to my fork. This was my 1st time doing this so im happy it got merged

**Comment by TeoTwawki** [comment]
Whatever you copy and pasted *into* from notepad++ is likely the culprit. We avoid github's app and its web UI for editing files. They encourage bad commit messages, stabs, and other problems.

In notepad++ you can still actually use the tabkey and automatically get 4 spaces if you edit the settings to do so. If you are having trouble with some kind of error, you should see about getting help with getting that fixed. I have a reconfigured portable copy (runs from USB device, no installation) should you need one.

Thanks for contributing. 😄

**Comment by dwn134** [comment]
The issue i was getting was someone sending me a file from pastebin that i
copy and pasted and i had to delete every space in the whole script for it
to work. Its a learning process for sure But thanks you guys for putting
this game together

**Pull request merged**
