### PR TITLE
Improve treasure binding and fix bug where client says you dropped item to yourself.

### PR DESCRIPTION
**Pull request by TeoTwawki**
So, how do you feel about moving BCNM loot from SQL to script? It'd be fairly easy to do and I could fix the longstanding bug where the last item gets force dropped at the same time.

### CODE REVIEW

**Comment by teschnei** [comment]
that's something I do want to see done, yeah

**Comment by TeoTwawki** [comment]
I think I can accomplish it fairly quickly next time I get a day to myself.

**Comment by takhlaq** [comment]
if you feel like finishing off rewrite im not even using sql there (and i'd prefer there not to be conflicts when it is finally ready to merge)

**Comment by TeoTwawki** [comment]
@takhlaq I can just do it in that branch and it can land in master when the branch gets merged

**Pull request merged**
