### PR TITLE
Gm away tells

### LINKED ISSUE #4211: GMs and sending /tells to people with /away status.
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30170707_0

**_Server Version_** (type `!revision` in game) **:** 
de8eab2e5da8bfad3f4e0ea98dca001a025dda9b

**_Source Branch_** (master/stable) **:** 
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
GM's can no longer send tells to people with /away flag. Last time I had to talk to someone doing inappropriate things attempting to hide behind /away (10ish months ago) if you had the GM flag you could still send /tells to them and could not be ignored. 

Also, if you have the /away flag up and you log out you also now have perma away flag no matter how much you zone etc.

### PR DESCRIPTION
**Pull request by ShelbyZ**
- GM must have GM flag toggled
- Fixes #4211

### CODE REVIEW

**Comment by TeoTwawki** [comment]
> https://github.com/DarkstarProject/darkstar/pull/4267

image

The way you were doing it the 1st time by checking GM level, was correct.

**Comment by teschnei** [comment]
I think in this case, it's okay to do it this way.  Tells with the [GM] tag
are allowed, while ones without are not (and most likely if you are taking
disciplinary action, you have your GM flag on).  Otherwise, should all GM
messages have the [GM] chat mode?

**Comment by TeoTwawki** [comment]
other things still get the fire and burning!

**Pull request merged**
