### PR TITLE
Additional Effects V1.3

### PR DESCRIPTION
**Pull request by Krynasty**
fixed weapons effects calling globals constantly.
fixed sub effect for darkness damage weapons.

### CODE REVIEW

**Comment by nesstea** [comment]
wanna do the sirroco dagger while you are at it? it's the wind elemental one.

**Comment by TeoTwawki** [comment]
Like I said on IRC, you don't have to open a new pull request, just pushing to the same branch automatic updates the existing one

**Comment by TeoTwawki** [comment]
@nesstea sirroco kukri has already been in trunk for like a year

**Comment by TeoTwawki** [comment]
Don't forget to check the changes to base dmg and proc% now that you've closed #1050 which was same branch. When you add new stuff, avoid changing old stuff unless you can safely say the change was more retail accurate than the old value.

**Comment by Krynasty** [comment]
ill bear that in mnd. thank you.

**Comment by maxtherabbit** [comment]
so I see you're still changing dmg and proc rates? got sources on that stuff?

also why are there two of these?

**Comment by Krynasty** [comment]
i have closed the other one now. this will be the only one that gets updated.
still getting used to github and stuff. sorry about this.

**Comment by maxtherabbit** [comment]
Status effect resistances must be checked in the weapon scripts. I realise you don't have any in this particular pull rq but regarding the other one you closed: there are no other places that apply resistance for the mob it must be done here. I suggest you look at other additional (status) effect weapon scripts to see the correct way to do the resist chance. I'm not 100% sure how the element is determined for the status effect but I would assume it would be the same as the element of the spell which would normally apply it. @TeoTwawki may know more about that. 

Also I will be shortly modifying applyResistanceAddEffect() to apply specific status resistance bonuses. With this in mind, the correct format for the call is: applyResistanceAddEffect(player,target,ELE_WHATEVER,EFFECT_WHATEVER)

The 4th param is currently a unused param for a bonus, so I ask that any new additional status effect scripts added to the trunk replace the '0' with the appropriate EFFECT_X as of now :D

**Comment by xdemolish** [comment]
@maxtherabbit get modifying

**Comment by maxtherabbit** [comment]
there's no need to me to fix that prior to this getting merged, he can go ahead and make the requested changes anytime now :fast_forward:

**Comment by TeoTwawki** [comment]
Some of the changes were pointed out in the other 2 pull requests he had open, and it got all confusing with the comments scattered among those because of pull requests being closed then reopened and diff one closed so I'm repeating some of what I can remember here:

pre-existing data like dmg amount and proc rate should not be being changed unless the change is for sure making it more retail accurate than the previous values.

**Comment by xdemolish** [comment]
reopen when changes have been made (i keep accidentally checking this pull req thinking it was opened recently)

**Pull request closed without merging**
