### PR TITLE
misc item fixes

### PR DESCRIPTION
**Pull request by Ninjistix**
mostly fixes form one of my old prs that are still missing

side note can we decide something about the comment spacing, like is there going to be a standard format?

### CODE REVIEW

**Comment by teschnei** [comment]
Comment spacing?

On Sep 5, 2017 12:36 PM, "Ninji" <notifications@github.com> wrote:

mostly fixes form one of my old prs that are still missing

side note can we decide something about the comment spacing, like is there
going to be a standard format?
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/DarkstarProject/darkstar/pull/4036
Commit Summary

   - misc item fixes

File Changes

   - *M* sql/item_mods.sql
   <https://github.com/DarkstarProject/darkstar/pull/4036/files#diff-0>
   (335)
   - *M* sql/item_mods_pet.sql
   <https://github.com/DarkstarProject/darkstar/pull/4036/files#diff-1>
   (10)

Patch Links:

   - https://github.com/DarkstarProject/darkstar/pull/4036.patch
   - https://github.com/DarkstarProject/darkstar/pull/4036.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/DarkstarProject/darkstar/pull/4036>, or mute the thread

**Comment by Ninjistix** [comment]
Spacing for the comments in this file isn't uniformed, someone has either tabbed/aligned/spaced some comments, the rest are just 1 space

capture

**Comment by teschnei** [comment]
As long as there is a space between the dashes and the text, it's fine. The
space between the semicolon and the dashes doesn't matter

**Comment by Ninjistix** [comment]
ok

**Comment by Ninjistix** [comment]
@teschnei in a separate branch I spaced, the commits evenly by 2 tabs (4 spaces each), and also shorted some long line commit messages, can you take a look before i try to open a PR

https://github.com/Ninjistix/darkstar/commit/d625581b3eb7ea37eb39273bfff72140e7f28b00?w=1

**Comment by teschnei** [comment]
I don't really see much of a point in changing the spacing - there's not really anything to gain and it makes merging a pain

**Comment by Ninjistix** [comment]
if i have more mods to add, to avoid merge conflicts should i commit them to this branch?

**Pull request merged**
