### PR TITLE
Summoner mods QC and reordered item_mods_pet.sql

### PR DESCRIPTION
**Pull request by wrenffxi**
Fixed inconsistent sign on summoner mods
Added some missing summoner pet mods
Reordered item_mods_pet.sql by itemId
QC on Evokers, Convokers, Summoners, Glyphic, Callers sets (and their upgrades)

### CODE REVIEW

**Comment by wrenffxi** [comment]
Also related to issue #2082

**Comment by Hozu** [comment]
The modifiers for pets on equipment needs rework - they apply to all pets, and there's no way to limit that to anything specific.

**Comment by teschnei** [comment]
Pet latent?

**Comment by Hozu** [comment]
There is a latent that checks for the pet, yes, but the mods in item_mods_latent are applied to the master. item_mods_pet is currently the only table that applies mods to pets, but it can't do latents.

**Comment by teschnei** [comment]
it's not hard to add a way for latents table to add to pets - i thought we
had done that already, but apparently not

**Comment by TeoTwawki** [comment]
Or do what we did with mods and have 2 tables.

**Pull request merged**
