### PR TITLE
Halvier

### PR DESCRIPTION
**Pull request by Turttle**
Cleaned up a the code a bit and fix the logic order of checks. Nested
Mission 9-2 check under Nation check.

### CODE REVIEW

**Comment by xdemolish** [comment]
have you checked to make sure his script doesnt get stuck ever?

**Comment by Turttle** [comment]
i check the mission that where giving issues which where sandy 2-3 CS for KI. I will check each of the mission that he has scripted, until then hold the pull.

**Comment by Turttle** [comment]
@xdemolish  all mission that are on Halvier script, including bastok and windy have been tested and everything is working.

**Comment by TeoTwawki** [comment]
My hero.

**Pull request merged**
