### PR TITLE
strays don't reward XP

### PR DESCRIPTION
**Pull request by wrenffxi**
retail evidence (volume warning!)
https://www.youtube.com/watch?v=oEBb5bU2sM4#t=2m45s

### CODE REVIEW

**Comment by TeoTwawki** [comment]
```sql
INSERT INTO `mob_pool_mods` VALUES (3784,2,-1,1); -- Stray GIL_MAX: don't drop gil
INSERT INTO `mob_pool_mods` VALUES (3784,28,-100,1); -- Stray EXP_BONUS: don't give XP
INSERT INTO `mob_pool_mods` VALUES (2614,368,100,0); -- Memory Receptacle regain 10%
```
you know I'm just gonna move all 3 of these to lua if you don't, before merging

**Comment by zynjec** [comment]
Why would you put it in lua?

This is literally what this table is there for, instead of having to copy and paste those 3 mods to strays across 4 zones.

**Comment by TeoTwawki** [comment]
This is literally a thing we're trying to get rid of and has been mentioned multiple times, why would you keep expanding it?

**Comment by zynjec** [comment]
Maybe for one off mobs, but this is a family across multiple zones, applying 3 mods for 4 different scripts is a lot messier.

**Comment by TeoTwawki** [comment]
I disagree Like I said were intending for this table to not exist in the future. I was told be dear leader we prefered to lua them. 3 isn't a lot of scripts to add 1 line to.

**Comment by TeoTwawki** [comment]
fk it merge if you want, I don't care enough to die on such a small hill

**Comment by nfaletra** [comment]
Per discussion on discord, mob_pool_mods isn't going anywhere. We're trying to avoid having sql handle mob mods on an individual mob.

**Pull request merged**
