### PR TITLE
abilities using target:takeWeaponskillDamage() rather than takeWeaponskillDamage()

### PR DESCRIPTION
**Pull request by wrenffxi**
This PR started as a fix for crashy card shots.  It has evolved. :)

### CODE REVIEW

**Comment by Hozu** [comment]
https://github.com/DarkstarProject/darkstar/blob/master/scripts/globals/weaponskills.lua#L881

Looking at that, either the binding or the function should be renamed so this confusion doesn't happen.

**Comment by teschnei** [comment]
takeWeaponskillDamageDontCallThis?

nothing should be calling the binding except for the lua function (and I don't see a reason why the shots are bypassing the lua function)

**Comment by Hozu** [comment]
I intended to use the function when I wrote it, but it looks like I did it wrong. I assumed that wasn't the case since it was working. Sorry about that.

**Comment by TeoTwawki** [comment]
`weaponskillDamageCaughtInCeilingFan()`

The instructions, they were unclear again..

**Comment by wrenffxi** [comment]
All right.  That should be better.

**Comment by teschnei** [comment]
tp mult and ce/ve override don't need to be defined, just pass an empty table into the function

dmg = takeWeaponskillDamage(target, player, {}, true, dmg, SLOT_RANGED, 1, 0, nil);

**Comment by wrenffxi** [comment]
Third time's the charm.

**Comment by TeoTwawki** [comment]
> nothing should be calling the binding except for the lua function (and I don't see a reason why the shots are bypassing the lua function)

@teschnei  Totally slipped my mind this came up before. Now I recall being grumpy about the naming myself after: https://github.com/DarkstarProject/darkstar/blob/1b705c79a11724e2b977947fa23707b98867dca0/scripts/globals/weaponskills/spirits_within.lua#L58
I put that comment there to remember which one it was already using, so the fact of it already using the wrong one ain't my fault. Also happens in Atonement.lua 

So if no place should call that binding except the lua wrapper function the same name, and its already been done wrong in several situations, we need to either fix'em all and then keep a better eye on pr's using the wrong one, or just rename one of them already. `doNotUseTakeWeaponskillDamageYouPunkKids()`? I got nuthin.. 😃

**Comment by teschnei** [comment]
you could skip the call if it didn't add enmity, but you could also call it with 0 enmity multiplier.. 

I say just make everything use the lua function.  

also, I dont think it needs changing, but you could have just omit the last argument entirely if it was just going to be nil (Lua will give you nil for a missing argument)

**Comment by TeoTwawki** [comment]
> but you could have just omit the last argument entirely if it was just going to be nil (Lua will give you nil for a missing argument)

In my best archer voice: Do you want ~~ants~~ messages about nils in the console long? because thats how you get ~~ants~~ messages about nils in the console log. (it'll notify you about it even when it doesn't cause a problem)

**Comment by teschnei** [comment]
i think that was just for tables that you were seeing those... would be no difference in this case as they'd both evaluate to nil

**Comment by wrenffxi** [comment]
There we go.  No more calls to the binding.

**Pull request merged**
