### PR TITLE
onMobDeath..Stuff! And also Things!

### PR DESCRIPTION
**Pull request by TeoTwawki**
1st commit has the core changes, 2nd has the script changes.
easier reading: https://github.com/TeoTwawki/darkstar/commit/18f1844d6c20f22fb429027959e7a0d6aff86cf7?w=1

Scriptwriters will need to pay attention to this:
**killer:doStuff()** and **doStuff(killer)** for things that should ***only*** effect the person delivering killing blow, **ally:doStuff()** and **doStuff(ally)** for things that need to effect ***every member*** of every party of the killer's alliance.

### CODE REVIEW

**Comment by teschnei** [comment]
What do you mean pcall isn't documented? It's part of lua itself :(

**Comment by TeoTwawki** [comment]
maybe I wrote wrong thing there but remember when I needed to know what the friggin params for something were the other day, and couldn't find wtf they were anywhere in our trunk? Link I am gonna know what `(0, 2, LUA_WHATEVER)` actually means :(

**Comment by TeoTwawki** [comment]
Somebody tried to stick things in pretty variable names but then didn't leave any mention of wtf was what.

**Comment by TeoTwawki** [comment]
easier reading: https://github.com/TeoTwawki/darkstar/commit/79e9e347934f33a4cadc43492c9cf6dbb8e168a3?w=1

**Comment by teschnei** [comment]
you mean LUA_MULTRET? that's part of lua, not dsp, so you can just google it.  I like this site for the various lua functions: http://pgl.yoyo.org/luai/i/lua_pcall
at any rate, i'll look at it when I get home :)

**Comment by TeoTwawki** [comment]
I guess this will have to serve as a reminder that I should actually read the manual and not just the DSP trunk. :blush:  I thought we had a monopoly and just barely comprehensible abbreviations paired with numbers that mean nothing to me till I go on a hunt.

**Comment by Hozu** [comment]
Er, your commit managed to add in your branch merging prior to your code stuff, so it's adding in things that were already done.

**Comment by TeoTwawki** [comment]
@Hozu you are just seeing the merge. Its safe.

**Comment by TeoTwawki** [comment]
I had time before I take off again to rebase - anything looking like repeats you see now are from whitespace changes.

**Pull request merged**
