### PR TITLE
Item Mods Part 1

### PR DESCRIPTION
**Pull request by Ninjistix**
So here I am again doing item_mods... trying to clean up the list by going over it to;
- Add all missing comment info
- Correct items with the wrong Mod or Mod Value.
- Reorganize mod lines based on item tool-tip.
- Add any new items (or items missing mods)

Side note:
- I'm just placing (UB) on item's with no actual number value in the tool-tip as a reference.
- Item's with ,NONE, or (NA) have nothing defined in the [modifer.h](https://github.com/DarkstarProject/darkstar/blob/master/src/map/modifier.h) about the mod (or I missed it)

when I finish ~500 lines I'll commit them, added a commit bookmark at end to remember where I left off, will prob move it down again next commit. 

https://github.com/DarkstarProject/darkstar/pull/3521/files?w=1
Without the White space changes.

### CODE REVIEW

**Comment by Ninjistix** [comment]
hmm something went wrong sec

**Comment by libeclipse** [comment]
> when you're desperate for those +/- lines on your profile

**Comment by Ninjistix** [comment]
That comment only tells me what a small minded person you are.

**Comment by libeclipse** [comment]
> notice me

Lmao you go ahead mate. Someone merge this so Mr. Insecure here feels better about himself.

**Comment by takhlaq** [comment]
adding comments only really helps us when reviewing additions since eventually someone's gonna dump the file and comments will be lost so there's not really any point in commenting stuff already in there

also no idea why you're changing the comments from previous commits, maybe you and @wrenffxi  should decide on a formal cause there's really no point in changing existing ones unless they're completely wrong

**Comment by takhlaq** [comment]
format even (blame autocorrect)

**Comment by Ninjistix** [comment]
thb I'm doing  these on my server, just decided to open a PR here too to share my work

**Comment by Ninjistix** [comment]
ill submit it once its complete... (and ill try to keep the changes to under 500 per commit)

**Pull request closed without merging**
