### PR TITLE
trying push request cop 1-3 missing cs

### PR DESCRIPTION
**Pull request by gedads**

### CODE REVIEW

**Comment by gedads** [comment]
https://github.com/DarkstarProject/darkstar/pull/1355/files?w=1

**Comment by xdemolish** [comment]
rip out your tab key and replace all tabs with 4 spaces :D

**Comment by gedads** [comment]
no way

**Comment by nesstea** [comment]
lol

**Comment by helixhamin** [comment]
ctrl+h is your fwiend.

**Pull request merged**
