### PR TITLE
SQL: Dimensional Death/Barbed Crescent ID check fix

### PR DESCRIPTION
**Pull request by Hozu**
Another broken spell with the mobskill/family separation, again due to fomor stuff. Though this separation means that Barbed Crescent should finally be learnable.

### CODE REVIEW

**Comment by teschnei** [comment]
FYI: I can basically guarantee it will break again when I merge the ai
rewrite

**Comment by Hozu** [comment]
Really? Well it can be easily fixed at that point at least.

**Comment by teschnei** [comment]
Yes, just that I probably won't remember to do it :p

**Comment by Hozu** [comment]
Rather have it working now then break later, and be easily fixed after someone catches it over waiting for the ai rewrite to be finished and fix it then, honestly.

**Comment by teschnei** [comment]
I'm not saying this shouldn't be merged, just something I thought of since
this will essentially have to be reverted then

**Comment by bendangelo** [comment]
I'm going to merge this because it does fix the issue.

**Pull request merged**
