### PR TITLE
DB/SQL - Neo Nyzul and Salvage+1 Gear

### PR DESCRIPTION
**Pull request by theRonLewis**
Updated item_mods.sql to also set up gear from Neo Nyzul and Salvage+1.

Wanted to do a smaller pull request before doing a larger one. I think this should look better for you guys now, w/line-by-line changes. If this does look good, I have more gear updates from folks on my server to review myself and then submit.

Thanks.

### CODE REVIEW

**Comment by TeoTwawki** [comment]
@theRonLewis  Nice work.

**Comment by TeoTwawki** [comment]
@theRonLewis looks like you accidentally committed a backup file. A git amend can be used remove that without adding additional commits if desired.

**Comment by xdemolish** [comment]
don't forget to change the commit message to include commit lables while you're at it :D
(see https://github.com/DarkstarProject/darkstar/blob/master/README.md)

**Comment by theRonLewis** [comment]
D'oh, thanks guys. This is why I did a smaller test one first! Updated the name, and now looking into an amend to update my previous commit. I'm using the windows GUI though and not the command line. I'm reading it's just a 2nd commit? That doesn't seem right.

**Comment by TeoTwawki** [comment]
Thats the PR title you changed, not the commit message

**Comment by TeoTwawki** [comment]
are you using github crappy app? Never us ethat. Trying to do it via the website interface is almost as bad. Should either use tortosiegit or the command line git bash. In tortoise you enter the commit dialog then check the "amend" box", then after replacing teh commit (it will only replace the very last commit, with the new one) you force push to your branch. The pull request is then automatically updated.

**Comment by TeoTwawki** [comment]
There ya go :smiley:

**Comment by theRonLewis** [comment]
Yeah, I'm using the pretty crappy git windows gui app. I think I have gitbash, I'll put in some time to learning that. Shoulda figured the gui would be crap haha.

All I did here was remove the file, and create another commit I think. Something online I read said --amend will just create another commit anyways, but that sounds fishy to me. Maybe because I already pushed up to the server.

Either way, looking to get a better grasp on git, and help out with this project. Hope I'm not a pain! lol

**Comment by xdemolish** [comment]
once more! (you accidentally committed an extra file)

**Comment by TeoTwawki** [comment]
https://msysgit.github.io/
https://code.google.com/p/tortoisegit/
The 1st link gives you the command line tool, the 2nd gives you a windows shell interface but depends on the command lien being available to function.
And now you'll need to squash too, but you got the commit message format right.

**Comment by theRonLewis** [comment]
Whoops! File wasn't checked or something. Incoming!

**Comment by TeoTwawki** [comment]
meant to say "shell extension". As in you get a right-click menu in windows. very handy.

**Comment by theRonLewis** [comment]
Awesome. I think I've got GitBash and GitGui (separate from the crap github windows gui, but I think also not as great as command line and shell extension interfaces). I'll get tortoise and start getting familiar with that.

I've gotta squash wut?

Thanks whasf.

**Comment by xdemolish** [comment]
meh it's already been merged now but ya, squash/amend as needed :D

**Pull request merged**
