### PR TITLE
Correct all misuses of utils.clamp throughout trunk. This fixes a bug with Phalanx.

### PR DESCRIPTION
**Pull request by TeoTwawki**

### CODE REVIEW

**Comment by TeoTwawki** [comment]
I blame copy pasta!

**Comment by TeoTwawki** [comment]
I was absorbing mobs ice spikes when I had ~~failanx~~ phalanx up.

**Comment by TeoTwawki** [comment]
Side note: seem to be a lot of clamping happening before more math is done to things, not sure that's right but didn't touch it. Hopefully its not possible for those effect durations to go negative from resistance.. >.>

**Comment by bendangelo** [comment]
Duration is clamped to 1 for most status effects

**Pull request merged**
