### PR TITLE
Updated Item_Weapon

### PR DESCRIPTION
**Pull request by Ninjistix**
fixed some delays and added missing h2h weapons

### CODE REVIEW

**Comment by bendangelo** [comment]
Do you know how to squash this?

**Comment by Ninjistix** [comment]
nope, how?

**Comment by TeoTwawki** [comment]
Also you tested?

**Comment by Ninjistix** [comment]
yeah tested them

**Comment by Ninjistix** [comment]
figured out how to rebase commits, will prob have to do it again in a few days...

**Comment by bendangelo** [comment]
Thanks for contributing :heart:

**Comment by Ninjistix** [comment]
thanks a lot, will work on adding/fixing more during the week

**Comment by tagban** [comment]
Thanks Ninji!

**Comment by R3P0FFXI** [comment]
@Ninjistix @bendangelo can we be sure this is correct, I dont remember which as its been a while since anyone talked about H2H delays but was the base delay taken into account I thought H2H was always a lower delay due to the delay associated with not having a weapon equipped and just using bare knuckles. If this is the case then they may have been previously correct at the 300 delays they were at before.

**Comment by Ninjistix** [comment]
I was told by kj that all h2h start wth 480+ whatever delay is on the
weapon , so nothing should be under 480 for h2h

**Comment by tagban** [comment]
I'm guessing 480 is the default delay IE 0 on a weapon itself..?

**Comment by TeoTwawki** [comment]
Probably 480 is what your delay is with nothing at all equipped, before any reduction from martial arts etc.

**Pull request merged**
