### PR TITLE
BCNM Add Royal Jelly

### PR DESCRIPTION
**Pull request by Linkandentity**

### CODE REVIEW

**Comment by zynjec** [comment]
I believe there is a lot more work to be done for this BCNM to be functional.

There are 8 Princess Jelly's that slowly make their way to the center of the arena, and merge in to a final Queen Jelly

**Comment by Linkandentity** [comment]
Thanks for getting back.  It'll take me while to figure out what's changed in the code in recent years.  Do you know if any other bcnms follow this same scenario or is it bespoke?

**Comment by TeoTwawki** [comment]
Theres also that unmerged bcnm branch we're alegedly almost done with that changes some things

**Comment by zynjec** [comment]
Going to close this for now, feel free to open another PR once completed.

**Pull request closed without merging**
