### PR TITLE
Add Geyser Lizard

### PR DESCRIPTION
**Pull request by ymkc**
unfortunately not synced to the geysers, just a fake timed pop

### CODE REVIEW

**Comment by takhlaq** [comment]
how should this behave? syncd with player interactable geysers? (e.g. the ones which trigger on players running over them and move them)

**Comment by TeoTwawki** [comment]
years ago that NM was geyser sync', but on modern retail he's just a lotty spawn

**Comment by TeoTwawki** [comment]
should be using phOnDespawn() in the proper placeholder mob

**Comment by TeoTwawki** [comment]
just noticed *both wiki* still say when geyser spawns, lol

**Comment by ymkc** [comment]
thought it was synced to the bigger geysers erupting, the ones that are fogging parts of the zone

**Comment by TeoTwawki** [comment]
uh, apologies for the multi post spam:
They changed it when they added the lv 80 mobs to the zone. They moved him down to the lower lv steam lizard area.

**Comment by ymkc** [comment]
so turn him into a lottery pop from the steam lizards?

**Comment by TeoTwawki** [comment]
was looking in polutils just now to identify the PH I was killing in retail last free week... :thinking: they aren't even grouped. perhaps coincidentally he only ever spawned with one lizard down and I misremember the cooldown on steal lizard repops :thinking: 

Normally when you have a lotto pop, the PH is in a group of several and is the bottom to top member of that grouping. There are only 4 steam lizards left in the zone (SE nearly made these extinct!) so the only thing I can prove atm is that they no longer sync with the geysers going off. Shall we just time spawn him for now till we get a longer camping session on retail to prove/dis[rove placeholdering? Which means, no further work needed on this here PR (Teo's swiss cheese memory making Teo be Teo again).

**Comment by TeoTwawki** [comment]
Oh, I didn't check the pos's you used.

He's only around G-11 now so if thats where you have it it's good

**Comment by ymkc** [comment]
i see :)
will have to change his pos to g-11, i put him all over the zone like the wikis say

**Pull request merged**
