### PR TITLE
Create scroll_of_blizzaja.lua

### PR DESCRIPTION
**Pull request by some1here**
Making scroll work

### CODE REVIEW

**Comment by TeoTwawki** [comment]
Thank you :heart:

**Comment by nesstea** [comment]
Can you do one commit for all the scrolls @some1here  instead of one commit for each of them?

**Comment by some1here** [comment]
Sorry for the second batch but this was to patch(xx) originally.  Then Teo  wanted it closer...... less space

**Comment by TeoTwawki** [comment]
@some1here its ok. If you get more you can combine when they are small things. I wasn't gonna ask you for anything more than what you already did.

**Pull request merged**
