### PR TITLE
Update the item_basic.sql and item_puppet.sql to include all current …

### PR DESCRIPTION
**Pull request by helixhamin**
…attachments for puppet.

Complete:
- [x] Accelerator IV
- [x] Armor Plate IV
- [x] Dynamo II
- [x] Dynamo III
- [x] Heat Capacitor II
- [x] Inhibitor II
- [x] Loudspeaker IV
- [x] Mana Jammer IV
- [x] Scope III
- [x] Stabilizer IV
- [x] Tension Spring IV

Best guess, needs some retail verification, but values are estimates or follow standard behavior for similar attachments:
- [x] Mana Channeler II
- [x] Tranquilizer III

Corrections for the following attachments:
- [x] Tension Spring III

The following are added to the appropriate SQL files (item_basic & item_puppet), but need someone to add the appropriate LUA behavior, since the methods are not something I am familiar with:
- [] Amplifier
- [] Amplifier II
- [] Arcanic Cell
- [] Arcanic Cell II
- [] Auto-Repair Kit IV
- [] Barrier Module
- [] Damage Gauge II
- [] Mana Tank IV
- [] Optic Fiber
- [] Optic Fiber II
- [] Regulator
- [] Repeater
- [] Resister
- [] Resister II
- [] Speedloader
- [] Speedloader II

### CODE REVIEW

**Comment by helixhamin** [comment]
Anyways, all done with what I can currently do, so should be ready for review. I will see if i can test tonight, and will update one I have tested some, like heat capacitor.

**Comment by helixhamin** [comment]
So, any love for pup here? Sorry, I won't be able to do the missing ones, so this is ready for merge if accepted.

**Comment by areckx** [comment]
No point without the lua scripts

**Comment by helixhamin** [comment]
Um, you know that many scripts were added. Yes some are still missing. I pretty clearly noted what is done and what is not

**Comment by areckx** [comment]
I see, though perhaps it would only be likely to be merged if only the sql entries that had lua scripts were added, so maybe take out the ones that need to be worked on and file an issue report on the need for missing lua files.

That's just my thought, though.

**Comment by TeoTwawki** [comment]
If we had a reason to reject or wanted something more done, we'd say so. Nobody has reviewed yet, maybe we will want something maybe we won't *we don't know yet and when we do we will comment or merge*.

**Comment by helixhamin** [comment]
@areckx based on that logic, why did you just have to submit the proper stuff for some armor? I would love to be able to commit the remaining luas, but beyond my current skill, so I can add the items, then let someone else fill in the missing pieces. And if a project team member data no without the associated lua,I will comment out so someone knows they are there, but not ready for actual release. Either way, right now just need to stand by until a project manager completes review.

**Pull request merged**
