### PR TITLE
Adjusted available NPC's on widescan

### PR DESCRIPTION
**Pull request by ymkc**
Lots of generic NPC's (which I forgot on the first commit) don't belong on widescan:
- Auction Counter's
- Excavation Point's
- Gate's excluding Gate Sentry's
- Elevator's

### CODE REVIEW

**Comment by teschnei** [comment]
are there any npcs with no models that show on widescan? is it possible to just disregard all no model npcs?

**Comment by ymkc** [comment]
great tip!
the list of npc's without models is 3200+ long, so pretty hard to check and there is little info on which npc's are on widescan or not

**Comment by ymkc** [comment]
not sure about stuff like:
- Large Apparatus
- Unstable Displacement
- Torches
- Banishing Gates

**Comment by ymkc** [comment]
added them all to the pr, if they do belong on widescan I will change it

**Pull request merged**
