### PR TITLE
CORE/SQL: expose latent effects to lua

### PR DESCRIPTION
**Pull request by xdemolish**
- moved item mod handling to lua

### CODE REVIEW

**Comment by whasf** [comment]
Can't you merge this? Or are you waiting for kj to take a look at it

**Comment by xdemolish** [comment]
waiting for minions to script the latents for each item

**Comment by teschnei** [comment]
maybe we should put this on a different branch so we can open PRs to it

**Comment by xdemolish** [comment]
as soon as i clean the query (cause fields r gone)

**Comment by teschnei** [comment]
actually, think we'll do something else for the pet mods.. i started going through fixing everything but it's too much work for like 3 items

**Comment by xdemolish** [comment]
guess the other way would involve adding a petmod field to item_latents

**Pull request closed without merging**
