### PR TITLE
Update Guslam.lua

### PR DESCRIPTION
**Pull request by AaronDemoncia**
As per BGwiki and Allahkazam for all Borghertz Hands quests, the previous AF quest simply needs to have been accepted.

### CODE REVIEW

**Comment by Hozu** [comment]
If you make it check for just accepted, the quest won't be able to begin if it's completed. I think you should check if it's completed or accepted. Or rather, the original file before my change was correct and it should be reverted to that.

**Comment by AaronDemoncia** [comment]
Id accept that, as it was perfectly functional as was.

**Comment by AaronDemoncia** [comment]
As you mentioned, thats a valid addition and it would (hopefully) prevent issues with people whom had already completed the quests being locked out, Coded in "or QUEST_COMPLETED" flags

**Comment by Hozu** [comment]
er, adding an or like that, while makes sense logically, doesn't work with code. That's how Qu Hau Spring was broken for a while. Doing ~= QUEST_AVAILABLE is the way to go, and that's what it originally had.

**Comment by AaronDemoncia** [comment]
*sigh* way to go LUA ill just go ahead and do that then.

**Pull request closed without merging**
