### PR TITLE
Fix multiple overlapping modifier IDs

### PR DESCRIPTION
**Pull request by TeoTwawki**
Someone used an existing modifier ID for a new one.
QD prolly came first I dunno, but it was easier to spot in item_mods.sql so that's the one I changed.

### CODE REVIEW

**Comment by TeoTwawki** [comment]
p.s. someone may wanna check the amounts of the quick draw mod being used in the item mods file..looks fishy to me.. That is outside the scope of this pull request though.

**Comment by TeoTwawki** [comment]
I just added a 2nd commit to remove over 82 liens of modifier that do not even exist in either status.lua or modifier.h 😠

**Comment by TeoTwawki** [comment]
Refix'd PR. Some were wrong because the previous editor thought IDs were spare because they were not enum'd. Because they are calculated as base+(some other ID) instead.

**Comment by wrenffxi** [comment]
Noted, and sorry about that.

**Comment by TeoTwawki** [comment]
np, I was confused and thought we had a bunch of non existent mods in the sql table for a few min, Hopefully its clearer now for the next dude after us.

**Comment by Hozu** [comment]
Oh... oh god I think I'm responsible for this one. Damn it.

**Comment by R3P0FFXI** [comment]
@Hozu its all good man its what caused the confusion on my initial PR for the mods.

**Comment by TeoTwawki** [comment]
Hozu if its any consolation it let me to noticing the other 3 lol

**Comment by teschnei** [comment]
when I added the WS dmg% modifiers, I made sure the MOD_SPARE were right...

**Pull request merged**
