### PR TITLE
PLD Traits

### PR DESCRIPTION
**Pull request by nfaletra**
* Added Undead Killer Tiers - https://www.bg-wiki.com/bg/Undead_Killer
* Fixed Resist Sleep Values - https://www.bg-wiki.com/bg/Resist_Sleep
* Added Resist Sleep Tier
* Added Shield Mastery item mod - https://www.bg-wiki.com/bg/Shield_Mastery
* Implemented Iron Will - https://www.bg-wiki.com/bg/Iron_Will
* Added Shield Def. Bonus - https://www.bg-wiki.com/bg/Shield_Def._Bonus
* Implemented Crit. Def. Bonus - https://www.bg-wiki.com/bg/Crit._Def._Bonus
* Linked Iron Will and Guardian traits to appropriate merit IDs

Also cleaned up lua code around the areas I touched to conform to the style guide.

### CODE REVIEW

**Comment by teschnei** [comment]
do we know for sure that crit def bonus is additive with crit dmg bonus in the same way that mab/mdb is? if there's no concrete proof i'm fine with it this way, just want to be sure it's been attempted to be researched

**Comment by nfaletra** [comment]
Only proof I have is what BG-WIKI says.

`Reduces critical hit damage.
Appears to be additive with Critical Attack Bonus, so someone with 14 Critical Attack Bonus fighting a level 99 Paladin monster would net 0 Critical Attack Bonus.`

**Comment by nfaletra** [comment]
There are links to some research data on the bg-wiki page, too.

**Comment by nfaletra** [comment]
This is the last time I try to style guide stuff. . .My eyes hurt.

**Comment by nfaletra** [comment]
For future reference, is it possible to run the lua check locally?

**Comment by TeoTwawki** [comment]
yeah https://github.com/mpeterv/luacheck/releases

**Pull request merged**
