### PR TITLE
MOBMOD_STANDBACK_TIME no longer exists

### PR DESCRIPTION
**Pull request by TeoTwawki**
Did not test (and not going to) If the behavior was changed as well as the name, I'll push it off onto the guy that broke this and close the PR.

### CODE REVIEW

**Comment by bendangelo** [comment]
Wait, the new mod `mobmod_standback_cool` is different from the old one. This mod will make the mob cast magic more often when it is not within melee range. I think the original intent was to prevent this mob from standing back. So maybe it should just be removed?

**Comment by TeoTwawki** [comment]
I can amend to comment it out if you think thats closer to the original behavior
I didn't look at wtf the replacement mod does relative to the original one and the descriptions of the old and new are ambiguously similar (not digging through old source to compare them, ya know?)

**Comment by TeoTwawki** [comment]
@bendangelo amened, and thats as far as I go with this.

**Comment by teschnei** [comment]
FYI: yes the original intent was he never stands back.

**Comment by TeoTwawki** [comment]
I should have mentioned at the start: the reason I made this quickfix is it was crashing servers by calling nil modifier, and the guy in IRC didn't know why so I looked.

**Comment by teschnei** [comment]
I think that much was evident in your original email :)

**Comment by bendangelo** [comment]
Looks good thanks

**Pull request merged**
