### PR TITLE
Corrected mobTypes in all Dynamis zones according to mobentity.h

### PR DESCRIPTION
**Pull request by Brierre**
battlefield normal mob = 16
battlefield NM = 18
battlefield called (pet) = 24
battlefield NM pets = 26

I had found that Count Raum in DX was occasionally spawning as a trash mob and looked to see that he was listed as a normal mob.  There were several other NM who were mobType the same way.  Hopefully this helps in some fashion.

### CODE REVIEW

**Comment by TeoTwawki** [comment]
> battlefield normal mob = 16
battlefield NM = 18
battlefield called (pet) = 24
battlefield NM pets = 26

Clarification needed: are your values in decimal or hex in the above list you posted?

```cpp
    MOBTYPE_NORMAL      = 0x00, // or 0 in decimal
    MOBTYPE_PCSPAWNED   = 0x01, // or 1 in decimal
    MOBTYPE_NOTORIOUS   = 0x02, // or 2 in decimal
    MOBTYPE_FISHED      = 0x04, // or 4 in decimal
    MOBTYPE_CALLED      = 0x08, // or 8 in decimal
    MOBTYPE_BATTLEFIELD = 0x10, // or 16 in decimal
    MOBTYPE_EVENT       = 0x20  // or 32 in decimal
```
Is what we use, and they can be combined (add them in decimal from)

**Comment by TeoTwawki** [comment]
um..we don't have a type for pets in that field.

**Comment by Brierre** [comment]
All pets already had the "Called" mob type except for the three NM in
Xarcabard, which were listed as normal.  I changed those three,  plus the
other two NM pets in the list to reflect NM (source,  ffxiclopedia).

**Comment by TeoTwawki** [comment]
must be some ancient leftovers...Since they don't do anything no harm in merging that.

**Comment by TeoTwawki** [comment]
P.s.

Love the branch name

**Pull request merged**
