### PR TITLE
more bits for the rng

### PR DESCRIPTION
**Pull request by TeoTwawki**
testing was very minimal, but that oughta initialize it more gooder :+1:

### CODE REVIEW

**Comment by TeoTwawki** [comment]
@teschnei -nudge-

**Comment by teschnei** [comment]
Out of town til January, but I'm pretty sure it's good

**Comment by TeoTwawki** [comment]
guess you forgot you already reviewed it a week ago

**Comment by TeoTwawki** [comment]
_-nudge nudge nudge nudge nudge nudge-_
@teschnei

**Comment by teschnei** [comment]
my 2fa for github won't let me log in and I'm too lazy to go through github
support right now

**Comment by TeoTwawki** [comment]
2FA STRIKES AGAIN @whasf

**Pull request merged**
