### PR TITLE
SQL: Correct Dynamis Bastok mega boss mobskill list

### PR DESCRIPTION
**Pull request by Hozu**
Totally shouldn't have the quadav NM moves.

### CODE REVIEW

**Comment by bendangelo** [comment]
Actually, mob skill list 705 is correct. The skills in the list are just wrong, the skill list should contain all Adamantking Effigy skills plus wrath of gu`dha.

**Comment by Hozu** [comment]
I haven't come across any reference as to the mega boss having that move. Nothing about it on dynamisbums from what I was told.

**Comment by bendangelo** [comment]
http://ffxiclopedia.wikia.com/wiki/Dynamis_-_Bastok. Actually it's all Quadav NMs have this skill. So the skill list was set on the wrong mobs.

**Comment by Hozu** [comment]
So the statue shouldn't have the move, yes? Just the statue moves?

**Comment by bendangelo** [comment]
ok it's correct then

**Pull request merged**
