### PR TITLE
Metalworks Elevators

### PR DESCRIPTION
**Pull request by areckx**
https://github.com/DarkstarProject/darkstar/blob/7c23efa653cd3f78b45c8500f42b4e09d6fc579d/src/map/lua/lua_baseentity.cpp#L1892

### CODE REVIEW

**Comment by areckx** [comment]
Testing for awhile. For some reason the value 1 will result in a zero during the check or something like that. elevators.sql seems to not be used at all, so that should be removed. looking into why 6 seems to be working (or I'm guessing any value above 1) because what I think is happening is that the 1 is being subtracted by 1 and making it 0, resulting in isPermanent check to set value to 0

**Comment by Wiggo32** [comment]
What is the issue you are trying to address with this? And what does this change do to gameplay?

**Comment by helixhamin** [comment]
https://github.com/DarkstarProject/darkstar/blob/master/scripts/zones/Metalworks/npcs/_6lt.lua

**Comment by Wiggo32** [comment]
does deleting those values from the database resolve the issue with the elevators? meaning, do they now work flawlessly as they're supposed to?

**Comment by TeoTwawki** [comment]
the elevators sql table isn't even used anymore, its a relic.

**Comment by Wiggo32** [comment]
awww... i though he might have fixed it finally... so we probably shouldn't have that table in our database then?

**Comment by TeoTwawki** [comment]
I've got fix incoming tonight

**Pull request closed without merging**
