### PR TITLE
Windurst 8-1, 8-2, 9-1

### PR DESCRIPTION
**Pull request by OzmaEra**

### CODE REVIEW

**Comment by gedads** [comment]
Nice, just one small problem, the script for zones are still on the old var i used back then windurst81 but the mission var is now missionstatus

**Comment by OzmaEra** [comment]
Thanks, but I'm unsure what these cutscenes even have to do with Vain. The wiki makes no mention of them. http://ffxiclopedia.wikia.com/wiki/Vain

Are you sure these are related to the mission?

**Comment by xdemolish** [comment]
any of these involve the talking doll? cause if they do, you need to make sure that works too

**Comment by gedads** [comment]
all zones are the talking dolls telling you to go north south east west etc. Worked after server message thing was fixed, should be still working.

**Comment by gedads** [comment]
Hi, i'll have another look at it sunday night then i'll push it, i'm leaving for the week end and i'm in a hurry this morning. sorry for the delay

**Pull request merged**
