### PR TITLE
Fixed Oupire's spell list. Added spells:

### PR DESCRIPTION
**Pull request by Fiocitrine**
Blizzaga III
Waterga III
Aeroga III
Firaga III
Stonega III
Thundaga III
Blizzard IV
Aero IV
Water IV
Stone IV
Thunder IV
Fire IV
Poisonga III
Breakga
Dispelga
Bindga
Blindga
Graviga
Sleepga II

### CODE REVIEW

**Comment by whasf** [comment]
Thanks, but does the monster do what the wiki says it does? http://ffxiclopedia.wikia.com/wiki/Oupire

**Comment by Fiocitrine** [comment]
Not entirely. TP moves for this mob aren't scripted for DSP ( as far as I know) to allow it access to the individual elemental spell lists These can be changed when TP moves are added. Also the mob is missing 100% double attack trait. This is beyond my knowledge of DSP to implement.

**Comment by Fiocitrine** [comment]
hmmm why did AppVeyor build fail?

**Comment by bendangelo** [comment]
Thanks for contributing :heart:

**Pull request merged**
