### PR TITLE
tabled homepoint functions

### PR DESCRIPTION
**Pull request by wrenffxi**

### CODE REVIEW

**Comment by TeoTwawki** [comment]
Want a emurder player vars.. baaaaadly.

Would you be so kind as to move those to char_unlocks table? Its ok if you don't wanna just thought I'd ask

**Comment by wrenffxi** [comment]
I'm not at all familiar with char_unlocks. what are the bindings i'd use to read and write homepoints there?

**Comment by TeoTwawki** [comment]
Its same as when you save the ourposts data with some minor cpp change

I moved non currency things out of char_points to form cha_unlocks

**Comment by TeoTwawki** [comment]
ah yeah..the markers are reading player vars...

**Comment by TeoTwawki** [comment]
ima just merg this, we're work on ebil charvar to sql blob conversion later

**Pull request merged**
