### PR TITLE
[#5865] Earthbreaker shouldn't wipe shadows like AOE magic 

### PR DESCRIPTION
**Pull request by zach2good**
Original Issue:
https://github.com/DarkstarProject/darkstar/issues/5865

Seems simple enough

### CODE REVIEW

**Comment by Delkathus** [comment]
According to bgwiki and ffxiclopedia it supposed to wipe shadows.

https://ffxiclopedia.fandom.com/wiki/Earthbreaker
https://www.bg-wiki.com/bg/Category:Scorpion#Abilities

**Comment by TeoTwawki** [comment]
@Delkathus we have video footage showing wiki incorrect, see the reported issue for a link.

@zach2good if the param has it wipe "up to" 3 shadows but the skill does a single hit, its gonna take just one still. Confirm the behavior. 

We also need proper multihit anyway to do the skill correctly if it really is multihit, but if this change does what you were expecting that can be a separate PR.

**Comment by zach2good** [comment]
Just did some testing with Serket

_MOBPARAM_WIPE_SHADOWS:_
`Test's Copy Image (3) effect wears off.`

_MOBPARAM_3_SHADOW:_
`1/2 of Test's shadows absorb the damage and disappear`

using _MOBPARAM_3_SHADOW_ recreates what we see in the videos :)

**Comment by isotor** [comment]
I've tried building this and unfortunately it doesn't work as it's lacking any sort of multihit parameter. I'm guessing what this adjustment does is cause shadows to be removed using some sort of math.random when it should be based on the hitrate of the ability (see my comment about `numhits` in the report).

Without `numhits` or something similar there is never any chance of damage overspill. What I mean here is if you have *any* number of shadows Earthbreaker won't do any damageᵗ, which is incorrect.

ᵗ *I've eaten around 50 earthbreakers testing this locally with between 1-3 shadows and never taken damage*

**Comment by isotor** [comment]
Addendum: not my call but this turns the skill from a truck into a kitten, personally I'd err on the side of overtuned *(current)* instead of very weak *(this PR)* until the right answer is found.

**Comment by zach2good** [comment]
Now that I've slept on it, I agree with @isotor. Its better for now for the skill to be far too powerful than far too weak. I'll take another crack at this in a couple of days 👍

**Comment by isotor** [comment]
A few comments for your next crack at this @zach2good:

1. I tried simply changing it to a `MobPhysicalMove` in order to use the existing `numhits` class and went to punch Serket a bunch on 75 MNK *(B+ eva)* and was avoiding all hits at a much higher rate than I should have *(compared with the video in the issue and others I reviewed yesterday)* so assuming a similar implementation I'd suggest an `accmod` greater than 1 as a baseline.
2. The issue with Earthbreaker almost certainly extends to the normal mob equivalent move Earth Pounder, so may as well kill two birds with one PR 👍

**Comment by TeoTwawki** [comment]
```
I'm pretty sure from watching YT for sources on this yesterday I encountered a few instance of "[Name] evades.".
```
I'm pretty sure its physical based on that, unless a status is being evaded and not the damage thats a strong indication its a physical move.

**Pull request closed without merging**
