### PR TITLE
Core/SQL: Implement AGI boost version of "Enhances Trick Attack"

### PR DESCRIPTION
**Pull request by Hozu**
Mod give % AGI bonus to Trick attack, and if the mod is on a piece of equip, it has to be equipped on hit.
Added said mod to Rogue Armlet's +1 (15% bonus AGI).
Gave a proper description for my "Enhances Drain/Aspir" mod from earlier.

### CODE REVIEW

**Comment by Joeyjohjjo** [comment]
Thanks for doing this. However, shouldn't Vajra (ID 18996) also have a modifier of 10?

**Comment by Hozu** [comment]
Vajra "enhances Sneak Attack" is actually different - it increases the critical damage by 10%. That's why I included AGI when I named the modifier. https://www.bg-wiki.com/bg/Vajra_%28Level_75%29

**Comment by teschnei** [comment]
It's just flat damage bonus actually - it stacks differently than with
actual critical hit damage

**Comment by Hozu** [comment]
Oh? Interesting. And that is why I didn't add the mod for Vajra. I did THF AF+1 hands by request.

**Comment by teschnei** [comment]
note that since SA/TA are always crits, they work out to be the same except in regards to stacking with other crit damage, so it's not really a big difference

either way, it does not multiply DEX/AGI like rogues/raiders gloves do

**Pull request merged**
