### PR TITLE
CORE: Add new latent check

### PR DESCRIPTION
**Pull request by BRFord88**
Added LATENT_WEAPON_DRAWN_MP_OVER for use with the runic weapons.

### CODE REVIEW

**Comment by xdemolish** [comment]
tabs > 4 spaces :p

**Comment by BRFord88** [comment]
Sorry, my first time ever working with C++ or H.  Is this worth going back and fixing? Also is this on the line where it says LATENT_WEAPON_DRAWN_MP_OVER      = 56, part?

**Comment by xdemolish** [comment]
yep, that and where you added the cases for it
in terms of functionality it won't make a difference but tabs have different sizes across editors and so generally come out ugly so we ask to replace with 4 spaces instead

**Comment by BRFord88** [comment]
Ok, I see where I messed up.  I'll repull here soon.

**Pull request closed without merging**
