### PR TITLE
Synthesis Recipes

### PR DESCRIPTION
**Pull request by RwNigma**
Adding Synthesis Recipes on lines 3555 to 3566: 
Candelabrum
Orichalcum Ring (Desynth)
Peiste Leather
Peiste Leather x3
Angelstone (HQ is Selenite, HQ2 and 3 is Carbutear)
Painite (HQ is Deathstone, HQ2 is Tenebrite, HQ3 is Fenritear)
Wyrdweave
Akaso-Thread
Akaso-Cloth
Angelskin-Orb
Oxblood-Orb
Oil-Soaked Cloth

Previous Commits were sloppy. The lines of 359X and 36XX didn't even exist and I wanted to make this one commit for the pull request.

### CODE REVIEW

**Comment by RwNigma** [comment]
Keep getting "cannot squash without previous commit."

**Comment by teschnei** [comment]
can't help if you don't say what you're doing

**Comment by RwNigma** [comment]
Yeah sorry. I am trying to squash my commits so I don't have 13 of them. I am using git rebase -i HEAD~13 then it brings up around 748 commits. I abort it. 

When I try to use a smaller number it doesn't catch them all. However using git rebase -i HEAD~7 I can locate 7 of them. 
squash 6751c8c Update synth_recipes.sql
squash 789a523 Update synth_recipes.sql
squash e3b23df Update synth_recipes.sql
squash ecd08f3 Update synth_recipes.sql
squash 5de0ce9 Update synth_recipes.sql
squash 5eceadd Update synth_recipes.sql
squash db1b438 Update synth_recipes.sql
pick 8ab9007 Update synth_recipes.sql
Rebase 7c399af..8ab9007 onto 8ab9007
which gives me the "cannot squash" error.

**Comment by RwNigma** [comment]
In all fairness I say someone with more knowledge just takes the lines that I added and send it into DSP. Its been a few days and I still can't get this correct.

**Comment by teschnei** [comment]
okay, first of all: never use master branch for pull requests. since you
did, copy your synth_recipes.sql somewhere. then git reset --hard master to
get your master back to unchanged.  then update your master to latest
(fetching the dsp master, and merging it to your master).  then, check out
a new branch for your changes (git checkout -b something).  then, paste the
synth_recipes.sql you saved earlier, and make a commit with those changes.
then you can open a new pull request on it.
from now on, try not to merge to your branch while you have a pull request
open - it makes rebasing more annoying if you don't know what you're doing.
 if you need to merge (maybe because there are conflicts or something),
then you should use the rebase option for merges (--rebase), which will
undo your commit and reapply it on top after the merge.  If you keep your
commits at the head, squashing commits is trivial
and since you asked, no, I'm not going to do it for you: it just encourages
contributors to give up and make me do it for them (which I don't have time
for)

**Comment by RwNigma** [comment]
Going to close this Pull Request and follow Teschnei's instructions.

**Pull request closed without merging**
