### PR TITLE
Erase DIMENSIONAL_PORTAL_UNLOCK setting from existence

### PR DESCRIPTION
**Pull request by TeoTwawki**
Just comment out the mission check if you want this feature.

Present me questions how past me got things merged sometimes.

PR'd to bcnm branch to avoid extra conflicts later and give a sort of heads up.

### CODE REVIEW

**Comment by ZeromusXYZ** [comment]
Probably just so all QoL settings are found in the same place, and you don't need to edit multiple lua's ?

**Comment by zynjec** [comment]
```scripts/zones/Konschtat_Highlands/npcs/Dimensional_Portal.lua:16:58: (E011) expected 'then' near ')'
scripts/zones/La_Theine_Plateau/npcs/Dimensional_Portal.lua:15:58: (E011) expected 'then' near ')'
scripts/zones/Tahrongi_Canyon/npcs/Dimensional_Portal.lua:16:58: (E011) expected 'then' near ')'```

**Comment by TeoTwawki** [comment]
I created it actually. its 3 lines to comment out. its 7 lines to make into a setting.

**Comment by TeoTwawki** [comment]
fixed the sneaky `)` that got by me

**Pull request merged**
