### PR TITLE
Attempt to make nation mission 5-1 less retarded and more like retail. ...

### PR DESCRIPTION
**Pull request by TeoTwawki**
...Not supposed to have all 7 mobs on you at battle start. See issue #918

Pop timing may need adjusted, I have gone with 30 seconds. Neither wiki has an exact duration between pops specified. This does not address everything I brought up in issue #918 just the skeleton repops and initial agro state.

### CODE REVIEW

**Comment by teschnei** [comment]
pretty sure you dont need to script mobs to link in bcnms anymore, it should be done automatically

**Comment by TeoTwawki** [comment]
then I can replace spawnmob(id):updateemnity with just spawnmob(id) and make sure that the warriors do not start pre-popped. Amending.

**Comment by TeoTwawki** [comment]
Updated and fully tested even multi boxed in more characters to fix the 2nd and 3rd battlefields that had mobs and players not arriving in same battlefield.

**Comment by TeoTwawki** [comment]
The other mobs didn't need scripts at all, so I deleted them since i have everything handled in the Archlich's script (and sorcerers already link to him). The warriors I had to updateEmnity() in their spawn command though or they'd stand there doing nothing.


https://github.com/DarkstarProject/darkstar/pull/1001/files?w=1

**Pull request merged**
