### PR TITLE
Dsp shareback items

### PR DESCRIPTION
**Pull request by Loki79**
More items added.   Left out any +skill weapons.

### CODE REVIEW

**Comment by teschnei** [comment]
No adoulin items, please.

**Comment by Loki79** [comment]
oh you want no adoulin items at all?  i left out all the +skill weapon content, was unaware you didn't want anything.

**Comment by teschnei** [comment]
Correct, none at all. 99 cap only :)

**Comment by Loki79** [comment]
Do I need to keep them out of _basic, _weapon, _armor as well?  or just mods?  Currently we have custom _mods that execs after main to keep updates simple but been trying to keep the other 3 the same as main repo.

**Comment by teschnei** [comment]
Yep. Its not a question about custom mods or anything like that, it's
making sure that DSP never conflicts with the players of retail (ie does
not offer what retail offers)

**Comment by Loki79** [comment]
ok thanks, was unaware of that policy.  Sounds like we will need to create some other custom sql's and ill sift through and amend this commit.

**Comment by teschnei** [comment]
Thanks :)

**Comment by helixhamin** [comment]
I am confused. I was under the impression that anything that was in retail was fair game to submit. You are saying that we cannot commit the most current items available on retail? Just trying to understand myself.

**Comment by teschnei** [comment]
Yep.

**Pull request merged**
