### PR TITLE
stop using getShortID for the value of a mobmod where that value never matters

### PR DESCRIPTION
**Pull request by TeoTwawki**
This began as just being copy pasted from an existing script from an author that isn't around, we have no idea what his original intent was but whatever it was, it never happened. the value is never used the code just checks if this is zero or non zero.

### CODE REVIEW

**Comment by TeoTwawki** [comment]
gee if only Wren had accepted a dev position, I could merge now..

:cry:

**Comment by KnowOne134** [comment]
You ungrateful he-bitch

**Comment by TeoTwawki** [comment]
well, that escalated quickly!

**Comment by TeoTwawki** [comment]
AH WUZ DRUNK! SO WUZ DA BABY MAWMA!

**Pull request merged**
