### PR TITLE
Remove unneeded nil lines from headers.

### PR DESCRIPTION
**Pull request by TeoTwawki**

### CODE REVIEW

**Comment by TeoTwawki** [comment]
*REEEEEEEE*based

**Comment by wrenffxi** [comment]
a lot of those mobids nils are needed.

batallia downs mobIds contains CERMET_HEADSTONE which conflicts with headstones in other zones.
cape terrigan, buburimu contains SIGNPOST_OFFSET which does the same
etc

**Comment by TeoTwawki** [comment]
we're going to have to change the var names it'll get lost like this because its unexpected.

**Comment by TeoTwawki** [comment]
Todo (likely I'll get to it as soon as BCNM branch gets merged to master, as I have pr waiting that needs gone first): rename mobIDs.lua to EntityIDs.lua sicn eit now contains NPC's as well, and set both all of those and TextIDs.lua's to be returned tables so nothing needs nil'd ever again. See also: https://github.com/DarkstarProject/darkstar-utils/issues/15

**Comment by TeoTwawki** [comment]
coming back to this later

**Pull request closed without merging**
