### PR TITLE
SQL Items mods

### PR DESCRIPTION
**Pull request by some1here**

### CODE REVIEW

**Comment by bendangelo** [comment]
What does this change?

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/pulls?q=is%3Apr+author%3Asome1here+is%3Aclosed
round and round we go

**Comment by xdemolish** [comment]
you forgot the other 20 pulls
edited your comment with ficks

**Comment by TeoTwawki** [comment]
those got lost when he managed to delete and recreate his github account
https://github.com/DarkstarProject/darkstar/pull/1748
They don't show on the filter list because of that

**Comment by TeoTwawki** [comment]
@some1here When you jam this much at once in a PR, we can't even see it in a diff report on github. That means just to see what you did I have to actually download your changes and view them locally. And I doubt anybody wants to go to line by line verify your work. Either comment* it all or explain and convince someone that you made sure its all correct. I told you this when you PM'd me about it. Since them you've opened and closed upwards of 20 pull requests for the same changes and still have mostly the same issues in your file . As pain in the ass as it is, I checked it out locally to look, hoping against all odds that this one would be good enough to end this. No such luck.

( * *Yes people, I know comments get wiped in redumps - still helps see wtf you are adding when the lines are new*! )

**Comment by Loki79** [comment]
Careful what you ask for....  Probably get a 33,381 line comment incoming soon now!  >.>

**Pull request closed without merging**
