### PR TITLE
Scripts/ quest: Gifts of the griffons - Modified quest so the plumes d'or can be distributed in any order.

### PR DESCRIPTION
**Pull request by Vivitarut**

### CODE REVIEW

**Comment by TeoTwawki** [comment]
I didn't look real hard, but if those are all for same thing can prolly use 1 var with `setMaskBit`/`getMaskBit` and then once all bits are set can check that with `isMaskFull`.

**Comment by TeoTwawki** [comment]
see npc's involved in *Lure of the Wildcat*, or *Snake on the plains*, for examples.

**Comment by Vivitarut** [comment]
Thanks Teo, i didn't realize there were bitwise functions available! I'll modify it again.

**Comment by teschnei** [comment]
we do have luaJIT as well, which means you can also use the bit library (bit.band, etc) anywhere

**Comment by Vivitarut** [comment]
@teschnei

Good to know, thanks!

**Comment by xdemolish** [comment]
should prolly set the player:getVar as a var in the script, for readability e.g.
```
local mask = player:getVar("GiftsOfGriffonPlumes");

if player:getMaskBit(mask, thing) then
-- etc
```

**Comment by Vivitarut** [comment]
@xdemolish

Np, i'll modify it.

**Comment by xdemolish** [comment]
amend last commit > change commit message to include label > force push

oh, and leave a comment once the changes have been made so we know to take a look :p

**Comment by Vivitarut** [comment]
@xdemolish

Understood, i will do that next time, changes are done.

Thanks.

**Comment by Vivitarut** [comment]
Here's a quick walkthrough for faster testing:

  Louxiard                   @pos -90 -4 47 80
  Louxiard                   @pos -90 -4 47
  Rholont                    @pos -166 -2 54
Plumes:
  -Louxiard                   @pos -90 -4 47
  -Rongelouts N Distaud       @pos 0 2 -20
  -Machionage                 @pos -253 -4 104
  -Illeuse                    @pos -44 2 -32
  -Loillie                    @pos 80 -7 -20
  -Elnonde                    @pos 84 2 1
  -Sabillont                  @pos 6 2 -85

  Rholont                    @pos -166 -2 54

**Pull request merged**
