### PR TITLE
Allow Quest Empty Memories to flag as complete

### PR DESCRIPTION
**Pull request by Whitechaser**
Fix for #3761 

Note: I don't know how much fame to add at the end, so I looked up some repeatable quests already in the scripts and used that. Should hardly matter, I guess.

### CODE REVIEW

**Comment by Whitechaser** [comment]
Crud, I did it wrong. Resubmitting.

**Comment by takhlaq** [comment]
please don't close and reopen pull requests as it sends out emails whenever you do so
rebasing and force pushing to the pull requestsl's branch will update the pull requests for you

**Comment by Whitechaser** [comment]
Thank you! I'll do that from now on.

**Comment by TeoTwawki** [comment]
It also does stuff like not carry over any comments we leave on one to the other. So say Tahklaq said something important here and then is away and I review  your new PR without him - I might never realize he said anything and miss something important that needed to change. Just as an example.

**Comment by takhlaq** [comment]
>So say Tahklaq said something important

> important

hah

**Pull request closed without merging**
