### PR TITLE
remove level sync while entering bcnm, consume ammo during reward, update speed of sandworm

### PR DESCRIPTION
**Pull request by Scavenge**
people were apparently able to sync before entering a bcnm, and then unsync once inside in order to remove all level restrictions and be 75 for any bcnm.  this will prevent level sync from being active prior to applying the restriction for the bcnm.  there may be a better way to do this, considering that it probably shouldn't let you initiate the bcnm until you do not have level sync active at all, or just change your level restriction from the level sync's to the battlefield's.

### CODE REVIEW

**Comment by xdemolish** [comment]
holding off until someone with retail access confirms how it's handled

**Comment by teschnei** [comment]
do not mix unrelated things into a single pull request

**Comment by Scavenge** [comment]
I take it there is no way to separate changes that are all on the same branch and I'll probably have to create separate branches for them?

**Comment by teschnei** [comment]
That is indeed what you are supposed to do

**Pull request closed without merging**
