### PR TITLE
Mass find/replace of mistaken haste values.

### PR DESCRIPTION
**Pull request by helixhamin**

### CODE REVIEW

**Comment by helixhamin** [comment]
Changed title, since, while I was sure I had fixed something with Empyrean sets, I cannot for the life of me find the changes. Only the haste fixes...

**Comment by TeoTwawki** [comment]
is broke! 😢

**Comment by helixhamin** [comment]
Yes, I can't figure out why it is failing. It is literally just some find replace for haste gear

**Comment by TeoTwawki** [comment]
it says why right here: its has conflicts

rebase coz your previous changes changes some of the same lines, so when they got merged this one got broke

**Comment by helixhamin** [comment]
@TeoTwawki Okay, it seems I was able to finally get it all fixed after some trial and errors xD
Yeah, I noted the conflicts, but the details link was greyed out, so had no idea how to check.
Thanks for the heads up about rebasing, seems to have worked once I figured it out and fixed my attempts to fix conflicts.

**Pull request merged**
