### PR TITLE
Hopefully the last MR/Stray related PR of the year.

### PR DESCRIPTION
**Pull request by wrenffxi**
Strays no longer drop gil
Strays spawn every 5.5 minutes if MR is not engaged
Strays spawn in 20 second intervals if MR is engaged
Strays spawn at MR location and move outward

Addresses #433, #4201, and #4257 .

edit: and before anyone says "why does the MR spawn a stray immediately when engaged, instead of waiting 20 seconds", I considered this, and decided that resetting the 20 second timer onMobEngaged is problematic because on DSP mobs deaggro quickly when they're not smacking you.  MRs have no autoattack, so if you aren't meleeing them, they go white quickly, which would then reset the timer when someone nukes it, and a stray would never spawn during the fight.

### CODE REVIEW

**Comment by takhlaq** [comment]
summoning @Wiggo32 for review (i dont care to watch the vid)

**Comment by Wiggo32** [comment]
Yea, that's better than what it was for 'retail' accuracy.

**Comment by TeoTwawki** [comment]
Merging, since 'approval'

**Comment by Wiggo32** [comment]
If you put something like this along with the other one it will behave more like retail. Then you can keep the strays scripted (128) so they aren't able to pop all at the same time. Retail doesn't have strays popping at the same time even if they are all mass killed at the same time. Also, with this I'm not sure you need that Stray.lua except for the gil mod.

```
function checkStrayIdle(mob)
    local mobId = mob:getID();
    local numStrays = MEMORY_RECEPTACLES[mobId][2];
    
    if (os.time() > mob:getLocalVar("nextStray")) then
        for i = mobId + 1, mobId + numStrays do
            local stray = GetMobByID(i);
            if (not stray:isSpawned()) then
                mob:setLocalVar("nextStray", os.time() + 330);
                SpawnMob(stray:getID());
                break;
            end
        end
    else
        mob:AnimationSub(2);
    end
end;

function onMobRoam(mob)
    checkStrayIdle(mob);
end;
```

**Comment by Wiggo32** [comment]
no, don't think you can do that exactly, the local vars would conflict... but something along the line?

**Pull request merged**
