### PR TITLE
Updated zone.lua to add Escha - Zi'Tah

### PR DESCRIPTION
**Pull request by some1here**
added  Escha - Zi'Tah zone to the @zone command 
as per https://github.com/DarkstarProject/darkstar/blob/master/documentation/ZoneIDs.txt

### CODE REVIEW

**Comment by xdemolish** [comment]
commit titles should contain descriptive comments on what you're modifying

see comments on https://github.com/DarkstarProject/darkstar/pull/2271
https://github.com/DarkstarProject/darkstar/pull/2254
https://github.com/DarkstarProject/darkstar/pull/2253
https://github.com/DarkstarProject/darkstar/pull/2252

**Comment by bendangelo** [comment]
Change your commit message with `git commit --amend`, then `git push -f`

**Comment by some1here** [comment]
my remote permission is denied

**Comment by bendangelo** [comment]
Are you pushing to your remote? `git push {yourRemote} patch-42 -f`

**Comment by some1here** [comment]
git push origin patch-42 -f
remote: Permission to Darkstarproject/darkstar.git  denied to some1here.
fatal: UNABLE to access 'https://github.com/DarkstarProject/darkstar/darkstar.git/' : The 
requested URL returned error: 403

**Comment by bendangelo** [comment]
You have to push to YOUR remote not darkstar. `git add remote some git@github.com:some1here/darkstar.git`
`git push some patch-42 -f`

You'll need an ssh key and upload it to github.

**Comment by some1here** [comment]
git remote add some git@github.com:some1here/darkstar.git     (swamped add & remote)
git push some patch-42 -f

error:  src refspec patch-42 does not match any.
error: failed to push

**Comment by some1here** [comment]
Do I need a new code issued?

**Comment by bendangelo** [comment]
You need a commit to push.... Pull your branch, `git pull some patch-42`

**Comment by some1here** [comment]
git pull some patch-42

error: src refspec patch-42 does not match any.
error: failed to push refs to 'git@github.com:some1here/darkstar.git'

**Comment by bendangelo** [comment]
I can't keep helping you. You need to amend your commit then push it to remote. Look it up.

**Comment by some1here** [comment]
Well I have tried different things at different times I was hopping you could help.
I HAVE TRIED but the system does not allow me.

this was even the time before that i tried http://www.bnet.cc/threads/stupid-worthless-guys-question.1060/#post-2833

**Pull request closed without merging**
