### PR TITLE
Fix msg for Familiar

### PR DESCRIPTION
**Pull request by WiggoCaptures**
This was displaying: The <mob> uses Acid Mist. 
Now it displays: The <mob> uses Familiar.

### CODE REVIEW

**Comment by TeoTwawki** [comment]
We've a mistake in our documentation at the same line ([108](https://github.com/DarkstarProject/darkstar/blob/master/documentation/message.log#L108)) too:
```
108 - The <player> uses .. Pet's powers increase!
109 - The <player> uses .. Pet's powers increase!
```
it got duplicated, which probably lead to this mistake in scripts before we moved it to global.

**Comment by zynjec** [comment]
Unless I'm not understanding the issue correctly, I'm unable to reproduce on master.

Using Familiar yields me:
image

**Comment by zynjec** [comment]
Adding to that, it seems both of those messages in documentation are accurate.

image

**Comment by TeoTwawki** [comment]
huh. ok then.

**Comment by zynjec** [comment]
For whatever reason, one is an ability parameter, and another is weapon skill parameter, despite never being passed a WS.

image

**Comment by TeoTwawki** [comment]
wierd

**Comment by WiggoCaptures** [comment]
that fix was for mob's using familiar... go to dynamis bastok and get your beasttender to pop 2hr... read what it says

**Comment by TeoTwawki** [comment]
oh hey, mobs have same index as ws for mobskills. so thats why there are 2

**Comment by TeoTwawki** [comment]
so we're going to want both in the global.

**Comment by WiggoCaptures** [comment]
but... i suppose the messages are used for both mob and player... so maybe there's a different way it should be handled?

**Comment by zynjec** [comment]
A bit more detail would have helped then.

Either way, this fix isn't appropriate, as it'd break the player message.

**Comment by TeoTwawki** [comment]
FAMILIAR_MOB
FAMILIAR_PC

or something

**Comment by zynjec** [comment]
I did forget that mob abilities were in the weapon skill index!

So we just need something like:

```lua
FAMILIAR_PC = 108,
FAMILIAR_NPC = 109,
```

and then update `scripts/globals/mobskills/familiar.lua` to use `dsp.msg.basic.FAMILIAR_NPC`

**Comment by TeoTwawki** [comment]
I'd say `_MOB` not `_NPC`, but yeah

**Comment by WiggoCaptures** [comment]
I'd also have to update wherever it calls FAMILIAR_PC too right?

**Comment by TeoTwawki** [comment]
yes

**Comment by zynjec** [comment]
```$ git grep dsp.msg.basic.FAMILIAR
scripts/globals/abilities/familiar.lua:28:    ability:setMsg(dsp.msg.basic.FAMILIAR)
scripts/globals/mobskills/familiar.lua:24:    skill:setMsg(dsp.msg.basic.FAMILIAR```

**Pull request merged**
