### PR TITLE
SQL: Item_Basic Update AH categories

### PR DESCRIPTION
**Pull request by Ninjistix**
Update AH category to remove some Ex,R/E,iLv Items from AH, some items were in wrong category, removed GM gear from ah category also

### CODE REVIEW

**Comment by R3P0FFXI** [comment]
@Ninjistix where did you get the information that some of this should be removed from AH categories, im pretty positive some of the stuff you removed is sellable on the AH specifically the ilvl items.

**Comment by Ninjistix** [comment]
Ffxiah and most of them were rare exclusive or exclusive I'm sure the ah
never sold them, and I'm sure judge gear wasn't meant to be on ah

**Comment by Ninjistix** [comment]
When I get home I can triple check but the only items that might need to be confirmed is the ammo

**Comment by R3P0FFXI** [comment]
Theres ammo and Voay stuff thats wrong now @Ninjistix which was correct before

**Comment by Ninjistix** [comment]
fixed, and also fixing more categories based on BG FFXI WIKI

**Comment by R3P0FFXI** [comment]
Thanks @Ninjistix looks good @xdemolish

**Pull request merged**
